reduxjs/redux

examples/todo/Body.js
examples/todo/Header.js

Adds propTypes to todo example components.

add prop types to todo example

---

examples/actions/CounterActions.js
src/Dispatcher.js
src/utils/bindActions.js

https://github.com/gaearon/redux/pull/46#issuecomment-109605733

Simplify perform API

---

src/createDispatcher.js

* Hide OOP implementation
* Hide private API

createDispatcher should return binded functions

---

src/Dispatcher.js
src/components/Provider.js
src/createDispatcher.js

https://github.com/gaearon/redux/issues/51#issuecomment-109643666

hydrate() -> initialize(), dehydrate() => dispose()

---

src/Redux.js

More clearly state the purpose of the returned function.

Name returned unsubscribe function

---

src/Redux.js
test/createDispatcher.spec.js
test/exports.spec.js

Tests improvements will follow in another PR.
See https://github.com/gaearon/redux/pull/56#issuecomment-110797801

Adjust tests after API changes

---

test/createRedux.spec.js

This is (hopefully) a failing test for #90

Add failing test for #90

---

README.md

Updated README.md to fix typo

---

README.md

@gaearon @acdlite since many people are asking for that, I added the link to the WIP example.
Also a table of contents makes it easier to find the sections if the README is quite long...

Link to examples

---

src/utils/composeStores.js
test/composeStores.spec.js

Ignorning non-func values in composeStores

---

docs/middleware.md

Fixes https://github.com/gaearon/redux/issues/143

compose -> composeMiddleware

---

examples/todomvc/components/MainSection.js
examples/todomvc/package.json

- ToggleAll doesn't make sense when there are no todos and also it causes to state mismatch i.e, the toggle will be checked and newly entered todos are unmarked.  
- Update dep to redux@0.12.0

Toggle All fix in todo mvc

---

ROADMAP.md
TODO

We have many parallel topics currently under discussion and it's easy to get lost in them.
I think it makes it also easier for people to have a quick overview on where we are heading.
/cc @gaearon @acdlite

Create roadmap document

---

README.md

The build is currently failing because of a pull request. I changed the build icon to point at master.

Fixed build image to point to master branch

---

README.md

Added at @gaearon's request in #99.
Wasn't sure where exactly to put it, so I put it next to @emmenko's example.

added link to erikras' starter kit example in README

---

examples/todomvc/components/TodoTextInput.js

Currently if you blur the newTodo TextInput containing text you'll see a new todo item get added.
Blurring probably shouldn't have any effect on the newTodo TextInput.

TodoMVC - Do not save onBlur if newTodo

---

src/utils/composeReducers.js

Minor terminology fixes from comments here: https://github.com/gaearon/redux/pull/195/files#r33650741

Breaking changes: s/atom/store

---

examples/todomvc/components/TodoItem.js

The build is failing for many pull requests because of the todomvc example. I fixed a linting error.

Fixed broken todomvc lint

---

README.md

Add a section with ES5 examples

---

docs/store.md

Am I along the right lines here?

First attempt at updating docs for Redux Store

---

docs/react.md

Switches imports in react example to reflect separating out the packages

Reference react-redux within react.md

---

README.md

Update README: add link to Yo generator (Redux + Rails API)

---

README.md

Hi, I implemented the counter example for react native and added it to the example list.

added react native example

---

docs/Reference/API.md
src/createStore.js
src/utils/applyMiddleware.js

JSDoc improvements

---

docs/Basics/Getting Started.md

I find this ordering to be more clear IMO. I'm fine with this PR getting rejected =P

Update ordering or things

---

README.md

[Docs](http://gaearon.github.io/redux/) have a little bit unnecessary information in header :)

fix: remove badges from title

---

docs/api/Store.md
docs/api/applyMiddleware.md
docs/api/bindActionCreators.md
docs/api/combineReducers.md

fix some typos in the new docs

---

src/createStore.js
test/createStore.spec.js
test/helpers/actionCreators.js
test/helpers/actionTypes.js
test/helpers/reducers.js

#368 -- This one actually works and doesn't disable the entire test suite =)

Forbid dispatch from inside a reducer

---

examples/buildAll.js
examples/counter/actions/CounterActions.js
examples/counter/components/Counter.js
examples/counter/containers/App.js
examples/counter/package.json
examples/counter/store/createCounterStore.js
examples/counter/test/actions/CounterActions.spec.js
examples/counter/test/components/Counter.spec.js
examples/counter/test/containers/CounterApp.spec.js
examples/counter/test/jsdomReact.js
examples/counter/test/reducers/counter.spec.js
examples/todomvc/components/MainSection.js
examples/todomvc/package.json
examples/todomvc/test/actions/TodoActions.spec.js
examples/todomvc/test/components/Footer.spec.js
examples/todomvc/test/components/Header.spec.js
examples/todomvc/test/components/MainSection.spec.js
examples/todomvc/test/components/TodoItem.spec.js
examples/todomvc/test/components/TodoTextItem.spec.js
examples/todomvc/test/jsdomReact.js
examples/todomvc/test/reducers/todos.spec.js

tests for the examples

---

README.md

We're not releasing 1.0 yet, but I presume this will happen within a week.
If you haven't upgraded your project to 1.0RC, see the instructions this PR adds at the top of the README.

It's time for upgrading to 1.0RC!

---

SUMMARY.md
docs/recipes/README.md
docs/recipes/Reselect.md

Suggestions for improvement welcome!

reselect doc

---

README.md

I've created a [starter-project](https://github.com/dferber90/webapp-starter-pack) in which a lot of the setup work is already done. May be useful as a reference for other people.

add example webapp-starter-pack

---

docs/basics/Reducers.md

The repo has moved, thanks much for including it!

Update updeep's url

---

package.json

Modify package.json description

---

docs/introduction/Examples.md

As requested in https://github.com/gaearon/redux/pull/426

Merged changes to readme examples

---

docs/basics/DataFlow.md

Hi Dan,
I found the original sentence a bit hard to read and make sense of, thought I'd submit a PR to update.

slight rewording in Dataflow docs

---

docs/recipes/ReducingBoilerplate.md
docs/recipes/WritingTests.md

Hello, Dan! Thank you for your brilliant solution.
I've found some minor typos in new documentation, solved with this PR.

typo fixes in docs

---

docs/basics/Reducers.md

I removed the "..." in the ``Object.assign()`` discussion in favor of { visibilityFilter: action.filter } to avoid any confusion with the spread operator.

Minor help text improvements

---

PATRONS.md
README.md
docs/README.md

The work on Redux was [funded by the community](https://www.patreon.com/reactdx).  
Meet some of the outstanding companies and individuals that made it possible:
* [Webflow](https://webflow.com/)
* [Chess iX](http://www.chess-ix.com/)
* [Herman J. Radtke III](http://hermanradtke.com)
* [Ken Wheeler](http://kenwheeler.github.io/)
* Chung Yen Li
* [Sunil Pai](https://twitter.com/threepointone)
* [Charlie Cheever](https://twitter.com/ccheever)
* [Eugene G](https://twitter.com/e1g)
* [Matt Apperson](https://twitter.com/mattapperson)
* [Jed Watson](https://twitter.com/jedwatson)
* [Sasha Aickin](https://twitter.com/xander76)
Thank you.

Say thanks to Redux Patrons

---

README.md

grammar nit

---

docs/basics/DataFlow.md
docs/basics/UsageWithReact.md
src/utils/mapValues.js

Typos and grammatical fix

---

examples/counter/store/configureStore.js
examples/todomvc/reducers/todos.js

Came across these while studying the example code :)

Removing a few unused combineReducers imports in examples

---

docs/basics/DataFlow.md

Removed a "but" that was accidentally left in

Sentence fix in DataFlow.md

---

examples/async/index.html
examples/counter/index.html
examples/real-world/index.html
examples/todomvc/index.html

Examples: add doctype, move <script> inside body to please HTML

---

docs/introduction/PriorArt.md

So here's my humble suggestion to #552 .

Improves explanation about Elm

---

docs/api/applyMiddleware.md

Add a tip about conditionally applying middleware

---

README.md

Refs:
https://github.com/rackt/redux/issues/579
https://github.com/rackt/redux/issues/563

Mention that you need NPM to install things from NPM

---

docs/recipes/ServerRendering.md

Fixes #635
Our example is secure, but this adds some notes on how to handle security. Please let me know if I left anything out or have anything wrong, since it's an important topic to get right.

Add some notes on security in server-side apps.

---

docs/introduction/Examples.md
docs/recipes/ServerRendering.md
examples/universal/package.json
examples/universal/server.js
examples/universal/webpack.config.js
examples/universal/webpack.server.js

Sorry about so many PRs :neckbeard:
This addresses the comments in #640.

Add a console message to universal boot.

---

docs/README.md
docs/advanced/AsyncActions.md
docs/advanced/AsyncFlow.md
docs/advanced/Middleware.md
docs/advanced/README.md
docs/recipes/WritingTests.md

I made the changes we discussed about the order of async and middleware; I also tried to simplify some points. I'm not 100% satisfied with the results, but don't have time to do better. Hopefully, I updated all cross references, but if you remember more of them, please update those yourself.

Docs async switch

---

docs/advanced/Middleware.md

* Fixed reference to ordering of AsyncActions.md
* Fixed interval/timeout consistency in examples

Clean up middleware docs

---

docs/introduction/Ecosystem.md

Adding https://github.com/leoasis/redux-immutable-state-invariant to the ecosystem file.

Add redux-immutable-state-invariant to Ecosystem.md

---

docs/introduction/Ecosystem.md

I think this tutorial really deserves a link in official docs, not only is it very in-depth, but also promotes high-quality standards for writing code, e.g. TDD

Add a link to the great full-stack tutorial

---

docs/advanced/Middleware.md

Docs: added a couple of missing definite articles

---

docs/recipes/ReducingBoilerplate.md

Continues the discussion in #742.

Docs Changes on Action Creator Boilerplate Reduction

---

docs/advanced/AsyncActions.md

Update AsyncActions.md, fix code indentation

---

examples/todomvc/components/Footer.js

Cursor value should be 'pointer'.

fix style of todomvc filter links

---

README.md

I recently got married and changed my last name.

New link for offline docs (I'm Paul Kögel now)

---

examples/todos-with-undo/.babelrc
examples/todos-with-undo/actions.js
examples/todos-with-undo/components/AddTodo.js
examples/todos-with-undo/components/Footer.js
examples/todos-with-undo/components/Todo.js
examples/todos-with-undo/components/TodoList.js
examples/todos-with-undo/containers/App.js
examples/todos-with-undo/index.html
examples/todos-with-undo/index.js
examples/todos-with-undo/package.json
examples/todos-with-undo/reducers.js
examples/todos-with-undo/server.js
examples/todos-with-undo/webpack.config.js

Please let me know if this looks okay :grin:
As discussed, it is based off https://rackt.github.io/redux/docs/basics/ExampleTodoList.html and the counter example in this repo (for `package.json`, webpack etc).
This would close #599

add todos-with-undo example

---

README.md
docs/introduction/Examples.md

This pull request fixes #785
As in my previous pull request, there was an unexpected change to delete a space at the end of lines 10 and 11. When I saved the file from Atom editor? I hope that is not a problem.
Thank you for inviting me to make a pull request for the issue. The practice is very helpful to me.

Universal example inconsistencies

---

src/utils/combineReducers.js

Add prefix to randomly generated action type in combineReducers #792

---

docs/api/combineReducers.md

wording: combineReducers.md

---

docs/basics/DataFlow.md

Adds links to related Actions, Store and Reducers docs to the Workflow doc.

Add links to DataFlow.md

---

examples/real-world/createDevToolsWindow.js
examples/real-world/index.js

https://github.com/rackt/redux/issues/862
- adding try/catch when when devTools is throwing an error,
usually when the popup is blocked

ISSUE #862, unhandled error when devTools popup window is blocked

---

CNAME

As per [step 3 of the dns.js.org instructions](https://github.com/js-org/dns.js.org) and [github's documentation on CNAME files](https://help.github.com/articles/adding-a-cname-file-to-your-repository/).
Closes #890

Set up redux.js.org CNAME

---

docs/advanced/ExampleRedditAPI.md

- adds a missing semicolon to `return` statement

add missing semicolon

---

examples/todos-with-undo/components/AddTodo.js
examples/todos-with-undo/containers/App.js

Also removes ability to add an empty todo

todo undo example - from click to on submit

---

README.md

I think this is more what was trying to be said.
`takes a few minutes` by itself is like saying it takes time to get started with.
`only takes a few minutes` is saying it doesn't take much time to get started with.

Readme tinyfix

---

docs/basics/DataFlow.md

The 'name' field in the code snippet ('Megan') does not match with the name used in the description of the code snippet ('Mary'). Updated name in code snippet to match name used in description.

Fixed name in code snippet to match name used in description.

---

examples/shopping-cart/components/Cart.js
examples/shopping-cart/components/Product.js
examples/shopping-cart/components/ProductItem.js
examples/shopping-cart/components/ProductsList.js
examples/shopping-cart/containers/App.js
examples/shopping-cart/containers/ProductsContainer.js

minor fixes per @gaearon's request on PR #824; resolves #823

Shopping cart example fixes

---

examples/shopping-cart/containers/CartContainer.js

It's minor but it's helpful when someone try to follow the code. In addition, there's no point importing files we do not use.

be more explicit when importing files

---

examples/shopping-cart/containers/CartContainer.js

Reverts rackt/redux#984 because https://github.com/rackt/redux/pull/984#issuecomment-152665451

Revert "be more explicit when importing files"

---

docs/advanced/Middleware.md

removed extra newline causing the broken link

broken link to Store.md#getState

---

docs/advanced/AsyncActions.md

fix lint error for AsyncActions.md

---

docs/basics/Reducers.md

The current example throws a syntax error (unexpected token). Not sure if we can even use "...-syntax" in object literals? Maybe this example just got never checked. But please let me know if I'm wrong.

Docs example: Use Object.assign also for updating state.todos

---

docs/basics/UsageWithReact.md

Remove whitespace in docs

---

docs/basics/ExampleTodoList.md
docs/basics/UsageWithReact.md

Since TodoList's todos property is required, visibleTodos should be required too.

Make visibleTodos a required property

---

docs/advanced/ExampleRedditAPI.md

post.title appears to be a required property.

Specify shape of post elements

---

docs/recipes/ReducingBoilerplate.md

I'm just trying to make it consistent with the rest of the documentation.
You can view the first diff with the `--ignore-space-change` option to `git-diff`.

Use ES6 syntax and the spread operator

---

docs/introduction/Ecosystem.md

Automatically index resources in a web worker and search em without blocking.
Demo: https://treasure-data.github.io/redux-search/
Repo: https://github.com/treasure-data/redux-search

Add redux-search to ecosystem page

---

docs/introduction/Ecosystem.md

Not sure if it's proper to use `中文文档` here, it means `Chinese documentation`

Add translations part and Chinese docs link

---

docs/introduction/Ecosystem.md

It's also worth to add a Traditional Chinese doc.

Added Traditional Chinese doc to Ecosystem

---

docs/basics/ExampleTodoList.md
examples/todos-with-undo/actions.js
examples/todos-with-undo/components/TodoList.js
examples/todos-with-undo/containers/App.js
examples/todos-with-undo/reducers.js

Hey Dan — I believe this should fix https://github.com/rackt/redux/issues/1129 by generating a unique ID for every to do and updating correctly when a to do is completed. I went ahead and cleaned up the naming to reflect this as well.

Fix id-related bug in example ToDo app and update README

---

README.md

Really, really important pull request
Before | After
---|---
[![Changelog #187](https://img.shields.io/badge/changelog-%23187-lightgrey.svg)](https://changelog.com/187) | [![Changelog #187](https://img.shields.io/badge/changelog-%23187-lightgrey.svg?style=flat-square)](https://changelog.com/187)

Fix changelog badge to match style

---

docs/introduction/PriorArt.md

This is a really small, minor change and I for sure won't feel bad if you all decide this isn't important enough to consider :) Thanks for your time!
Reference: https://github.com/evancz/elm-architecture-tutorial/#the-basic-pattern

Correct type signature of Elm updater in prior art

---

docs/basics/Store.md

Adds documentation about unsubscribing store listeners to Store.md

---

docs/advanced/AsyncActions.md
docs/advanced/ExampleRedditAPI.md
examples/async/actions/index.js

fixes #1209 
And anyway direct link to host better than go through redirect every time

use https reddit endpoint

---

docs/recipes/ServerRendering.md

Match target element ID in server-rendered and client

---

LANGS.md

avoid confusion

---

docs/advanced/AsyncActions.md
docs/advanced/ExampleRedditAPI.md

Squashed merge commit message this time.

Replaced the word "reddit" with "subreddit" where subreddit is the correct term.

---

src/index.js

Added period on line 9 to match other comments

Add period on line 9

---

examples/real-world/containers/UserPage.js
examples/real-world/reducers/index.js
examples/real-world/reducers/paginate.js

Fixed the issue reported in #1270

fixed the issue with importing lodash methods in the real-world example

---

examples/real-world/containers/App.js
examples/real-world/containers/RepoPage.js
examples/real-world/containers/Root.dev.js
examples/real-world/containers/Root.prod.js
examples/real-world/containers/UserPage.js
examples/real-world/package.json
examples/real-world/reducers/index.js
examples/real-world/routes.js
examples/real-world/store/configureStore.dev.js
examples/real-world/store/configureStore.prod.js

As discussed here https://github.com/rackt/redux/pull/1152, this is a small proposition to update the `real-world` example with the latest version of `react-router-redux`
Feedback welcome !

Update real-world example with react-router-redux

---

docs/introduction/Ecosystem.md

Add redux-loop to enhancers

---

docs/api/Store.md
src/createStore.js

Clarification to reflect the conclusion from issue #1221.

Clarify that Store subscribe listeners should not expect to see all states

---

docs/introduction/Ecosystem.md

Deprecate for reasons outlined in https://github.com/gajus/redux-immutable/issues/12#issuecomment-176189454

Deprecate redux-immutablejs in favour of redux-immutable

---

docs/basics/ExampleTodoList.md
docs/basics/UsageWithReact.md

Bug in "Usage With React" and "Example Todo List" docs

---

examples/async/containers/App.js

use a variable `isEmpty` instead of accessing `posts.length` twice. Makes it more readable, and short enough for the whole expression to exist on one line.

use isEmpty variable in asnyc example

---

examples/async/containers/App.js

Less redundant and more transparent control flow.

Update Async example

---

docs/recipes/ComputingDerivedData.md

On line 70 probably was meant visibilityFilter

Mistake in ComputingDerivedData.md

---

docs/Troubleshooting.md
docs/api/createStore.md

There is no more experimental page on Babel website and object rest spread proposal has changed its stage

Update broken and old links in docs

---

docs/advanced/ObjectSpreadOperator.md
docs/advanced/README.md

Work towards https://github.com/rackt/redux/issues/1351. While the discussion on whether to update all examples to use the object spread syntax is ongoing, I think that either way it's a great thing to document.
This is a first draft, so let me know if there's any changes you'd like to see!

Add object spread documentation

---

docs/advanced/AsyncActions.md

Updated all the broken real world example links.

fixed real world example links

---

README.md

avoid horizontal scroll in the gitbook readme

---

docs/Feedback.md
docs/README.md

Add Feedback.md with a link to Product Pains and an <iframe> that embeds a Product Pains widget inline for feedback specifically relevant to Redux.

+ Feedback.md

---

examples/todos/test/actions/todos.spec.js

```toogleTodo``` -> ```toggleTodo```

fix minor typo

---

docs/advanced/ExampleRedditAPI.md

Fix docs, response instead of req in ExampleRedditAPI.md

---

docs/FAQ.md
docs/README.md

Here you go.  I created a new branch and added the completed contents of the FAQ page in a single commit, since I don't think all 49 individual commits really need to go into Redux's permanent history :)

Add an FAQ page to the Redux docs

---

docs/introduction/Ecosystem.md

Add Redux Ecosystem Links to the "More" section
Add both "Links" entries to the intro section for visibility.

Ecosystem page: add "Redux Ecosystem Links" entry

---

CONTRIBUTING.md

change `npm run check` to `npm run check:src`

fix CONTRIBUTING doc 'check' part

---

docs/recipes/WritingTests.md

Updated test docs following http://tobyho.com/2015/12/16/mocha-with-promises/

Simpler with mocha's built-in promise support

---

src/compose.js

```javascript
export default function compose(...funcs) {
if (!funcs.length) {
return (...args) => args[0]
} else {
const last = funcs[funcs.length - 1]
const rest = funcs.slice(0, -1)
return (...args) => rest.reduceRight((composed, f) => f(composed), last(...args))
}
}
```

Avoid every execution and allocation

---

docs/introduction/Ecosystem.md

redux-actions-assertions has assertions for multiple testing frameworks and libraries, like:
- [chai](#chai)
- [expect](#expect)
- [expect.js](#expectjs)
- [should](#should)

Add redux-actions-assertions

---

src/utils/warning.js

Better comment for dummy try...catch block

---

docs/api/Store.md

Closes #1627.
I believe the point is important enough to put it as the first one.
Looking forward to your comments.

Clarify dispatch() usage inside subscribe() listener

---

examples/real-world/containers/RepoPage.js
examples/real-world/containers/UserPage.js
examples/real-world/middleware/api.js

Fix real world to be case insensitive

---

docs/introduction/Ecosystem.md

Add redial to Ecosystem

---

docs/introduction/Ecosystem.md

#I think React is in our head stamped with ReactDOM.
So it may be clearer to specifiate React Native, even if there is no difference between using Redux within React nor React Native.
What do you think?
_Please, tell me if I need to change the branch name, or if I need to open an issue._

May we speak about React Native instead of React

---

docs/basics/UsageWithReact.md

The code in containers/AddTodo.js on page 2.5. differs from containers/AddTodo.js on page 2.6.
It should be the same as chapter 2.6. is just an overview of all the created components.
I chose to favor the code from 2.6. as I think the usability of a form (with a submit action) is better. (It allows you to press enter)

Update to reflect the code from the examples overview

---

PATRONS.md

I, Herman, setup up patreon account as an employee of HauteLook. The company should receive the credit for funding the project.

Correct PATRONS.md entry

---

docs/introduction/Ecosystem.md

Hope you are willing to have this listed - I've got lots of great feedback from people who have taken it!

Added Learn Redux to screencasts

---

examples/async/webpack.config.js
examples/counter/webpack.config.js
examples/real-world/webpack.config.js
examples/shopping-cart/webpack.config.js
examples/todomvc/webpack.config.js
examples/todos-with-undo/webpack.config.js
examples/todos/webpack.config.js
examples/tree-view/webpack.config.js
examples/universal/webpack.config.js
webpack.config.js

See http://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin

Fix typo: `OccurenceOrderPlugin` -> `OccurrenceOrderPlugin`

---

.github/ISSUE_TEMPLATE.md

Add an initial issue template based on React's template

---

docs/introduction/Ecosystem.md

HI guys,
Redux-bootstrap utility can be used to initialize Redux applications with ease:
```
import bootstrap from "redux-bootstrap";
import routes from "./routes";
import thunk from "redux-thunk";
import * as createLogger from "redux-logger";
import usersReducer from "./reducers/usersReducer";
import reposReducer from "./reducers/reposReducer";
bootstrap({
container: "root",                    // optional
initialState: {},                     // optional
middlewares: [thunk, createLogger()], // optional
reducers: {
usersReducer,
reposReducer,
},
routes: routes
});
```
You can learn more about it at [here](https://github.com/remojansen/redux-bootstrap/blob/master/README.md).
Thanks!

Added redux-bootstrap to utilities

---

docs/advanced/AsyncFlow.md

Simple grammar fix for documentation.

Added word for better sentence flow.

---

examples/todos-with-undo/index.js

Removed unused import from todos-with-undo/index.js

Removed unused import from todos-with-undo/index.js

---

docs/advanced/AsyncActions.md

Wording fix in AsyncActions.md

---

docs/recipes/WritingTests.md

Add fetch import to async creators testing example

---

README.md

http://ell.stackexchange.com/questions/49448/using-that-or-how-after-describe/49477#49477

Provides "how"

---

test/createStore.spec.js

Not sure how this crept in.
Let’s wait for Travis to pass and I’ll merge it.

Fix failing test

---

README.md

[You Might Not Need Redux](https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367#.eqv7ilqo9)
This article sufficiently states why you might not need Redux from the creator itself. Adding this to the documentation will help those people who are not able to decide whether they need Redux or not.
**Not sure if it is the correct place for the link, please suggest.**

Add a URL to 'You Might Not Need Redux'

---

docs/advanced/UsageWithReactRouter.md

english word tweak

---

docs/recipes/reducers/InitializingState.md

Typo fix in InitializingState.md

---

docs/Troubleshooting.md

Immutability helpers are mentioned elsewhere in the docs but I thought a reference here would be nice as I myself couldn't find the reason for my issues by looking at the troubleshooting page

Adding the case for nested state objects

---

docs/recipes/reducers/PrerequisiteConcepts.md

https://twitter.com/acemarke/status/782956839935893504
I will be honored if you decide to add this in the official docs. I hope the writeup will help people tackle this issue

Mark suggested adding this article about structuring app state to Prerequisite Concepts

---

docs/recipes/UsingObjectSpreadOperator.md

The object spread/rest operator is now stage 3
[Source](https://github.com/tc39/proposals#active-proposals)

Stage 2 => 3 for object spread/rest in docs

---

docs/introduction/Ecosystem.md

Update Ecosystem.md to add `ember-redux` link

---

docs/recipes/ServerRendering.md

I am not 100% sure if this is what you meant but this makes most sense to me.

improved comment, was a bit unclear

---

docs/README.md
docs/introduction/CoreConcepts.md
docs/introduction/README.md
docs/introduction/TheReduxWay.md

Following this thread : https://twitter.com/thedgbrt/status/797779637573128193
I've put the simplified explanation from @gaearon where it seemed to fit the most, just before the dive into the three principles in more detail.
It adds a bit of repetition to the flow of the whole section, but overall makes things clearer imo.
Let me know what you think.

Added chapter in docs intro

---

.travis.yml

Test against node v7

---

docs/advanced/ExampleRedditAPI.md

Added a line in handleChange() which fixes the issue of posts not being requested when a new subreddit is selected.

Updated ExampleRedditAPI.md

---

examples/todos-flow/src/types/index.js

See this [blog post](https://medium.com/@gcanti/immutability-with-flow-faa050a1aef4) for an explanation of the used tecnique

todos-flow example: make domain models immutable

---

examples/todos-with-undo/src/reducers/todos.js

Removed deprecated filter in the todos reducer

---

docs/advanced/AsyncActions.md

Docs: Add redux-pack to AsyncActions

---

docs/advanced/ExampleRedditAPI.md

:smile: https://twitter.com/acdlite/status/818934938141528064

Little fix from official guidelines

---

docs/recipes/ServerRendering.md

It's explained in the doc but it's better to not have any copy/pastable code with security issues.

SSR: de-fang JSON embed in example code

---

docs/introduction/CoreConcepts.md

It seems there's a missing article here for the indefinite noun "function", which is referred to as a singular noun with the article "a" in previous sentences.

Added article "a" for grammar consistency

---

examples/real-world/src/reducers/paginate.js

Fixes a small style nit with a return statement in the "real world" example.

Small coding style fix

---

docs/recipes/ServerRendering.md

Fixed typo in docs/recipes/ServerRendering.md

---

docs/FAQ.md
docs/README.md
docs/faq/ImmutableData.md
docs/recipes/README.md
docs/recipes/UsingImmutableJS.md

Adds a section of questions on using Immutable Data and Immutable.JS to the FAQ in response to the request in #1785 . Note that although I tried to make this as neutral as possible, this is inevitably an opinionated set of questions and answers (particularly the Best Practices section), so please point out any opinions that are too strong or just plain wrong!
Feedback welcomed.

Doc: Immutable Data FAQ

---

docs/recipes/reducers/PrerequisiteConcepts.md

I hope this will alleviate some of the confusion in #2239
[ci skip]

[docs] Revise long sentence about "pure" reducers.

---

examples/counter/package.json

updated dependencies in counter example

updated dependencies to last version

---

README.md

I never really linked to that one, but it might be useful to people.
Free as well.

Add a link to second video series about Redux

---

package.json

https://github.com/reactjs/redux/pull/2283#issuecomment-284915101

Remove legacy jsnext entry

---

docs/recipes/reducers/UpdatingNormalizedData.md

`lodash/object/merge` -> `lodash/merge`

Fix Module not found: 'lodash/object/merge'

---

docs/introduction/ThreePrinciples.md

Just a simple word change. Introspect means to examine one's own thoughts - like a human.

Introspect vs inspect

---

docs/advanced/UsageWithReactRouter.md

express deprecated res.sendfile: Use res.sendFile instead

converted sendfile() to sendFile()

---

docs/advanced/AsyncActions.md

See https://github.com/facebook/react/issues/6895

Explain how (not) to catch errors

---

docs/advanced/AsyncActions.md

A missing `>` was located at line #379

Fix of a typo in AsyncActions.md

---

examples/todomvc/package.json
examples/todomvc/src/components/Footer.spec.js
examples/todomvc/src/components/Header.spec.js
examples/todomvc/src/components/MainSection.spec.js
examples/todomvc/src/components/TodoItem.spec.js
examples/todomvc/src/components/TodoTextInput.spec.js
examples/todomvc/yarn.lock

Just a follow up update for some tests on todomvc example

Update todomvc specs with React v15.5.0 adding react-test-renderer

---

docs/basics/Reducers.md

If you talk about it, why not show it too

Add action imports for clarity

---

CONTRIBUTING.md

Just want to give people fair warning. Feel free to close this and write it better 😄

note about code style changes (reflect reality)

---

docs/introduction/CoreConcepts.md

`nothing magical` seems to be better than `nothing magic`

Small correction

---

examples/universal/server/server.js

The function needs to be declared before the actual call.

Changed order of function call in code

---

examples/universal/common/containers/App.js
examples/universal/server/server.js

Replaced es5 functions with arrow functions.
+1 for consistency. :)

Unify the usage of arrow functions

---

docs/basics/Actions.md
docs/basics/DataFlow.md
docs/basics/ExampleTodoList.md
docs/basics/Reducers.md
docs/basics/Store.md
docs/basics/UsageWithReact.md

As discussed in #2385 , I'm splitting that PR to smaller ones.
This PR apply prettier to docs/basics folder.

Prettier to basics folder

---

docs/advanced/AsyncActions.md
docs/advanced/ExampleRedditAPI.md
docs/advanced/Middleware.md
docs/advanced/UsageWithReactRouter.md

Prettier to advanced folder

---

docs/api/Store.md
docs/api/applyMiddleware.md
docs/api/bindActionCreators.md
docs/api/combineReducers.md
docs/api/compose.md
docs/api/createStore.md

#2385 
ok this is the last one

Prettier to api folder

---

docs/recipes/ComputingDerivedData.md
docs/recipes/ImplementingUndoHistory.md
docs/recipes/ReducingBoilerplate.md
docs/recipes/ServerRendering.md
docs/recipes/UsingImmutableJS.md
docs/recipes/UsingObjectSpreadOperator.md
docs/recipes/WritingTests.md

Prettier to recipes folder

---

examples/testAll.js

Changing the `var` to `const` in the [examples/testAll.js](https://github.com/reactjs/redux/blob/master/examples/testAll.js) file to make everything in ES6

change var to const

---

docs/faq/OrganizingState.md

Fixed a trivial type: determing -> determining

Fixed a typo

---

examples/async/package.json
examples/async/yarn.lock
examples/counter/package.json
examples/counter/yarn.lock
examples/real-world/package.json
examples/real-world/yarn.lock
examples/shopping-cart/package.json
examples/shopping-cart/yarn.lock
examples/todomvc/package.json
examples/todomvc/yarn.lock
examples/todos-flow/package.json
examples/todos-flow/yarn.lock
examples/todos-with-undo/package.json
examples/todos-with-undo/yarn.lock
examples/todos/package.json
examples/todos/yarn.lock
examples/tree-view/package.json
examples/tree-view/yarn.lock

Updating (almost) all npm packages, including react-scripts@1.0.1

chore(packages): Update npm packages in CRA examples

---

docs/recipes/UsingImmutableJS.md

Fix link to ImmutableData article

---

docs/basics/ExampleTodoList.md

Hi there,
This PR represent syncing docs with recent [PR](https://github.com/reactjs/redux/pull/2431).
Best,
Danko

syncing docs with recent PR (2431)

---

docs/recipes/reducers/SplittingReducerLogic.md

Fix a typo in Splitting Reducer Logic docs

---

src/bindActionCreators.js
test/bindActionCreators.spec.js

Revert #2279

---

docs/faq/Performance.md

Add new links to "Performance" FAQ section (#1785)

Add new discussion links to Performance

---

docs/basics/UsageWithReact.md

1. `VisibleTodoList` has not yet been introduced in the documentation
2. It's slightly confusing to see the combination of a component and container without preamble in a "here's the rest of the code" section.
3. What is a `ref`?

Clarify details on connecting with React

---

docs/basics/UsageWithReact.md

TodoList on line 414 should be replaced with VisibleTodoList to match the import statement in line 404. Either TodoList or VisibleTodoList works functionally, but VisibleTodoList demonstrates implementation of container component.

Line 404 -414 Agreement

---

examples/real-world/src/components/Explore.js

Hello. Here's a minor PR for you that replaces a string ref with a callback.

Use a callback ref in the Real World Example

---

docs/recipes/UsingImmutableJS.md

It was previously confused with the article's title above.
Was a bit puzzled when reading the docs. So I made a simple replace.
Hope you could merge it!

Corrected the name of the link for immutable.js library.

---

src/index.js

indent the comment

---

README.md

The current one looks like it's implementation of Redux library for WordPress (which has no sense…)

Improve note about WordPress framework

---

docs/recipes/reducers/NormalizingStateShape.md

Added missing comma to example.

Added missing comma

---

docs/introduction/Ecosystem.md

I wonder if you all would consider [redux-data-structures](https://redux-data-structures.js.org/) as a "staff pick". I got good feedback on it (and 85 stars on GitHub so far).

Add redux-data-structures to Ecosystem

---

docs/api/Store.md

The argument in the title and in the arguments list should be consistent between each other

Fix argument inconsistency in Store.md

---

docs/recipes/reducers/PrerequisiteConcepts.md

'Javascript and Immutability' The url is redirected to wrong location.

Update the article 'Javascript and Immutability' url

---

index.d.ts

This fixes the issue https://github.com/reactjs/redux/issues/2508

Remove @private flag on AnyAction type definition

---

docs/recipes/reducers/ImmutableUpdatePatterns.md

Revert "Doc fix: updateObjectInArray replaces with new value, not an obj."

---

docs/recipes/WritingTests.md
docs/recipes/reducers/InitializingState.md

nock doesn't work as far as I can tell. 
https://medium.com/@kellyrmilligan/testing-async-actions-in-redux-with-isomorphic-fetch-and-fetch-mock-35f98c6c2ee7
specifically mentioned in that article:
https://github.com/node-nock/nock/issues/409
https://github.com/node-nock/nock/issues/591

updates the testing section on async actions to use fetch-mock

---

docs/recipes/WritingTests.md

Revert "Update WritingTests.md"

---

docs/introduction/Ecosystem.md

:wave: This is a project I've been working on with some friends and coworkers for some time now. We think it's ready for others to use, so if you think it's worth adding to the Redux docs, we'd appreciate it!
If not, no worries. Thanks for reading! 👌

Add redux-resource to Ecosystem

---

docs/basics/Actions.md

Added punctuation to the second paragraph of the Action Creators section to make text easier to understand.
Link to updated section: http://redux.js.org/docs/basics/Actions.html#action-creators

Updated Action Creators second paragraph

---

docs/advanced/UsageWithReactRouter.md

It is related to https://github.com/reactjs/redux/pull/2509.
The `<NavLink />` needs to be changed accordingly.

Update react-router-dom <NavLink />

---

docs/faq/Reducers.md

- Fix a broken link and add the target text (#async-action-creators)
- Remove extra spaces

Fix broken link

---

docs/faq/ImmutableData.md

Spelling: immutably => immutability

---

docs/api/combineReducers.md

Clarify how combineReducers namespaces state.

Clarify combineReducers documentation

---

docs/basics/Reducers.md

Revert "Make clear where reducers act on a state slice instead of on whole state"

---

examples/async/src/actions/index.js
examples/async/src/containers/App.js
examples/async/src/reducers/index.js

See https://github.com/reactjs/redux/issues/2742.

Rename variable names to subreddit instead of reddit

---

examples/real-world/src/containers/Root.prod.js

Fix react-world production example

---

docs/introduction/Ecosystem.md

Was reading through the documentation and found this 404.

Link to data integration tutorial fixed.

---

examples/shopping-cart/src/components/Product.js
examples/shopping-cart/src/components/Product.spec.js
examples/shopping-cart/src/components/ProductItem.js
examples/shopping-cart/src/components/ProductItem.spec.js

https://github.com/reactjs/redux/issues/2769

ProductItem and Cart gives different prop for product quantity

---

docs/basics/Reducers.md

Was reading the docs and noticed this probably should be a full stop, not a semi-colon.

Fix punctuation error in Reducers.md

---

docs/introduction/Ecosystem.md

Fixes a number of missing repo links in the ecosystem.

Fixes missing repo links in Ecosystem.md

---

examples/real-world/src/middleware/api.js

I open an issue [#2803](https://github.com/reactjs/redux/issues/2803)

Fix real-world example got error message

---

docs/recipes/WritingTests.md

'compatability' => 'compatibility'
p.s. first time contributing :)

Fix a small typo

---

docs/introduction/README.md

This matches the other doc README titles

Change introduction/README.md title to <h1>

---

docs/advanced/UsageWithReactRouter.md
docs/basics/ExampleTodoList.md

Import and use the VisibilityFilters const from the actions file in the
documentation instead of using a hardcoded string.
To complement #2840.

Update Footer to use to use VisibilityFilters from actions

---

docs/basics/ExampleTodoList.md
examples/todos/src/actions/index.js
examples/todos/src/components/Footer.js

Kudos to @antoniwan for spotting the issue.

Fix examples and todo app with VisibilityFilters export

---

docs/recipes/ImplementingUndoHistory.md
docs/recipes/ServerRendering.md
docs/recipes/UsingImmutableJS.md

Some of the links in the recipes were broken, this PR fixes that

fixed broken links by removing /docs/

---

README.md

[docs]:Fix Documentation links

[docs]:Fix Documentation links

---

docs/advanced/Middleware.md

changed const to let in applyMiddleware function in Attempt #6

changed const to let in applyMiddleware

---

docs/faq/CodeStructure.md
docs/faq/General.md

Helping with some FAQ updates from #2854. Added 3 links to existing questions. 
Not much, but good for my first contribution to open source. Hope to keep helping :)

Docs(FAQ): Adding links to existing questions #2854

---

docs/basics/ExampleTodoList.md

Noticed this was not updated. Probably should consider syncing the actual code with the markdown files (Gatsby 🤔 )?

fix: update ExampleTodoList.md with regards to #2964

---

CONTRIBUTING.md

Due to the building workflow has changed, this documentation may need to update.
- update cjs build command
- add guidelines for esm build

Update CONTRIBUTING section Building

---

docs/basics/Reducers.md

"describe the fact that *something happened*" can be nothing more than a BEEP that is irregular and inconsistent in it's response to an input, while an action (that is of any use beyond a '*' (all)) is going to describe (as defined by the author) *what happened*, through a series of one or more descriptors/data points.

Update Reducers.md to be a bit more succinct

---

src/combineReducers.js
src/utils/actionTypes.js

Make the code style more uniform

Move PROBE_UNKNOWN_ACTION to utils/actionTypes.js

---

docs/advanced/AsyncFlow.md

Changed "Now you saw" to "Now that you've seen"

Small grammar correction

---

docs/advanced/NextSteps.md

Hi there! Made a few typo/grammar fixes, and a couple of small wording changes.   Thanks for the great docs :)

Docs(Advanced > NextSteps.md): typos/wording tweaks

---

docs/advanced/Middleware.md

https://developer.mozilla.org/en-US/docs/Web/API/Console/groupEnd

console.groupEnd doesn't take parameters

---

docs/recipes/ReducingBoilerplate.md

Well, I am not sure from where should we get isFetching as no structure provided here.

Shouldn't we pass isFetching from redux?

---

docs/introduction/LearningResources.md

* Fixes an uppercase typo
* Fills the closing quotation mark and adds semantic emphasis.

docs(redux): fixes typos

---

examples/todos-flow/package-lock.json
examples/todos-flow/package.json
examples/todos-flow/src/components/__snapshots__/App.spec.js.snap
examples/todos-flow/src/components/__snapshots__/Footer.spec.js.snap
examples/todos-flow/src/components/__snapshots__/Link.spec.js.snap
examples/todos-flow/src/components/__snapshots__/Todo.spec.js.snap
examples/todos-flow/src/components/__snapshots__/TodoList.spec.js.snap
examples/todos-flow/src/containers/__snapshots__/AddTodo.spec.js.snap
examples/todos-flow/src/containers/__snapshots__/FilterLink.spec.js.snap
examples/todos-flow/src/containers/__snapshots__/VisibleTodoList.spec.js.snap

Fix #2717 
It appears updating all dependencies to the most recent fixed the problem.

Fix todos-flow example

---

test/compose.spec.js
test/createStore.spec.js

Fix formatting and thus stop builds from failing

Fix Prettier complaints (wrap too long lines) in some specs

---

docs/introduction/PriorArt.md

Clean up some of the Flux section of PriorArt

---

docs/api/Store.md

Store Methods summary links were broken.

Update store.md summary documentation

---

docs/introduction/Ecosystem.md

update table of contents.  Missing a link

Update docs: introduction/Ecosystem.md

---

docs/api/applyMiddleware.md

docs(api): update applyMiddleware

---

docs/basics/Reducers.md

Disambiguation of antecedents for several instances of the pronoun "it".

Ambiguous antecedents for the indefinite pronoun "it".

---

website/siteConfig.js
website/static/css/custom.css

This PR addresses [#3283](https://github.com/reduxjs/redux/issues/3283)

Docs rebuild - improve accessibility of inline links and blockquote links

---

website/static/css/custom.css

Continues work on [#3283](https://github.com/reduxjs/redux/issues/3283)

Docs rebuild - improves accessibility of topNav links and hash links

---

src/createStore.js

Add a docstring explaining ensureCanMutateNextListeners

---

examples/todos-flow/src/containers/AddTodo.js

Remove unused `input` property.

Cleanup todos-flow container

---

README.md

From the discussion on https://github.com/reduxjs/redux/pull/3389

Referenced redux.mjs file in README

---

docs/recipes/UsingImmutableJS.md

Hi guys,
I've noticed some of the links broken on this page.
Thanks

fix broken links on Using Immutable.JS docs

---

docs/recipes/ConfiguringYourStore.md

Check `process.env.NODE_ENV` instead of `process.env`

fix the check for dev mode

---

docs/recipes/structuring-reducers/UpdatingNormalizedData.md

Also explain options using comments
See https://github.com/reduxjs/redux/pull/3400#pullrequestreview-229254034

Fix Redux-ORM related model name

---

src/createStore.js

Revert "Add bracket for comments"

---

docs/basics/UsageWithReact.md

I fixed fragment identifier in docs.

docs: Fix fragment identifier

---

src/createStore.js

Issue reference: https://github.com/reduxjs/redux/issues/3474

Clear current listeners on store unsubscribe.

---

README.md

made license text point to the respective file

Docs: update license section

---

test/utils/isPlainObject.spec.ts

convert utils/isPlainObject test to typescript

---

package-lock.json
package.json
rollup.config.js

Fixes https://github.com/reduxjs/redux/pull/3519#discussion_r315841722 with an upstream patch instead of custom config

Use new default cache root

---

test/applyMiddleware.spec.ts

remove unused type

---

src/types/reducers.ts
src/types/store.ts

Extract reducer types from index.d.ts

---

src/types/middleware.ts
src/types/reducers.ts
src/types/store.ts

also extract `Dispatch` into `store.ts` where it belongs

extract middleware types from index.d.ts

---

src/applyMiddleware.ts
src/bindActionCreators.ts
src/combineReducers.ts
src/createStore.ts
src/index.ts

This updates imports to use the newly moved action types

use the new action types

---

src/index.ts

This is the last code change PR prior to moving to auto-generation of index.d.ts

import types from src/types

---

docs/faq/Performance.md

Been reading a lot. Awesome docs!

Fixed broken link

---

docs/recipes/UsageWithTypescript.md

Updates an existing page.
- Nope, just figured I'd do it
- **Page**: Usage with TypeScript
- Rewrote the "React-Redux" section to copy the examples from the new React-Redux "Static Typing" docs page
- Added a "Redux Toolkit" section
- Added a "Resources" section
- Rewrote the "notes" section and moved it up to the top
No changes to assumptions

Rework "Usage with TS" page with more details

---

docs/style-guide/style-guide.md

grammatical error

---

package-lock.json
package.json

fix: index.ts error: Cannot find name 'process'

fix: index.ts error: Cannot find name 'process'

---

docs/introduction/GettingStarted.md

---
---
- Introduction:
- Getting started:
with a link
URL fix :)

Fix "api/createslice" RTK link

---

test/typescript/enhancers.ts

I was looking through tests to see how this thing can be typed correctly and found only this implementation-less test which was already a little bit helpful for me, but with the actual implementation would be even more... so I've added one for future explorers 😉

Add actual example implementation for StoreEnhancer to TS extraMethods test

---

website/docusaurus.config.js

Related with https://github.com/reduxjs/redux/pull/3635

Add Netlify badge

---

README.md

---
---
N/A
/README.md
Broken URLs to the Core Concepts and Three Principles pages on redux.js.org
Correct URLs

README: update URLS for redux.js.org

---

website/docs/recipes/ServerRendering.md

Fix broken link in code snippet

---

src/types/middleware.ts

---
name: "\U0001F41B Bug fix or new feature"
---
Fixes a bug
Improves type safety
`any` disables type safety
Type safety
Uses the correct types

Improve `Middleware` type

---

docs/advanced/UsageWithReactRouter.md

---
---
Update "Usage with React Router" page
- address #3694
- **Section**: https://redux.js.org/advanced/usage-with-react-router#next-steps
- **Page**: https://redux.js.org/advanced/usage-with-react-router

Remove "Note About Other Routing Libraries"

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/usage.md

[ISSUE_TEMPLATE] Replace new issue button with community link

---

examples/async/package-lock.json
examples/async/package.json

newer packages are required for the async example to run

---

docs/introduction/GettingStarted.md

---
---
Update an existing page
- **Page**: Getting Started with Redux
Link to the `cra-template-redux` package with a short description and usage information
This section assumes the user is making a new app with React and Create React App, though the other sections are still usable for other use cases

Add "Create a React Redux App" to getting started

---

docs/introduction/Installation.md

---
---
Update an existing page
- **Page**: Installation
See #3726

Add "Create a React Redux App" to installation

---

docs/introduction/GettingStarted.md
docs/introduction/Installation.md

---
---
Update existing pages
- **Page**: Getting Started and Installation
Remove the cd/start commands
They're already recommended by the create-react-app command
No, but the current example does assume the user is using npm, so this improves upon it

Remove the cd/start commands

---

docs/faq/Performance.md

---
---
update an existing page
- **Section**: FAQ
- **Page**: Performance
Specify the file type for the sample code.
This is purely a display change.

docs: enable syntax highlight

---

README.md

Updated documentation URLs for tutorials to latest on redux.js.org

Updated README.md with new documentation links

---

src/createStore.ts

---
---
- _https://github.com/reduxjs/redux/issues/3725_
Yes
- **Section**: NA
- **Page**: NA
A broken link is being displayed in the error message.
The PR changes the broken link to the correct one.

Updated createStore.ts

---

docs/recipes/ReducingBoilerplate.md

---
name: Updated Documentation Content
about: Fixed note format
---
**this PR updates an _existing_ page**
- **Section**: recipes
- **Page**: Reducing Boilerplate
Added missing `<` character

docs(recipes/ReducingBoilerplate): fix note format

---

docs/recipes/structuring-reducers/ReusingReducerLogic.md

Hi @markerikson, I saw that this issue #2520 has been around for a while and I thought I would help update the docs to include this example. Please tell me what you think. I used the example you provided in the issue, but fixed some stuff like adding action.name instead of just name and a closing paren.

2520 collection item reducer

---

docs/tutorials/essentials/part-5-async-logic.md

---
---
- **Section**: Redux Essentials - Part 5 Async Logic
- **Page**: Tutorial
Full stop and space are missing after the sentence ends.
Adds the missing full stop and space to the end of the sentence.

Add missing full stop

---

docs/tutorials/essentials/part-1-overview-concepts.md

added commas between object properties

---

docs/tutorials/essentials/part-4-using-data.md

---
---
I ran `npm run format:check`. Hope that is the right one to run.
- **Section**: Adding Authors for Posts
- **Page**: Redux Essentials, Part 4: Using Redux Data
- **code listing**: features/posts/AddPostForm
Highlight missing form new code added for `onAuthorChanged` event.
Added highlighting.

Missing highlight on new `onAuthorChanged`

---

docs/tutorials/essentials/part-4-using-data.md

---
---
- https://github.com/reduxjs/redux/issues/3845
- **Section**: Sorting the Posts List
- **Page**: part-4-using-data.md
See referenced issue
Add to documentation

Date field added to initialState with use of sub from date-fns.

---

docs/tutorials/essentials/part-4-using-data.md

---
---
- 
Yes
- **Section**: Adding Authors for Posts
- **Page**: part-4-using-data#more-post-features.md
Missing highlight for added code
Add highlight

add missing code highlight

---

docs/tutorials/essentials/part-3-data-flow.md

---
about: Amend tutorial code snippet to make it more explicit
---
Update an existing page.
- Resolves #3849
- **Section**: #saving-post-entries
- **Page**: tutorials/essentials/part-3-data-flow
Include default export in `postsSlice.js` snippet.
N/A

Update Redux Essentials Data Flow snippet (#3849)

---

docs/tutorials/essentials/part-5-async-logic.md

---
---
- _link issue here_ #3856
- Redux Essentials
- Part 5: Loading Posts
Where the file name should be "SinglePostPage", it is marked "EditPostForm".
fixed the wrong file name

fixed the wrong file name in the tutorial part5

---

docs/faq/OrganizingState.md

---
---
- Redux FAQ: Organizing State
- https://redux.js.org/faq/organizing-state
Reference to a deprecated package
https://github.com/tonyhb/redux-ui/issues/84#issuecomment-465303249
Removes reference

Remove reference to a deprecated package

---

docs/recipes/UsingImmutableJS.md
website/docusaurus.config.js
website/package-lock.json
website/package.json

Updated DS to `alpha.64`, and modified the Twitter card setting to "summary" to try to shrink the size of the Redux logo in previews on Twitter and Discord.
Comparison:

Update Docusaurus metadata

---

docs/introduction/LearningResources.md

Hi. as I mentioned in issue #3892, I have added the Korean redux documentation link to your docs.
I hope you accept this PR.
If you don't want to accept this, please let me know the reason and I will appreciate any feedback.  
Thanks !!

added a link to korean redux docs

---

CONTRIBUTING.md
website/README.md

- Also update commands in Readme of website
Change from using `yarn` to `npm`
Fix #3901

Update link for docs in Contributing.md

---

README.md

---
---
- **Section**: Main readme
- **Page**: README.md
There were a few issues with grammar and used words.
Making the readme more readable.

Main Readme file improvements

---

src/index.ts

---
name: :bug: fix: link to the page of webpack's 'mode' configuration
about: Fixing link to the page of webpack's 'mode' configuration
---
This fixes a small _bug_.
`https://webpack.js.org/concepts/mode/` was replaced with `https://webpack.js.org/configuration/mode/` by https://github.com/webpack/webpack.js.org/pull/2905.
The below is printed when NODE_ENV isn't 'production' to minify code.
It includes the old URL: https://webpack.js.org/concepts/mode.
```
You are currently using minified code outside of NODE_ENV === "production". This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or setting mode to production in webpack (https://webpack.js.org/concepts/mode/) to …
```

fix: link to the page of webpack's 'mode' configuration

---

website/docusaurus.config.js

feat: remove duplicate link

---

src/combineReducers.ts

---
name: Arrange import section of combineReducers and remove useless repeated import
about: arrange import section
---
- refactoring
- It makes codes more clean!

feat: arrange import section of combineReducers

---

docs/tutorials/essentials/part-5-async-logic.md

---
about: Simple grammatical error fix
---
- **Page**: Async Logic and Data Fetching
A sentence is missing the word "of".
Adds the word "of".

Fix grammar in docs

---

docs/introduction/Ecosystem.md

Easy Navigation and easy reading for others
(Fix broken URL in Ecosystem.md)

docs: Fix broken url  in docs

---

docs/introduction/GettingStarted.md

---
---
- **Section**:
- **Page**:

docs[GettingStarted]: fix variable typo

---

docs/tutorials/essentials/part-1-overview-concepts.md

---
---
- **Page**: Redux Overview and Concepts
_there's_ used with a plural
Changed _there's_ to _there are_ where applicable.

Fix some grammar

---

docs/tutorials/fundamentals/part-8-modern-redux.md

Thanks to Dev__#3824 in Discord for reporting this.

[docs] fix a typo in an import

---

docs/style-guide/style-guide.md

- **Page**: Style Guide: Best Practices
I was struggling to understand the logic in this part of the docs. Why are we setting the id to what it already is here instead of toggling the todo's `completed` state like elsewhere in the docs?
Update the example so that it's `completed` flag is toggled.

Toggle todo in doc

---

docs/tutorials/essentials/part-5-async-logic.md

---
---
- **Section**: Loading Users
- **Page**: Redux Essentials, Part 5: Async Logic and Data Fetching
Incorrectly mentioned the word `User` instead of `author` that is actually used.
Changed `User` to `author`

Fix a word to an actually used one

---

docs/tutorials/fundamentals/part-8-modern-redux.md

Closes #3951 
---
---
- [x ] Is there an existing issue for this PR?
- #3951 
- **Section**: Fundamentals part 8

Fix action exports from slice in in fundamentals part 8

---

docs/tutorials/fundamentals/part-4-store.md

---
---
- **Section**:
- **Page**:

remove duplication of "the"

---

docs/introduction/LearningResources.md

[Docs]: Update mapbox link in Learning Resources

---

docs/introduction/Examples.md
docs/tutorials/essentials/part-2-app-structure.md
docs/tutorials/essentials/part-3-data-flow.md
docs/tutorials/essentials/part-4-using-data.md
docs/tutorials/essentials/part-5-async-logic.md
docs/tutorials/essentials/part-6-performance-normalization.md
docs/tutorials/fundamentals/part-1-overview.md
docs/tutorials/fundamentals/part-3-state-actions-reducers.md
docs/tutorials/fundamentals/part-4-store.md
docs/tutorials/fundamentals/part-5-ui-and-react.md
docs/tutorials/fundamentals/part-6-async-logic.md
docs/tutorials/fundamentals/part-7-standard-patterns.md
docs/tutorials/fundamentals/part-8-modern-redux.md

---
---
Stems from an issue over on RTK - https://github.com/reduxjs/redux-toolkit/issues/877. This is an easy way to keep the CSB embed functionality in place while not freezing up some user's devices.

[Docs]: Add runonclick=1 param to CSB embeds

---

docs/tutorials/fundamentals/part-7-standard-patterns.md

---
---
- **Section**:
- **Page**:

fix: typo file name

---

docs/FAQ.md
docs/faq/CodeStructure.md
docs/faq/General.md
docs/style-guide/style-guide.md
docs/tutorials/essentials/part-2-app-structure.md
docs/tutorials/fundamentals/part-3-state-actions-reducers.md
docs/tutorials/fundamentals/part-8-modern-redux.md
website/package-lock.json
website/package.json
website/src/css/custom.css

This PR:
- Adds a new "How do I use the store in non-component files?" entry in the "Code Structure" FAQ page
- Cleans up and reuses the same example folder structure in both the Style Guide and FAQ
- Rewords the Style Guide folder structure entry to emphasize "single file logic", and mention both "slice" files and "ducks"
- Rephrases the "When should I learn/use Redux?" entries and adds links
- Updates Docusaurus to alpha.70

Assorted FAQ updates, 2021-02

---

docs/style-guide/style-guide.md
website/src/pages/index.js

This PR:
- Adds a style guide entry on naming selectors
- Removes the page banner

Add selector naming entry and remove banner

---

docs/tutorials/fundamentals/part-4-store.md

- Updated docs > part-4-store.md > #Dispatching Actions sample code
- Refactored `changeType` to `added`, a valid property
---
---
- **Section**:
- **Page**:

Closes Issue #4037

---

docs/recipes/UsageWithTypescript.md

---
---
This PR:
- Tweaks some of the descriptions and examples in the "Usage with TS" page based on late feedback in PR #4042

Tweak TS Usage examples based on PR feedback

---

README.md

---
---
no 
no
- **Section**: current section
- **Page**: current page
link update
update link

getting started link update

---

docs/tutorials/fundamentals/part-8-modern-redux.md

---
---
- **Section**: Converting the Todos Reducer
- **Page**: Modern Redux with Redux Toolkit
Some unused imports leftover
Removed those imports

Docs: Removed some useless imports

---

docs/tutorials/fundamentals/part-4-store.md

---
---
- **Section**: tutorials/fundamentals
- **Page**: /part-4-store#redux-devtools

Fix broken protocol in link to Firefox DevTools addon

---

docs/tutorials/fundamentals/part-4-store.md

---
---
- Too minor
- **Section**: redux/docs/tutorials/fundamentals
- **Page**: part-4-store.md
Extra word in the sentence, doesn't make sense.
Removed word.

[Docs] Removed typo

---

netlify.toml
package-lock.json
package.json
website/package-lock.json
website/package.json

Use an unreleased version of Docusaurus to test the webpack5 support works for this site.
See also https://github.com/facebook/docusaurus/pull/4089

chore: Docusaurus with webpack 5

---

docs/introduction/GettingStarted.md
docs/introduction/LearningResources.md
docs/tutorials/tutorials-index.md
website/package-lock.json
website/package.json

---
---
Updates some existing pages
- #4034 and #4096, partially
- **Page**: "Getting Started" and "Learning Resources"
- Updated Docusaurus to `beta.0`
- Added `react-lite-youtube-embed` lib
- Added an embed of the "Learn Modern Redux" episode into "Getting Started" and "Tutorials Index"
- Updated the "Learning Resources" page:
- Removed older tutorials that aren't how we want people using Redux today
- Moved Dan's Egghead videos into the "how it works" section and updated the course links
- Added some newer tutorial article links

Add "Learning Modern Redux" embeds and update Learning Resources

---

website/package-lock.json
website/package.json

This is just trying to bust the docusaurus cache to restore the floating section nav button
---
---
- **Section**:
- **Page**:

Bump to beta.3

---

docs/usage/deriving-data-selectors.md
docs/usage/redux-logic-thunks.md
docs/usage/writing-logic-thunks.mdx
website/sidebars.js

This PR:
- Adds a brand new usage guide page on Thunks

Add thunks usage guide

---

docs/tutorials/essentials/part-1-overview-concepts.md
docs/tutorials/essentials/part-2-app-structure.md
docs/tutorials/essentials/part-3-data-flow.md
docs/tutorials/essentials/part-4-using-data.md
docs/tutorials/essentials/part-5-async-logic.md
docs/tutorials/essentials/part-6-performance-normalization.md
docs/tutorials/fundamentals/part-6-async-logic.md
docs/usage/writing-logic-thunks.mdx

Added an example of using thunks for selection, and fiddled with page headers because I'm seeing doubled headers locally

Add thunk selection example

---

docs/understanding/thinking-in-redux/Glossary.md

---
---
- **Section**: understanding/thinking-in-redux
- **Page**: glossary
I think "a new enhanced store creator." is correct, not "a new, enhanced store creator.".
This removed ",".

Fix typo in Glossary.md

---

docs/introduction/Installation.md

Fixes a single grammatical error in the installation documentation.

fix(installation documentation): grammatical error

---

docs/tutorials/fundamentals/part-5-ui-and-react.md

---
---
- **Section**:
- Fundamentals Tutorial
- **Page**:
- part 5

Grammar fix

---

docs/tutorials/essentials/part-6-performance-normalization.md

---
---
- [] Is there an existing issue for this PR?
- **Section**: Tutorials - Redux Essentials
- **Page**: part-6 Performance and Normalizing Data
The server response doesn't include a `notifications` field
Change `response.notifications` to `response.data`

Fix code snippet in essentials tutorial part-6

---

docs/usage/UsageWithTypescript.md

The constant "store" should be exportable because this is what user is going to pass in the provider.

Update UsageWithTypescript.md ()

---

docs/tutorials/essentials/part-5-async-logic.md

I removed the redundant word
Fix typo:
that that -> that

Fix typo in part-5-async-logic.md

---

docs/tutorials/essentials/part-8-rtk-query-advanced.md

Fixed typographical mistake
Fixed typo:
when the click the -> when they click the

fix typo in part-8-rtk-query-advanced.md

---

docs/tutorials/fundamentals/part-5-ui-and-react.md

---
---
- Decided against it as such a small change.
- **Section**: Fundamentals Tutorial
- **Page**: 5
"dispatch actions to for changing the color" scans badly, I'm guessing it's a typo.
Remove the word "to".

Remove extra word from docs

---

docs/faq/CodeStructure.md

---
---
- **Section**:
- **Page**:

Removed link leading to 404 in faq

---

docs/tutorials/fundamentals/part-4-store.md

Issue-4276: update description of wrapDispatch - a nested function within middleware

---

docs/usage/WritingTests.md

Delete "a" to agree with plural "functions"
---
---
- **Section**:
- **Page**:

Correct typo

---

docs/faq/General.md

---
---
- **Section**: https://redux.js.org/faq/general#when-should-i-use-redux
- **Page**:
The word 'when' appears twice
Removes redundant 'when'

Update General.md: fix typo

---

website/src/css/custom.css

---
---
- #4299 
- **Page**: Style Guide
The Priority Tags (`Essential`, `Strongly Recommended`, `Recommended`) against each heading isn't aligned properly.
Add `position: relative` property to each tag in order to keep it in alignment with the Heading.

[#4299] Fix position of Priority Tags

---

docs/faq/CodeStructure.md

---
---
- **FAQ**:
- **CodeStructure**:

Add missing word to improve clarity

---

docs/tutorials/essentials/part-3-data-flow.md

---
---
- **Section**: /tutorials/essentials
- **Page**: part-3-data-flow
None.
No.

Added link to React Fragments documentation

---

src/types/store.ts

file: src/types/store.ts
line: 38
description: change word ‘distinquishable’ to 'distinguishable'

fix: spelling check

---

scripts/mangleErrors.js

---
name: :bug: Bug fix or new feature
---
It fixes a bug
- [_link issue here_](https://github.com/reduxjs/redux/issues/4341)
- [] Have the docs been updated to match the changes in the PR?
There is a tiny typo in mangleErrors.js file. 
`webpak` should be `webpack`.

fix webpack typo

---

docs/tutorials/essentials/part-4-using-data.md

Change == to === as suggested from eslint in Codesandbox

---

docs/tutorials/essentials/part-4-using-data.md

Add all reaction buttons initialization

---

docs/tutorials/essentials/part-5-async-logic.md

💪`because we have the store right there:`
😢but the store isn't right there
💪so I added the store right there

(docs) minor improve

---

docs/introduction/Ecosystem.md
docs/tutorials/typescript.md
docs/tutorials/videos.md
docs/understanding/thinking-in-redux/Glossary.md
docs/usage/Troubleshooting.md
docs/usage/UsageWithTypescript.md
docs/usage/WritingTests.md
docs/usage/structuring-reducers/ImmutableUpdatePatterns.md
website/package-lock.json
website/package.json

This PR:
- Bumps Docusaurus to the latest
- Rewrites the "Testing" page:
- Removed test config instructions and added links to Jest/Vitest docs
- Added links to RTL/MSW docs
- Converted examples to TS
- Added instructions on preloading state and dispatching actions
- Added selectors section
- Fixed busted page formatting in other pages
- Fixed a couple busted links
- Added some more links to the "Immutability" page

Rewrite "Testing" page to improve examples and setup instructions

---

docs/usage/UsageWithTypescript.md

---
---
Update existing page
- no issue
- **Section**: Use Typed Hooks in Components
- **Page**: Usage with Typescript
None besides the PR.
No

Add tip to detect wrong hook imports with eslint

---

docs/tutorials/fundamentals/part-8-modern-redux.md

Inside the "todosLoading" action creator, the status value is set to 'loading' but the initial state is an array, so I propose the following initialState:
```
const initialState = {
todoList: [],
status: null,
}
```
Type of PR:

Add status and todoList to initialState

---

docs/tutorials/fundamentals/part-5-ui-and-react.md

---
---
- **Page**: docs/tutorials/fundamentals/part-5-ui-and-react.md

DOC: fix tiny typo

---

docs/tutorials/fundamentals/part-3-state-actions-reducers.md

---
---
- No
- Yeah
- **Section**: Redux Fundamentals, Part 3: State, Actions, and Reducers
- **Page**: Designing Actions
Miss a single quote in the code.
Add a single quote.

docs: Missing a single quote

---

docs/introduction/GettingStarted.md
docs/introduction/LearningResources.md
docs/tutorials/tutorials-index.md
docs/tutorials/videos.md

---
---
- **Section**:
- **Page**:
Typescript -> TypeScript
Typescript -> TypeScript

Docs: Fix spellings error

---

docs/tutorials/fundamentals/part-5-ui-and-react.md

---
---
- #4409
- **Section**: Redux Fundamentals
- **Page**: UI and React
Just a couple minor wording issues.
It corrects the erroneous wording.

Fix minor wording issues in docs

---

.github/workflows/size.yaml
.github/workflows/test.yaml

No.
Actions used in GitHub Actions should be updated to the latest version and not use any beta versions. Dependabot could be used to automate this.

Update all GitHub actions

---

docs/tutorials/essentials/part-2-app-structure.md

grammar check for part-2-app-structure.md

---

docs/FAQ.md
docs/faq/OrganizingState.md
docs/style-guide/style-guide.md

---
---
- A change made to the section header in https://github.com/reduxjs/redux/pull/4434 was not updated in other locations in the docs
- Updates the links to the new header

Fix outdated link to "Do I have to put all my state into Redux?"

---

docs/faq/General.md

---
---
- **Section**: When should I learn Redux?
- **Page**: Redux FAQ: General
- Link points to a deleted tweet
- Removes the link

Remove link to deleted tweet

---

.github/workflows/size.yaml
src/index.js

Fixes https://github.com/reduxjs/redux/issues/4443

Remove minified check

---

docs/tutorials/essentials/part-8-rtk-query-advanced.md

---
---
- **Page**: RTK Query Advanced Patterns
Simple misspelled word.
Removes a letter.

docs: fixes typo

---

docs/tutorials/essentials/part-1-overview-concepts.md

---
---
updates an existing page
- #4515 
- **Section**: Redux Terms and Concepts
- **Page**:  [here](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#redux-terms-and-concepts)
tutorial -> Redux essentials
since React's old docs have been deprecated and aren't recommended, we should update the link to new React docs.

update link to latest react docs

---

README.md

- ref: https://github.com/badges/shields/issues/8671
shields.io badge needs to be updated
(left(as-is), right(to-be))

Update workflow badge

---

docs/tutorials/essentials/part-1-overview-concepts.md

---
---
updates an existing page
- #4521 
- **Section**: Redux Essentials, Part 1: Redux Overview and Concepts
- **Page**: [this page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#how-to-read-this-tutorial)
update the links to the latest react docs

update JSX link to latest react docs

---

docs/tutorials/essentials/part-1-overview-concepts.md

---
---
updates an existing issue
- #4521 
- **Section**: Redux Essentials, Part 1: Redux Overview and Concepts
- **Page**: [this page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#how-to-read-this-tutorial)

update links to latest react docs

---

docs/tutorials/essentials/part-1-overview-concepts.md

---
---
updates an existing page
- #4525
- **Section**: Redux Essentials, Part 1: Redux Overview and Concepts
- **Page**: [this page](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#how-to-read-this-tutorial)
update the links to the latest react docs

add separate link for `props`

---

docs/tutorials/fundamentals/part-1-overview.md

---
---
- **Section**: Redux Fundamentals
- **Page**: [this](https://redux.js.org/tutorials/fundamentals/part-1-overview#introduction)
one link is broken and others are outdated which needs to be updated
added new links

fix: outdated and broken links

---

docs/tutorials/fundamentals/part-2-concepts-data-flow.md
docs/tutorials/fundamentals/part-3-state-actions-reducers.md
docs/tutorials/fundamentals/part-5-ui-and-react.md

---
---
- **Section**: Redux Fundamentals, Part 5: UI and React
- **Page**: [this](https://redux.js.org/tutorials/fundamentals/part-5-ui-react#reading-state-from-the-store-with-useselector)

fix: outdated links

---

docs/introduction/CoreConcepts.md

Added spaces on both sides of the dash

---

docs/usage/WritingTests.mdx

---
---
- No, but it's a very small change
- **Usage**:
- **Writing Tests**:
[MSW's website](https://mswjs.io/) calls it Mock Service Worker, here it's referred to as Mock Server Worker.
Fix typo.

Fix name of MSW

---

docs/introduction/why-rtk-is-redux-today.md

Just a quick fix for this serious issue :)

add comment to docs

---

docs/tutorials/essentials/part-7-rtk-query-basics.md
docs/tutorials/videos.md

@markerikson also here - can you take a look if this looks right for you?

add links to egghead RTK Query tutorial

---

docs/usage/nextjs.mdx

---
---
- **Section**: https://redux-toolkit.js.org/usage/nextjs#overall-recommendations
- **Page**: https://redux-toolkit.js.org/usage/nextjs
Typo in 'architecture'
Add missing letter

Fix nextjs.mdx typo

---

docs/usage/UsageWithTypescript.md

Change base Typescript example to include AppStore type

---

website/src/css/custom.css

adding better dark theme

---

package.json
yarn.lock

Bump TypeScript to 5.5

---

docs/tutorials/essentials/part-8-rtk-query-advanced.md

docs: remove extra word

---

docs/tutorials/essentials/part-1-overview-concepts.md

docs: remove semicolon

---

docs/tutorials/fundamentals/part-4-store.md

fix(part-4-store): misprint in text

---

docs/tutorials/essentials/part-6-performance-normalization.md

I fixed a minor mistake in the docs.

Fix a minor mistake in docs

---

.codesandbox/ci.json
.github/workflows/publish.yaml
.github/workflows/test.yaml

chore: update CI Node.js version to 22
