- src/Container.js
- src/Root.js
Wrapping context would prevent collision with 3rd party libraries.
> Reduce context footprint

- examples/counter/App.js
- examples/todo/App.js
- src/Root.js
- src/decorators/container.js
- src/decorators/root.js
- src/index.js
Bring back decorator APIs:
```js
import { container, root } from 'redux';
@root
class App {
render() {
return (
<Counter />
);
}
}
@container({
actions: { increment, decrement },
stores: counterStore
})
class Counter {
static propTypes = {
increment: PropTypes.func.isRequired,
decrement: PropTypes.func.isRequired,
counter: PropTypes.number.isRequired
};
render() {
const { increment, decrement, counter } = this.props;
return (
<p>
Clicked: {counter} times
{' '}
<button onClick={() => increment()}>+</button>
{' '}
<button onClick={() => decrement()}>-</button>
</p>
);
}
}
```
> Resurrect decorators

- README.md
- examples/counter/App.js
- examples/counter/stores/counterStore.js
- examples/todo/Body.js
- examples/todo/stores/index.js
- src/Container.js
- src/addons/container.js
This makes `stores` and `actions` symmetric and lets us specify custom
prop names easily.
`container` decorator now takes a second argument `transformProps`,
which is a function that is used to transform the state and actions
props before passing them to the component. It defaults to
`({ state, actions }) => ({ ...state, ...actions })`
I removed some nesting from the states of `counterStore` and `todoStore` examples, because it didn't seem necessary after this change and made prop passing simpler.
Fixes #22.
> Accept stores as an object of prop key to store

- README.md
- examples/counter/actions/CounterActions.js
- src/createDispatcher.js
@gaearon Is that what you meant? It looked too much easier to implement... O.O
> Allow to read state by store on action creator callback

- examples/actions/CounterActions.js
- examples/components/Counter.js
- src/Redux.js
- src/createDispatcher.js
- src/index.js
- src/middleware/thunk.js
- src/utils/composeMiddleware.js
This gives users the ability to pass global "action middleware" (terminology still in flux) to the default dispatcher.
```js
// Before
createRedux(stores, initialState);
// After
createRedux(stores, initialState, middleware);
```
Middleware is a function that wraps the `dispatch()` method, or another middleware. For example, to use a middleware:
```js
// Instead of this
dispatch(action)
// do this
middleware(dispatch)(action)
```
Multiple middleware can be composed manually
```js
middleware1(middleware2(dispatch))(action)
```
Or using the provided `compose()` utility:
```js
// All are equivalent:
middleware1(middleware2(dispatch))(action)
compose(middleware1, middleware2)(dispatch)(action)
compose(middleware1, middleware2, dispatch)(action)
```
The `compose()` middleware may seem trivial, …
> Add basic middleware api to default dispatcher

- src/components/Connector.js
Another attempt at https://github.com/gaearon/redux/pull/66.
This has the benefit of associating `this.props.select` with its use (`selectState`).
> Extract selectState and set initial state in constructor

- src/Redux.js
- src/createDispatcher.js
- test/createDispatcher.spec.js
Related: #68, #62
I want to make this change to make custom dispatchers more composable.
The store is still managed by the “main” dispatcher, but now wrappers (such as a time travelling wrapper) are able to intercept the state that dispatcher is attempting to set, and, perhaps, put information of their own there too.
With this change, the `setState` call bubbles from the innermost dispatcher up to the Redux instance, and goes back with the state that was actually set.
> Make setState return the state that was set

- src/components/createConnector.js
- test/components/Connector.spec.js
On Connector, verify if `select` prop, which is a function, returns an
object, and if not, throws an error.
Issue #78
> Throws an error when `select` not returns an object

- src/createDispatcher.js
- src/index.js
- src/utils/composeMiddleware.js
- test/composeMiddleware.spec.js
To be consistent with e.g.: `composeStores`.
Also exporting the default `thunk` middleware is useful if I need to create a dispatcher with other middlewares, for example:
```js
import { createDispatcher, composeStores, middlewares } = 'redux';
import loggerMiddleware from './middlewares/logger';
import * as stores from './stores';
const dispatcher = createDispatcher(
composeStores(stores),
getState => [middlewares.thunk(getState), loggerMiddleware(getState)]
);
```
Does it make sense?
> Export default middlewares and use consistent naming

- src/createDispatcher.js
- test/createRedux.spec.js
This fixes #90 and includes a failing (now fixed!) test from #91 (thanks @aaronjensen!)
The issue was due to the inner function overwriting the `middlewares` parameter of the outer function during its first invocation, so `getState` was injected only once.
> Fix stale state inside action creators on hot reload

- src/react-entry.js
- src/react-native-entry.js
The paths should be relative, else it will result in `module "lib/react" not found`.
> Use relative paths in entry files

- .jshintrc
- LICENSE
from #reflux channel 
>chico [3:12 AM] 
>what is `.jshintrc` for when you actually use `eslint`?
>gaearon [3:28 AM] 
>@chico: Probably leftover from some earlier project :simple_smile:
also update year in license
> remove .jshintrc and make license up to date

- src/components/createConnector.js
- test/components/Connector.spec.js
- test/components/Provider.spec.js
- test/components/connect.spec.js
- test/components/jsdomReact.js
- test/components/provide.spec.js
This fixes a bug that causes the state passed by `Connector` to stay stale when a new `select` function is passed. This PR includes a failing test and a fix that makes it pass.
> Connector#componentWillReceiveProps should use the new value of `select`

- src/components/createConnectDecorator.js
- src/components/createProvideDecorator.js
- test/components/connect.spec.js
- test/components/provide.spec.js
This PR exposes the decorated component as a static property when using `@connect(...)`. This is great for removing the dependency on a redux instance in tests.
Before:
```
@connect(state => state)
class DecorateMe {
}
React.TestUtils.renderIntoDocument((
<Provider redux={redux}>
{() => <DecorateMe />}
</Provider>
));
```
After:
```
@connect(state => state)
class DecorateMe {
}
React.TestUtils.renderIntoDocument(<DecorateMe.DecoratedComponent {...props} />);
```
> Expose DecoratedComponent as static property.

- src/createDispatcher.js
Supersedes #114.
I want to establish a convention for “built-in” and “devtools” action types (more will come in #113) so that the tools are able to distinguish them, and so the user doesn't feel compelled to handle them and can clearly see that they are not from their app.
Thanks to @ooflorent for the `@@` naming tip.
> Give the initial action a special type

- src/utils/bindActionCreators.js
- src/utils/composeStores.js
- src/utils/mapValues.js
- test/utils/mapValues.spec.js
From #112's discussion, this replaces lodash's `mapValues` to reduce the number of lodash dependencies.
> Replace lodash's mapValues

- package.json
- src/components/createConnector.js
- src/utils/composeStores.js
- src/utils/identity.js
- src/utils/isPlainObject.js
- src/utils/pick.js
- test/utils/identity.spec.js
- test/utils/isPlainObject.spec.js
- test/utils/pick.spec.js
From #112 -- Removing lodash utils decreases the build size significantly as described by @dariocravero so this PR replaces the remaining three lodash modules with basic utils.
> Replace lodash utils

- src/Redux.js
> Renamed argument to be more descriptive of its dual nature

- CHANGELOG.md
Before we go into `1.0`, here's a change log autogenerated from releases.
It doesn't make use of sections like _Added_, _Changed_ and _Fixed_ as we should but it's probably ok because it's imported. I think we should stick to those from now on. Thoughts?
> Added an auto-generated change log.

- src/components/createConnector.js
- test/components/Connector.spec.js
You shouldn't need to attach the Connector components to redux's setState call unless the component mounts which should only be on the browser side.  This will provide more flexibility in the way people decide to do server rendering because componentDidMount is not called on the server.
> subscribe moved from Connector constructor to componentDidMount

- README.md
Unfortunately, there's no good way to point to a specific channel on Slack so I use a link to Slack-in website instead. That's yet another reason why you should probably use Gitter instead.
I use React Blue color. Feel free to improve it.
> Add Slack-in Badge

- README.md
This splits the lines just as well, and wouldn't get destroyed when someone has automatic trimming of trailing whitespace enabled or just doesn't know the intention.
> Replace trailing whitespaces with a newline

- src/components/createConnector.js
- src/components/createProvider.js
- src/components/createReduxShape.js
Just a simple change which also allows us to reuse `reduxShape` outside of the framework :)
> Normalised `reduxShape` in `components`

- test/Store.spec.js
- test/helpers/reducers.js
While I was reading through the test cases in the #195 it caught me off guard that the IDs were being reused. This modifies the test case to not reuse IDs so you can follow the flow of where the reducer is swapped with where the next ID appears rather than only the task text string.
> Modify test case ID generation for reducer changing

- README.md
Redux was demoed together with **[React Hot Loader](https://github.com/gaearon/react-hot-loader)** at React Europe.
Watch **[Dan Abramov's talk on Hot Reloading with Time Travel](https://www.youtube.com/watch?v=xsSnOQynTHs)**.
> Add a link to Hot Reloading with Time Travel talk

- src/utils/composeReducers.js
- test/composeReducers.spec.js
Accidentally created against alpha before. Sorry about that.
Updated composeReducers to throw error when reducer returns undefined. Update to #193. #191
> Throw error on undefined value from reducer function

- test/components/connect.spec.js
Added an additional test to connect decorator to check for shallowEqualScalar logic and make sure props are passed through the connect decorator.
> Added test for shallowEqualScalar in connect decorator

- src/utils/applyMiddleware.js
- test/applyMiddleware.spec.js
dispatch method passed to middleware was skipping middleware for subsequent.
> Dispatch sends action through entire middleware chain

- package.json
- scripts/test-cov
Coverage report runs as usual:
New shiny ES6-compatible report:
> ES6 coverage

- examples/counter/containers/App.js
- src/utils/applyMiddleware.js
- test/applyMiddleware.spec.js
- test/helpers/middleware.js
We're moving it into a separate project because:
* It's strange to export it as a top level export here.
* Asking people to reach into the internals is not an option either.
* Having it as a default middleware when you *still* have to call `applyMiddleware` manually doesn't make much sense.
> Remove thunk middleware from the core

- src/Store.js
- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
This renames `@@INIT` to `@@redux/INIT` and adds random type probing to ensure you're not trying to handle `INIT` directly. This fixes #186.
> Handling private actions is an anti-pattern. Enforce it. (Fixes #186)

- docs/store.md
As per commit 650f002 Remove combineReducers shortcut in favor of an explicit call
> Update store.md to use combineReducers explicit call

- src/utils/applyMiddleware.js
- test/utils/applyMiddleware.spec.js
`compose(middleware(methods), store.dispatch)` was happening on each dispatch, this pr updates `applyMiddleware` to only compose the dispatch method once.
> Compose applyMiddleware dispatch once.

- src/createStore.js
- src/index.js
- src/utils/applyMiddleware.js
- src/utils/bindActionCreators.js
- src/utils/combineReducers.js
- src/utils/compose.js
- src/utils/composeMiddleware.js
- src/utils/isPlainObject.js
- src/utils/mapValues.js
- src/utils/pick.js
I decided in favor of *not* shipping Flow types in 1.0.
This commit just strips types from the current Flow-friendly codebase (initially worked on in #254).
We will not use features unsupported by Flow (such as `let` or `const`) from now on so it's easy to gradually add Flow types later.
The reason I'm removing them is **they're too naive** and I don't want them to be perceived as the public API (at least not yet). I am ready to add Flow when [cases like this](https://github.com/gaearon/redux/issues/290) are solved. Adding them now is confusing because, for #290 to work, different (more polymorphic) signatures are needed. For example, `Store` type should be parameterized by `<MyState, MyAction>` instead of `any` types in the current annotations.
> Remove Flow types for now

- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
Symbols are a good way to prevent naming collisions of action types.
However, if you attempt to use a symbol as an action type, `getErrorMessage` inside `combineReducers` will throw an error on line 13 because symbols can't be implicitly converted to a string. I can reproduce this in at least Chrome and Firefox.
Strangely enough, I could not reproduce this in the tests -- it looks like babel is implicitly converting the symbol to a string, contrary to the es6 spec as I understand it. I added a test anyway to verify the use case.
I understand Redux probably wasn't designed to be used with symbols as action types, but this seems like an easy way to add support for them.
I'm also open to other solutions or workarounds.
> Allow es6 symbols to be used as action types

- .eslintrc
- src/createStore.js
- src/index.js
- src/utils/applyMiddleware.js
- src/utils/bindActionCreators.js
- src/utils/combineReducers.js
- src/utils/compose.js
- src/utils/isPlainObject.js
- src/utils/mapValues.js
- src/utils/pick.js
This adds JSDoc annotations to the public API as discussed in #140 and #89.
Comments are welcome!
(This is written against the 1.0 API which is not officially released yet.)
> Add JSDoc annotations to the public API

- package.json
- src/utils/isPlainObject.js
- test/utils/isPlainObject.spec.js
When isPlainObject is called between two different contexts then Object.prototype is not the same. Now it is comparing only stringified constructors. Fixes #304
> fix isPlainObject

- src/utils/bindActionCreators.js
- test/utils/bindActionCreators.spec.js
With this change you can use `bindActionCreators` to either bind a object of actionCreator functions to dispatch or only a single actionCreator directly.
```js
import { bindActionCreators } from 'redux';
import { addTodo } from './actions/todoActions';
const boundAddTodo = bindActionCreators(addTodo, dispatch);
boundAddTodo('Hello');
```
> Allow `bindActionCreators` to be used with function as actionCreator

- .travis.yml
- examples/buildAll.js
- package.json
Doesn't run the tests yet, but can easily do so. If this looks good, Travis will need to run `npm build:examples`
> Add script to help travis build all examples

- package.json
- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
Ok, not super happy with this but it is a start.
* I have written tests for verifyStateShape, but I couldn't think of a neat way to test the code in createStore so there is currently a hole in the test coverage.
* I don't really like the function name verifyStateShape. Is stateShapeWarning better?
* I haven't used an external warning module. Would it be a good idea? I'm currently just calling console.warn.
Happy to take some direction on this.
> Warn if the initial state shape doesn't match the reducer names

- docs/recipes/ReducingBoilerplate.md
Just a small change, but going over this example, the data returned from the API call isnt being dispatched :)
> Dispatch data from the Call API Middleware example

- src/utils/bindActionCreators.js
- test/utils/bindActionCreators.spec.js
This adds invariant warning support to `bindActionCreators` as per issue #407.
> Bind warning

- package.json
As per title, [see here for more info on jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main).
> add jsnext:main in package.json for next gen bundling

- docs/recipes/ComputingDerivedData.md
In the composition section, change some of the selector names that were left over from an old example. I think this is more coherent.
> change weird selector name in Computing Derived Data doc

- examples/buildAll.js
Fixes #438 by adjusting the scope of opts.
> adjust scoping for opts to avoid error with spawnSync

- README.md
This boilerplate is still a work in progress but is currently functional. I'm actively working on it and am focused on keeping it up to date with the latest Redux and React Router API changes so people can get an idea of how to use both.
> Adds react-redux-starter-kit to examples

- docs/api/compose.md
applyMiddleware threw an error because the middleware array was not destructured.
I also removed an unused import.
> Fix compose function example

- examples/counter/containers/CounterApp.js
- examples/counter/package.json
Update `Counter` example to use the most recent version of [react-redux](https://github.com/gaearon/react-redux).
Separate `Counter` into "smart" and "dumb" components per [smart / dumb](https://github.com/gaearon/react-redux#dumb-component-is-unaware-of-redux)
> Update counter example to recent react-redux

- src/createStore.js
- test/createStore.spec.js
Unsubscribing during a dispatch would change the listeners array.
However that causes the next listener not to fire.
Fixes #461
> Fixes #461 - Copy listeners array, so subscribes can't affect the loop.

- examples/real-world/middleware/api.js
> Fix syntax error in Object.assign in real world example

- examples/real-world/middleware/api.js
This changes 'on' to 'one' in the string 'Specify on of the exported Schemas.'
> Real World Example - Fix typo in API middleware error string

- docs/advanced/Middleware.md
errorHandler was never created, but crashReporter was created but unused.
> Fix variable name in middleware docs example

- docs/advanced/AsyncActions.md
It is somehow hard to grasp what's going on at first sight, specially for someone not much familiar with ES6.
I tried to explain the combineReducers part and let the reader figure out the ES6 part :)
> Add note about combineReducers in AsyncActions documentation

- docs/basics/Reducers.md
The word explore was misspelled as "expore".
Fix the typo :smile:
This is indeed a one-character PR, but I'll add in any more typos if I find them. Loving the new docs btw. Congrats on 1.0.
> Docs typo: expore -> explore

- .travis.yml
- examples/testAll.js
- package.json
This allows building examples with **Node 12.x** in windows.  
Also separates into "test:examples", and "build:examples" scripts
This leaves just running the tests exclusive to **io.js** due to **jsdom 4** dependency.
> compatible run scripts for Win/NodeJS, and separate build/test examples

- docs/basics/Actions.md
I assume this isn't intentional, since the use of semicolons is otherwise consistent.
> Add missing semicolon to doc

- src/utils/combineReducers.js
`process` doesn't exist in react-native's JavaScriptCore environment, so we should do something like react-redux connect does now.
https://github.com/gaearon/react-redux/blob/master/src/components/createConnect.js#L192
> fix `process is not defined` in react-native

- package.json
- src/createStore.js
- src/utils/bindActionCreators.js
- src/utils/combineReducers.js
- test/utils/bindActionCreators.spec.js
They don't really help much, and I'm not sure whether they have the same problem as https://github.com/rackt/redux/issues/525, so I'll just remove them.
> Don't depend on invariant and warning

- docs/api/README.md
Not quite sure that this is correct but it do make more sense to me.
Changed `below` to `above` in `Every function described below is a top-level export. You can import any of them like this:`
> Changed below to above in docs/api/README.md

- docs/recipes/ReducingBoilerplate.md
The prop called `isLoading` but referred to as `isFetching` in the text. Also `isFetching` is used in other places in the docs and examples.
> isLoading → isFetching

- docs/introduction/ThreePrinciples.md
It looks like semicolons are not being avoided elsewhere, so I assume this was an accidental omission.
> Add semicolon for consistency

- examples/todomvc/index.js
There was slight typo in todomvc example. There is no package named 'babel', it should be 'babel-core'.
> Changing import 'babel' typo to import 'babel-core'

- docs/introduction/PriorArt.md
[Existing link 404s](http://elm-lang.org/guide/architecture), the file was [removed](https://github.com/elm-lang/elm-lang.org/commit/039fd9eba4f876453eec5ba032e51fbaf39c7c53). 
elm-lang.org directly links to the elm-architecture-tutorial repo now, so I switched the link over to that
> Fixes link to elm architecture tutorial

- docs/basics/Actions.md
Surely looks like useless, but I got confused about how many `stores` redux involves, that's why I suggest the change, to be clearer.
> Change store designation

- examples/counter/store/configureStore.js
`combineReducer` is never used.
> Remove unused import

- docs/api/combineReducers.md
Replaced the suggestion to use `import * as reducers` with the recommendation to use `reducers/index.js` and call `combineReducers` there. Updated the code examples accordingly.
As discussed here: https://github.com/rackt/redux/pull/473
> Don't recommend the use of `import * as reducers`.

- docs/introduction/Examples.md
- examples/async/package.json
- examples/async/webpack.config.js
- examples/counter/package.json
- examples/counter/webpack.config.js
- examples/real-world/package.json
- examples/real-world/webpack.config.js
- examples/todomvc/package.json
- examples/todomvc/webpack.config.js
People seem to use them as starting boilerplates, and copy examples outside the `examples` folder.
Previously, this would fail because we wanted to resolve `redux` to `src` folder for easier development.
This PR tweaks Webpack configs so they work both standalone and with Redux.
If either `src` or `node_modules` of parent project is missing, we don't attempt aliasing anymore.
> Fix examples to work standalone

- docs/recipes/WritingTests.md
Also improved test setup a bit using a babelhook file rather than a command line option, for more flexibility.
> Explain unit testing decorated components.

- docs/recipes/WritingTests.md
Updated `WritingTests.md` with a section on how to test middleware.
The function signature for middlware is a little confusing, so I think this could add a lot of value.
> Add section on unit testing middleware to docs

- examples/universal/webpack.config.js
Hot reloading was not working due to a config error as described here:
https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md#syntax-error-unexpected-token-
> Correct publicPath in webpack config

- examples/universal/client.js
- examples/universal/server.js
The example is using `createStore` in both the server and client script, instead of `store/configureStore.js` with the thunk middleware. Fixed this and now the async and conditional action works.
> Fix universal rendering example (configureStore vs. createStore)

- docs/introduction/Examples.md
- examples/universal/webpack.config.js
This is to match the changes in #626, which happened before the universal example was merged, but after I had finished coding it.
Also, it adds the example to the Examples doc.
> Add universal to examples and update webpack config

- examples/universal/webpack.server.js
Removed use of ES6 string interpolation
> Don't depend on --harmony flag when running 'npm run client'

- examples/async/package.json
- examples/async/webpack.config.js
- examples/counter/package.json
- examples/counter/webpack.config.js
- examples/real-world/package.json
- examples/real-world/webpack.config.js
- examples/todomvc/package.json
- examples/todomvc/webpack.config.js
- examples/universal/package.json
- examples/universal/webpack.config.js
With React Hot Loader 1.3.0 release, we don't recommend `NoErrorsPlugin` anymore.
The problems it was supposed to fix were actually problems in RHL itself, and are fixed in 1.3.0 with https://github.com/gaearon/react-hot-loader/pull/187.
> Remove NoErrorsPlugin

- examples/real-world/package.json
Previously the real world example was not working due to a difference in
the file structure in react-router 1.0.0-beta4
The following error was being raised:
> Module not found: Error: Cannot resolve module
> 'react-router/lib/BrowserHistory' in /tmp/redux/examples/real-world
The version has been locked to react-router 1.0.0-beta3 to ensure the
example still runs. When the documentation has been updated for
react-router it would be ideal to update this to use the latest version
so the demo is up to date.
> fix(real-world-example): lock react-router version

- docs/recipes/WritingTests.md
Fixed a syntactical error in one of the first examples of [WritingTests.md](https://github.com/rackt/redux/blob/master/docs/recipes/WritingTests.md).
> Fixed example in WritingTests.md.

- docs/Glossary.md
- docs/api/README.md
- docs/api/Store.md
- src/createStore.js
- test/createStore.spec.js
It was only needed because React Redux used it to magically allow reducer hot reloading.
This magic used to cause problems (https://github.com/rackt/redux/issues/301, https://github.com/rackt/redux/issues/340), so we made the usage of `replaceReducer()` for hot reloading explicit (https://github.com/rackt/redux/pull/667). Now that it is explicit, there is no need for `getReducer()` so it can safely be removed from the public API.
This is a breaking change, so it goes into `wip-2.0` branch.
> Remove getReducer() from Store API

- docs/api/compose.md
- src/utils/applyMiddleware.js
- src/utils/compose.js
- test/utils/compose.spec.js
This fixes the [embarrassing mishap that `compose()` API was](https://github.com/rackt/redux/issues/632).
As suggested by @jlongster, now it is a proper `compose()` you'd find in Lodash or Underscore:
```js
it('composes from right to left', () => {
const double = x => x * 2;
const square = x => x * x;
expect(compose(square)(5)).toBe(25);
expect(compose(square, double)(5)).toBe(100);
expect(compose(double, square, double)(5)).toBe(200);
});
```
In terms of usage, if your code looked like this:
```js
const finalCreateStore = compose(
applyMiddleware(stuff),
devTools(),
somethingElse(),
createStore
);
```
It will now look like this:
```js
const finalCreateStore = compose(
applyMiddleware(stuff),
devTools(),
somethingElse()
)(createStore);
```
This is a breaking change, and thus goes on …
> Fix compose() to have a less surprising API

- src/utils/combineReducers.js
Since React Native 0.10 is out and polyfills `process.env.NODE_ENV`, we can now safely rely on it being there. If you're not ready to use RN 0.10, or are in a different environment, either use a browser build, or shim it yourself.
> Rely on process.env.NODE_ENV being polyfilled

- docs/advanced/ExampleRedditAPI.md
Three changes:
1. Removed ```combineReducers``` from ```import``` statement under configureStore.js (combineReducers is not used there).
2. The file names as listed on this page seem to imply that reducers.js and actions.js are in the same directory, so I changed the relative path of the import statement in reducers.js to match this. (from ```"../actions"``` to ```"./actions"```).
3. Same issue as number 2 above: configureStore.js and reducers.js seem to be in the same directory, so I changed the relative path of the import statement in configureStore.js to match this (from ```"../reducers"``` to ```"./reducers"```).
> Docs: Minor tweaks to advanced/ExampleRedditAPI.md

- docs/basics/UsageWithReact.md
1. Easier to read: less wrapping of lines with 2 columns and 4 rows
2. Easier to read: heading column aligned at the right, component columns aligned at the left
3. Easier to understand: smart versus dumb components as columns are "dependent variables" in analogy with the x-axis of a graph, or like month columns in a spreadsheet; characteristics as rows are like line items in a spreadsheet.
4. Easier to modify: you probably won't add another type of component, but you might add another contrasting characteristic (for example, from the bulleted lists in https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0). Adding another row to the inverted table would be easy, adding another column to the original table would be harder to do and harder to read.
> Invert rows and columns in table of components

- docs/introduction/Examples.md
Bullets shouldn't end in any punctuation when they're not a complete sentence. If they are a complete sentence, they should end in a period. More info: https://www.google.com/search?client=safari&rls=en&q=bulleted+list+punctuation&ie=UTF-8&oe=UTF-8
> Removed unnecessary punctuation

- README.md
**Problem this solves**
+ I want to be able to read the docs on the train / when offline.
**How**
+ link to a repository with instructions on how to create offline docs and example exports (will not always be up-to-date).
**Why this way**
+ don't want to bloat this repo with PDF, mobi, ePub builds. We could add the build instructions in Redux's README.
**Ideas for an even better solution**
+ integrate links to up-to-date PDF, ePub & MOBI files into https://rackt.github.io/redux - didn't hear back from @gitbookIO how that's possible / whether it's in the works.
Mockup:
+ add cache manifest to gitbook - didn't hear back from @gitbookIO or @samypesse about why this doesn't seem to be present anymore!? [https://github.com/GitbookIO/gitbook/pull/171](https://github.com/GitbookIO/gitbook/pull/17 …
> README: added link for offline docs & instructions.

- book.json
RE: #345 
to install the plugin you need to run:
`gitbook install`
it runs whatever is in `book.json`, so now the Gitbook version can also be specified in there
> add edit link to the gitbook docs

- docs/advanced/Middleware.md
Should be "the moment it reaches the reducer" instead of "the moment it
reaches the store". This matches the description of middlewares in the
Async Actions section.
fixes https://github.com/rackt/redux/issues/682
> Docs: Fix description of middleware

- examples/todomvc/components/Header.js
- package.json
- test/utils/isPlainObject.spec.js
Since contextify is not working on newer node versions, this removes it in favor of the native `vm` module. 
This will resolve errors with #698.
> Switch out contextify for vm

- docs/advanced/AsyncActions.md
Just a simple diff to the docs where I removed a semi-colon that causes a syntax error when running the code.
> Remove semi-colon from sample code

- examples/counter/test/containers/App.spec.js
> fix typo in counter container test

- docs/recipes/WritingTests.md
Use `createFakeStore` instead of `fakeStore`, because it's a function.
> docs: rename fakeStore to createFakeStore

- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
> Always call verifyStateShape for combined reducers

- examples/real-world/createDevToolsWindow.js
Fix warning about rendering components directly into document.body which comes with React 0.14 (ReactDom respectively).
Instead, render into DIV created on the fly.
> Don't render directly to document.body

- docs/api/applyMiddleware.md
Moved logging example to the top.
Logging is the canonical example of a cross-cutting concern. It is
(or should always be) the first example of implementing a cross
cutting concern, followed by more exotic things like async thunks.
> Docs: `applyMiddleware` API

- docs/recipes/ServerRendering.md
The href in the [rendered page](http://rackt.github.io/redux/docs/recipes/ServerRendering.html) currently leads to a 404.
> Fix link to Usage with React page

- docs/basics/Reducers.md
The first time I use Redux, I did some silly things like this:
```js
case ADD_TODO:
return Object.assign({}, state, {
todos: [...state.todos, {
id: uuid.v4(), // ｉｍｐｕｒｅ！！！　๐·°(৹˃̵﹏˂̵৹)°·๐
text: action.text,
completed: false
}]
});
```
Here, `uuid.v4()` is not pure. This causes the state to be unpredictable. I had to come back and move this impure code to the action creator later. So I hope this docs change can prevent future mistakes like this.
> Doc: Don’t call non-pure functions in a reducer

- docs/recipes/WritingTests.md
Fix comment line 300: "curly brances" => "curly braces"
> Fix typo (docs/recipes/WritingTests)

- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
Creates and logs sanity check error during `combineReducers`, but only throws on first invocation. Addresses #717.
> move combine reducers sanity check #717

- docs/recipes/MigratingToRedux.md
Feel free to close the PR if you disagree, although since it suggests to check the `createStore` implementation, I think it makes more sense to link to it, rather than to the API docs.
> Migrating docs: point to `createStore()` source file

- docs/basics/UsageWithReact.md
In line 156-158 :
```js
<Todo {...todo}
key={index}
onClick={() => this.props.onTodoClick(index)} />
```
There is index of todo.
But in the line 239-249:
```js
<TodoList
todos={[{
text: 'Use Redux',
completed: true
}, {
text: 'Learn to connect it to React',
completed: false
}]}
onTodoClick={todo=>
console.log('todo clicked', todo)
} />
```
There become just the `todo`,
I think change it to `todoIndex` would be clearer and less ambiguous than just `todo`.
> change todo to todoIndex in the example codes: App.js 

- examples/async/.babelrc
- examples/counter/.babelrc
- examples/real-world/.babelrc
- examples/todomvc/.babelrc
- examples/todos-with-undo/.babelrc
- examples/universal/webpack.config.js
When using v1.1.0 of the babel-plugin-react-transform, it throws warnings that the format for transforms is outdated and needs to be updated.
N/A
Update the babel-plugin-react-transform config format to the new, non-deprecated format from upstream. (v1.1.0+)
> Update babel config for new transform format

- examples/async/package.json
- examples/counter/package.json
- examples/real-world/package.json
- examples/todomvc/package.json
- examples/todos-with-undo/package.json
- examples/universal/package.json
Update babel-plugin-react-transform in package.json
to ^1.1.0 to support new format in babel config
See: https://github.com/gaearon/babel-plugin-react-transform/releases/tag/v1.1.0
> Update babel-plugin-react-transform to 1.1.0

- docs/api/applyMiddleware.md
Line 235: "poweful" => "powerful"
> Fix typo (docs/api/applyMiddleware)

- examples/async/package.json
- examples/async/store/configureStore.js
- examples/real-world/package.json
- examples/real-world/store/configureStore.js
Upgrades redux-logger from 0.0.x to 2.0.2 in async and real-world examples.
`redux-logger` now exports a function and not directly a middleware.
> Upgrade redux-logger to 2.0.2 in examples

- src/utils/combineReducers.js
- test/utils/combineReducers.spec.js
> Have combineReducers return same object if nothing changes

- docs/recipes/WritingTests.md
- examples/counter/test/actions/counter.spec.js
- examples/real-world/createDevToolsWindow.js
This tweaks #876 to suggest the approach described in https://github.com/rackt/redux/issues/546#issuecomment-146755322 instead, as it works with any other middleware, and even with composed thunks.
> Suggest to use applyMiddleware() for testing async action creators

- webpack.config.base.js
`webpack` is defined but never used.
> remove unused webpack

- docs/basics/ExampleTodoList.md
- examples/todos-with-undo/components/AddTodo.js
- examples/todos-with-undo/index.js
- examples/todos-with-undo/package.json
We will update all examples at once when everything is ready.
Please, don't send PRs to update React to 0.14: #885
Project maintainers: please don't commit updates to 0.14 to master.
cc @omnidan
> Revert todos-with-undo being ported 0.14

- docs/advanced/ExampleRedditAPI.md
- docs/api/applyMiddleware.md
- docs/basics/ExampleTodoList.md
- docs/basics/Reducers.md
- docs/basics/UsageWithReact.md
- docs/recipes/ServerRendering.md
- docs/recipes/WritingTests.md
- examples/async/index.js
- examples/async/package.json
- examples/counter/index.js
- examples/counter/package.json
- examples/counter/test/components/Counter.spec.js
- examples/counter/test/containers/App.spec.js
- examples/todomvc/index.js
- examples/todomvc/package.json
- examples/todomvc/test/components/Footer.spec.js
- examples/todomvc/test/components/Header.spec.js
- examples/todomvc/test/components/MainSection.spec.js
- examples/todomvc/test/components/TodoItem.spec.js
- examples/todomvc/test/components/TodoTextInput.spec.js
- examples/todos-with-undo/components/AddTodo.js
- examples/todos-with-undo/index.js
- examples/todos-with-undo/package.json
- examples/universal/client/index.js
- examples/universal/package.json
- examples/universal/server/server.js
> Update examples and docs to React 0.14

- docs/advanced/Middleware.md
Right now, it clips at "fra" in Chrome on a 1280px wide Pixel:
This fixes that.
> Docs: Wrap <code> to fit on 1280px wide screen.

- docs/introduction/PriorArt.md
- fixes small typo in `docs/introduction/PriorArt.md`
> fix small typo

- docs/recipes/WritingTests.md
I had problems following [Writing Tests](https://github.com/rackt/redux/blob/master/docs/recipes/WritingTests.md). Tests where failing with timeouts instead of proper error messages. This pull request improves `mockStore` to properly pass any exception which may occur.
```
fetchPages
1) creates FETCH_PAGES_SUCCESS when fetching pages has been done
0 passing (2s)
1 failing
1) fetchPages creates FETCH_PAGES_SUCCESS when fetching pages has been done:
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```
```
fetchPages
1) creates FETCH_PAGES_SUCCESS when fetching pages has been done
0 passing (47ms)
1 failing
1) fetchPages creates FETCH_PAGES_SUCCESS when fetching pages has been done:
AssertionError: { type: 'FETCH_PAGES_SUCCESS',
pages:
[ { id: …
```
> Improves Writing Tests doc.

- src/utils/isPlainObject.js
Calling toString on Object may cost a lot. It's much better to
have cached value for it.
> Cached Object string representation

- docs/recipes/WritingTests.md
The section `Writing Tests > Async Action Creators` contains inconsistent names for action-type constants and action-creator function names.
> fix(docs): test recipe for async action creators contains inconsistencies

- book.json
I know this sounds a little bit ridiculous, however I struggle to find the link to
the repo on GitHub most of the time. This commit adds a little icon along with the
Twitter and co icons.
> Adds GitHub link to docs.

- docs/introduction/Ecosystem.md
- docs/recipes/WritingTests.md
Hi,
I discussed with @gaearon yesterday on [Twitter](https://twitter.com/dan_abramov/status/658689636227792896) about extracting the mock store logic into a separate package. The benefits are that we can test the library and don't need to copy paste code around when the mock example is updated in the docs.
Here's the module: https://github.com/arnaudbenard/redux-mock-store
Let me know if you want to append changes/more tests to the current implementation and reference the package in the redux docs.
Thank you ;)
> added reference to redux-mock-store in docs

- docs/introduction/Ecosystem.md
- docs/recipes/MigratingToRedux.md
Hi!
I've recently open-sourced [backbone-redux](https://github.com/redbooth/backbone-redux), a set of bindings that helps to keep your BB collections and redux tree in sync. 
It is used in production heavily now and helps us to gradually migrate our legacy Backbone/Marionette app to React + Redux without full rewrite. 
So I think that it maybe be useful for others to mention this option in the migration guide.
> adding backbone-redux to migration guide and ecosystem

- examples/async/server.js
- examples/counter/server.js
- examples/real-world/server.js
- examples/shopping-cart/server.js
- examples/todomvc/server.js
- examples/todos-with-undo/server.js
From: https://github.com/rackt/redux/issues/955
Wrapped each express constructor in parentheses to keep `express` from showing when running depcheck.  I did notice the examples have a lot of unused deps.  Should I go ahead and remove them?
Screenshot of some of the unused deps:
> Wrap require(express) in express constructor in examples/server.js.

- README.md
- docs/introduction/Examples.md
@gaearon I referenced some patterns you described in your PR, can you take a quick look?
With respect to the Examples in general, maybe we could replace "It covers:" with something like "Patterns:" and try to include links to relevant code in bullet points. Since many people use these examples as learning tools and references, the ability to scan and jump to patterns would be helpful.
> Add Shopping Cart to Docs (Examples.md)

- docs/basics/Reducers.md
The code for the first implementation of `todos` as an example of reducer composition is actually the same as the previous example, causing the following paragraph ("This is called *reducer composition*, and it’s the fundamental pattern of building Redux apps") to make no sense. 
This change adds the `todos` function from the following example to make this one more clear.
There are other ways the composition could be done, certainly, and I'm not sure that the one I chose is the most iconic, so feel free to suggest alternatives. :-)
> Add missing reducer composition example to docs

- test/createStore.spec.js
- test/utils/applyMiddleware.spec.js
- test/utils/bindActionCreators.spec.js
- test/utils/combineReducers.spec.js
- test/utils/isPlainObject.spec.js
- test/utils/mapValues.spec.js
- test/utils/pick.spec.js
hello,
this change unifies the test names to use descriptive syntax in all tests.
I found that in some places there were leftovers from the "should" syntax. :)
> descriptive syntax in all tests

- docs/basics/Actions.md
- docs/basics/README.md
- docs/introduction/PriorArt.md
- docs/introduction/ThreePrinciples.md
This is mostly small tweaks, punctuation, etc. They're general improvements that I split off from #1010 as I figured that there was less potential for these edits to alter the intent of the content, and, hence, the likelihood of the PR being accepted.
> Grammar and flow improvements in some of the intro and basic docs

- docs/advanced/ExampleRedditAPI.md
- docs/basics/ExampleTodoList.md
- docs/basics/UsageWithReact.md
- docs/recipes/ReducingBoilerplate.md
fix https://github.com/rackt/react-redux/issues/170
> Rename smart/dumb to presentational/container

- .eslintignore
- docs/introduction/Examples.md
- examples/async/index.html
- examples/async/webpack.config.js
- examples/counter/index.html
- examples/counter/webpack.config.js
- examples/real-world/index.html
- examples/real-world/routes.js
- examples/real-world/webpack.config.js
- examples/shopping-cart/index.html
- examples/shopping-cart/webpack.config.js
- examples/todomvc/index.html
- examples/todomvc/package.json
- examples/todomvc/webpack.config.js
- examples/todos-with-undo/index.html
- examples/todos-with-undo/webpack.config.js
- package.json
This will let people see the examples without having to have a dev environment set up
To see what it would look like:
* http://kolodny.github.io/redux/examples/async/
* http://kolodny.github.io/redux/examples/counter/
* http://kolodny.github.io/redux/examples/real-world/   <- this one needs to use a <Redirect /> :/
* http://kolodny.github.io/redux/examples/shopping-cart/
* http://kolodny.github.io/redux/examples/todomvc/
* http://kolodny.github.io/redux/examples/todos-with-undo/
universal won't work because it needs a node server to serve it
> Make gh-pages examples runnable

- .eslintignore
- docs/introduction/Examples.md
- examples/async/index.html
- examples/async/webpack.config.js
- examples/counter/index.html
- examples/counter/webpack.config.js
- examples/real-world/index.html
- examples/real-world/routes.js
- examples/real-world/webpack.config.js
- examples/shopping-cart/index.html
- examples/shopping-cart/webpack.config.js
- examples/todomvc/index.html
- examples/todomvc/package.json
- examples/todomvc/webpack.config.js
- examples/todos-with-undo/index.html
- examples/todos-with-undo/webpack.config.js
- package.json
Reverts rackt/redux#1076 because it breaks the website.
None of the links on http://redux.js.org/docs/introduction/Examples.html work, and links like http://redux.js.org/examples/todomvc/ don't work either.
> Revert "Make gh-pages examples runnable"

- docs/advanced/AsyncActions.md
The code snippet uses an ES5-style function expression. I've changed it to use an arrow function instead.
> Use ES6 syntax in fetchPosts()

- docs/recipes/ReducingBoilerplate.md
Regarding the previous examples, I think that `shouldCallAPI` method isn't consistent.
```
if (posts[userId]) {
// There is cached data! Don't do anything.
return
}
```
was translated to:
`shouldCallAPI: (state) => !state.users[userId]`
I think it's `shouldCallAPI: (state) => !state.posts[userId]`
> Stay consistent for shouldCallAPI method

- docs/advanced/AsyncActions.md
...and only render after the Promise it returns, completes.
->
...and only render after the Promise it returns completes.
> Fix typo in AsyncActions.md

- docs/api/Store.md
Added some more information about the return value of store.dispatch.
It should be the dispatched action but could also be the return value of the middleware chain, such as a promise of the dispatched action
> Docs: Added clarity re return value of store.dispatch

- src/utils/compose.js
- test/utils/compose.spec.js
Related to https://github.com/rackt/redux/issues/632#issuecomment-157361578
This allows us to provide our composition with multiple arguments.
It does so by pulling off the last function from our list, calling it with the provided args, and using the result as the initialValue for reduceRight (which we then call on the remaining functions). Unfortunately, this does make our simple one liner a little more complex
Let me know if you see a cleaner approach.
> composition can be seeded with multiple arguments

- src/utils/combineReducers.js
The shape of the previous state is irrelevant, what we’re actually
testing is that state has the same shape as our reducer object
`finalReducers`.
Also fixes the algorithm to be O(n) by using `#hasOwnProperty` vs doing
an array search O(n<sup>2</sup>).
> Refactor combineReduer's Unexpected State Shape Warning

- docs/recipes/WritingTests.md
-The thunk action 'fetchTodos' resolves the promise and then passes json.body to the fetchTodosSuccess. 
-The bug was returning 'undefined' for json.body because the mock response was not returning a body
> Fix nock response to return a body

- docs/recipes/WritingTests.md
-Since expect is being used inside of the 'redux-mock-store', there is no longer a need to import expect in this example 
-The same is applicable to 'applyMiddleware', because it's being imported in the 'redux-mock-store'
> Remove defined but not used imported libraries

- docs/introduction/Ecosystem.md
redux-router suggests using redux-simple-router in it's description, so put redux-simple-router first. Also update links to avoid redirect.
> Update Routing links

- docs/recipes/ReducingBoilerplate.md
'insin/redux-action-utils' has been deprecated, so should be removed from the document.
> remove insin/redux-action-utils (deprecated)

- examples/todomvc/test/actions/todos.spec.js
`actions.clearCompleted()` doesn't accept any arguments.
> Remove unnecessary arguments

- src/index.js
@gaearon my attempt at #1029 . Likely still needs a bit of work but I wanted to get your opinion before i continued. thanks!
> warn user when using minified code outside of NODE_ENV 'production'

- examples/todomvc/components/MainSection.js
- examples/todomvc/test/components/MainSection.spec.js
Perhaps this is an optimization to prevent against an unneeded re-render. However this may be adding more confusion to the example than benefit. Am I wrong by removing this?
> Examples: todomvc: Removed precondition to clear completed todo's

- README.md
- docs/introduction/Examples.md
- examples/tree-view/.babelrc
- examples/tree-view/actions/index.js
- examples/tree-view/containers/Node.js
- examples/tree-view/generateTree.js
- examples/tree-view/index.html
- examples/tree-view/index.js
- examples/tree-view/package.json
- examples/tree-view/reducers/index.js
- examples/tree-view/server.js
- examples/tree-view/store/configureStore.js
- examples/tree-view/webpack.config.js
This adds a performant tree view example by a popular request.
Answers http://stackoverflow.com/questions/34981924/performance-issues-with-a-tree-structure-and-shouldcomponentupdate-in-react-re.
> Add tree view example

- docs/introduction/Examples.md
- examples/counter-vanilla/index.html
The new Counter Vanilla example is aimed to dispel the myth that Redux requires Webpack, React, hot reloading, sagas, action creators, constants, Babel, npm, CSS modules, decorators, fluent Latin, an Egghead subscription, a PhD, or an Exceeds Expectations O.W.L. level.
Nope, it's just HTML, some artisanal `<script>` tags, and plain old DOM manipulation. Enjoy!
> Add counter-vanilla example

- package.json
Replace `process.env.NODE_ENV` by adding this config when using browserify.
React also written this config: https://github.com/facebook/react/blob/0ce28c6e88448af6eda69df66088b88e7248bbb7/packages/react/package.json#L29-L33
Thanks
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/rackt/redux/1301)
> Add browserify config

- docs/advanced/AsyncActions.md
- docs/advanced/ExampleRedditAPI.md
- docs/advanced/Middleware.md
- docs/api/applyMiddleware.md
- docs/api/compose.md
- docs/api/createStore.md
- examples/async/store/configureStore.js
- examples/real-world/store/configureStore.dev.js
- examples/real-world/store/configureStore.prod.js
- examples/shopping-cart/index.js
- examples/universal/common/store/configureStore.js
- src/createStore.js
- test/createStore.spec.js
(Updated to @timdorr’s suggestion in https://github.com/rackt/redux/pull/1294#issuecomment-175938621)
```diff
- const createStoreWithMiddleware = applyMiddleware(thunk, logger)(createStore)
- const store = createStoreWithMiddleware(rootReducer, initialState)
+ const store = createStore(
+   rootReducer,
+   initialState,
+   applyMiddleware(thunk, logger)
+ )
```
It’s often said that creating a store with enhancers like `applyMiddleware()` or `DevTools.instrument()` is weird because it just looks outlandish in JavaScript to compose functions in such a savage way:
```js
// bad
const createStoreWithMiddleware = applyMiddleware(thunk, logger)(createStore)
const store = createStoreWithMiddleware(reducer, initialState)
// and even worse
const finalCreateStore = compose(
applyMiddleware(thunk, …
```
> Add first-class support for store enhancers to createStore() API

- src/applyMiddleware.js
3.1 changed the signature of `createStore()`. This isn't considered a breaking change because existing enhancers will continue to work; however, going forward, it should be expected that a store enhancer returns a `createStore` function with the same signature as its input.
See https://twitter.com/acdlite/status/692772885186764802 for context
Still needs tests :)
> Update applyMiddleware enhancer to use new createStore signature

- package.json
> Add loose-envify as a dep for Browserify users.

- src/createStore.js
- test/createStore.spec.js
> replaceReducer() should throw if argument is not a function

- src/createStore.js
- test/createStore.spec.js
Fixes: https://github.com/rackt/redux/issues/1324
> subscribe to throw when listener is not a function

- examples/counter/package.json
- examples/todomvc/package.json
This PR just adds support to set ENV variables when using npm scripts, that supports Windows
> Minor :: use cross-env; npm script support

- package.json
- webpack.config.js
> Update to lodash v4.2.0.

- docs/recipes/ComputingDerivedData.md
Update Computing Derived Data example recipe to reflect the new Usage With React code.
This example operates on the VisibleTodosList container instead of App as in the previous version.
-Rename memoized selector visibleTodosSelector to getVisibleTodos
-Rename selectors/todoSelector.js to selectors/index.js
-Update function names in text as appropriate
> Update ComputingDerivedData.md [WIP]

- README.md
Chess iX has been recently renamed to Ximedes. We would appreciate if the sponsor link could be updated to our new website.
> Update README.md to reflect new name of Chess iX

- src/combineReducers.js
- test/combineReducers.spec.js
Minor rewording of error message to address issue #1375.
Old message:
` Uncaught Error: Reducer "nameReducer" returned undefined handling "SET_NAME". To ignore an action, you must explicitly return the previous state.`
New message:
`Uncaught Error: Given action "SET_NAME", reducer "nameReducer" returned undefined. To ignore an action, you must explicitly return the previous state.`
> Reword error message for 'reducer returned undefined'

- docs/api/compose.md
- src/compose.js
This PR updates the documentation comment in `compose.js` to clarify that the rightmost function can have multiple arguments, as it provides the signature for the resulting composite function.
> Clarify comment in compose.js

- examples/testAll.js
Ran into this while trying to add component tests to the todos example. Currently running `npm run test:examples` results in the following error:
```
npm run test:examples
> redux@3.3.1 test:examples /Users/jon/Documents/Coding/Open Source/redux
> cross-env BABEL_ENV=commonjs babel-node examples/testAll.js
> redux-async-example@0.0.0 test /Users/jon/Documents/Coding/Open Source/redux/examples/async
> echo "Error: no test specified"
Error: no test specified
> redux-counter-example@0.0.0 test /Users/jon/Documents/Coding/Open Source/redux/examples/counter
> cross-env NODE_ENV=test mocha --recursive --compilers js:babel-register --require ./test/setup.js
/Users/jon/Documents/Coding/Open Source/redux/node_modules/babel-core/lib/transformation/file/options/option-manager.js:393
throw new …
```
> Add missing dependencies to get test:examples to run

- examples/real-world/containers/App.js
- examples/real-world/containers/RepoPage.js
- examples/real-world/containers/Root.dev.js
- examples/real-world/containers/Root.prod.js
- examples/real-world/containers/UserPage.js
- examples/real-world/index.js
- examples/real-world/package.json
- examples/real-world/reducers/index.js
- examples/real-world/store/configureStore.dev.js
- examples/real-world/store/configureStore.prod.js
React Router Redux recently incorporated the changes originally suggested in #1362. The RC of 4.x is out, so I encourage you to start migrating from the old versions.
The 4.x release is motivated by the desire to fix a few long-standing hard-to-fix bugs, become closer to Redux way of doing things, and by API changes in React Router 2.0. I know this is a lot of churn but it comes out of the lessons we learned from the real world usage. After this change, the project should be much more stable.
In case you haven’t been following, here is what changed:
Since React Router 2.0 gives us convenient history singletons (`hashHistory` and `browserHistory`), the middleware to handle history actions is no longer necessary. **It still exists** for those who prefer to `dispatch(push())` rather than …
> Use react-router-redux@4

- docs/api/applyMiddleware.md
The example of the tip for apply a middleware threw some errors to me. The reason is because an array was passed to applyMiddleware.
We should pass each elem of the array as an argument first to get it to work.
> Update example for conditional applyMiddleware

- .editorconfig
As a reaction to [@gaearon’s tweet](https://twitter.com/dan_abramov/status/700406516810182656). ;)
> Adjust editorconfig to not trim trailing whitespaces in Markdown files

- docs/introduction/Ecosystem.md
Added a link to my "React-Redux Links" repo.  It's intended to be more tightly focused than "Awesome Redux", and serve as a starting point to the React-Redux ecosystem.
> Add React-Redux Links to Ecosystem page

- docs/recipes/WritingTests.md
Updating docs regarding React updates on Shallow Rendering: https://github.com/facebook/react/issues/4019#issuecomment-172470697
> setState + shallow rendering are now working fine

- examples/tree-view/reducers/index.js
Spread operator is really not necessary here. It can be replaced with a simple filter function. Fortunately `.filter()` returns new array instance as it required by Redux and here it has a perfect fit.
Even more, [filter works here faster](http://jsperf.com/array-remove-in-es6): because doesn't create temporary arrays.
> tree-view: simplify reducer function

- docs/Troubleshooting.md
- docs/basics/Reducers.md
- docs/introduction/ThreePrinciples.md
As it was discussed in https://github.com/reactjs/redux/pull/1468, ES5 array methods like `map` and `filter` are recommended approach rather than array slicing.
> docs: replace slice calls to map

- docs/Troubleshooting.md
- docs/basics/Reducers.md
- docs/introduction/ThreePrinciples.md
Just found out that some text mentions that reducer uses `slice` to create a new array. Once we changed it in #1477, we should change surrounding text as well.
Does new text look good for you?
I really should more carefully read the text before sending that PR. Sorry about that.
> docs: fix surrounding text after changes in #1477

- src/combineReducers.js
- src/createStore.js
- src/utils/actionTypes.js
- test/combineReducers.spec.js
This is #1343 rebased on the `next` branch.
> Move ActionTypes to a private export

- examples/counter/package.json
- examples/counter/test/components/Counter.spec.js
- examples/counter/test/setup.js
This removes TestUtils, switches to shallow rendering, and removes jsdom from the Counter example.
> use enzyme in tests (resolves #1481)

- docs/basics/Reducers.md
Found an error (at least I think it is) when working through the todo tutorial.
```javascript
return state.map(todo, index) => {
if (index === action.index) {
return Object.assign({}, todo, {
completed: true
})
}
return todo
}
```
...has been changed to...
```javascript
return state.map((todo, index) => {
if (index === action.index) {
return Object.assign({}, todo, {
completed: true
})
}
return todo
})
```
Hope this helps! :smile:
> Fixes a documentation typo in basics/Reducers

- docs/recipes/WritingTests.md
I have updated https://github.com/arnaudbenard/redux-mock-store to be framework agnostic and have less errors.
This PR updates the documentation with the new syntax.
> update redux-mock-store documentation

- docs/introduction/Ecosystem.md
Updated Ecosystem with `redux-side-effects` yet another approach for side effects.
**Why it should be part of the Ecosystem?**
- Package is another approach which is trying to simulate Elmish approach to Side Effects
- Package is conceptually very similar to `redux-loop` but using a different mechanics (Generators). Some people may consider the API less "awkward"
- Package follows strict development process
- Package follows SemVer
- Package is being used in production apps for more than a half year.
- We try to cover all the functionality with Unit tests
- API is stable now
- [Surface area is pretty small](https://github.com/salsita/redux-side-effects/blob/master/src/createEffectCapableStore.js#L28-L33)
> Updated Ecosystem, reference to salsita/redux-side-effects

- docs/recipes/WritingTests.md
TLDR: **This PR fixes the test in Async Actions documentation to correctly pass/fail**
The docs (but not the [website](http://redux.js.org/docs/recipes/WritingTests.html)) were recently updated for v2 of [redux-mock-store](https://github.com/arnaudbenard/redux-mock-store) by the creator @arnaudbenard himself in #1515.
However best I can tell the changes do not appear to be correctly testing the async actions.
They appear to be:
- Not testing that the fetch was called.
- Not testing the entire action, only the type.
- Only testing 'FETCH_TODOS_REQUEST' instead of 'FETCH_TODOS_REQUEST' and 'FETCH_TODOS_SUCCESS'.
This PR fixes the test to correctly pass/fail.
Please let me know if I am mistaken.
I would also be great if the website was updated with master when you get the chance, so that …
> Update docs - Writing tests - Async actions text example

- package.json
Maybe I am missing something but it seems index.d.ts should be added to package.json to get into distributed npm package.
> Added index.d.ts to package.json

- docs/FAQ.md
This is work in progress on prettifying (and slightly rewording) the FAQ. The content is awesome but it doesn’t quite match our existing styleguide and has other minor stylistic issues:
* It uses `'` instead of `’`
* It uses `-` instead of either `—` or, in case of lists, `:`
* It uses `:` in the heading but we generally don’t
* It has a lot of double spaces
I know I’m probably the only one who cares about this so I’ll go slowly over the content myself and fix these :smile: . Thanks to everyone who worked on it, I love the content!
> Prettify FAQ

- book.json
- docs/FAQ.md
Added a Table of Contents, plus shorter anchor links than Github generates.  Some additional editing and article links.  Also added a new Gitbook plugin to mostly fix trying to go directly to a link with a hash anchor in it.
> FAQ page updates

- index.d.ts
- test/typescript/dispatch.ts
This PR follows https://github.com/reactjs/redux/pull/1413. I will open up some wounds here, so please excuse me if I missed any of the points in the previous conversation.
**Signature of dispatch**
The problem that I still have is with the signature of `dispatch`. `any` just isn't type-safe at all. It will propagate silently in the app without the developer even realizing. w.r.t what @pajn and @joshuacc said, there is a difference between consciously making a choice to type-cast and getting `any` by default. With this in mind, it's even better to use `{}` instead of `any` (which btw is what type parameters default to anyway). 
Given the nature of `dispatch` and it being wrapped by middlewares, it isn't possible to properly type it to account for every possibility. (goes with what @xogeny …
> TypeScript definitions improvements

- index.d.ts
- test/typescript/store.ts
Following up https://github.com/reactjs/redux/pull/1526#issuecomment-205403474 here is a PR that enhance typyings for `StoreEnhancer`.
- make `StoreEnhancer` to be parameterized by state type, because it's always being called with known type of the state, so that it opens a way to create state-specific enhancers
- when a generic version of `StoreEnhancer` is needed, newly introduced `GenericStoreEnhancer` can be used, which a function with same signature but has a state type parameter; obviously it's assignable to any typed store enhancer
- `StoreEnhancer` exposes a `StoreEnhancerStoreCreator<S>` as a result, that is a stricter version of `StoreCreator` which strictly expects to get a reducer and initial state (not optionals)
- `applyMiddlewares` now returns `GenericStoreEnhancer` as the …
> Improve typing of StoreEnhancer

- src/applyMiddleware.js
In the original version, the `dispatch` local variable in `applyMiddleware` stands for
different things before and after the `compose` call.
It'd be more expressive to separate "the original one on store" and "the one with middlewares applied"
> remove initial assignment of `dispatch` in applyMiddleware to make it more expressive

- docs/basics/Actions.md
As a result of this PR:
https://github.com/reactjs/redux/pull/1589#issuecomment-206778709
I understood that some of my understanding about Action Creators were
false. This PR aims to make the fact that action creators are the places
where to make API calls more explicit and clearer for future
readers.
> Add a note that action creators do not have to be pure

- docs/basics/Actions.md
As a casual reader the flux example might be confusing.
This is a Redux document, why not jump to the best part first?
> Actions.md: swapped the order of flux and redux examples. Redux first.

- package.json
- src/createStore.js
- test/createStore.spec.js
- Adds `Symbol.observable` method to the store that returns a generic observable
- Adds tests to ensure interoperability. (rxjs 5 was used for a simple integration test, and
is a dev only dependency)
closes #1631
> feat(store): add observable proposal interop to store

- src/applyMiddleware.js
- test/applyMiddleware.spec.js
Fixes #1644 which is a regression introduced in #1592 that got into 3.5.0.
Some middleware was relying on this pattern, and we broke it.
This PR reverts #1592 and adds a test for this regression.
> Keep dispatch available while middleware is initializing

- package.json
This updates symbol-observable dependency to be 0.2.3 or higher in order to fix an issue where legacy browsers did not like `Symbol.for` statement inside of the ponyfill
related #1632
related #774
> fix(Symbol.observable): update symbol-observable to fix IE8 issue

- package.json
This updates symbol-observable to 0.2.4 which resolves edge cases where a user may have another polyfill for Symbol.observable in place that results in redux store as not being identifiable as 'observable'. See http://github.com/blesh/symbol-observable/issues#7 and https://github.com/sindresorhus/is-observable/issues/1#issuecomment-214479549
> chore(dependencies): update symbol-observable to 0.2.4

- examples/async/actions/index.js
All action functions returned objects using the property value shorthand for the 'reddit' key & value except for 'receivePosts'. I updated it simply for consistency. I think it was just an oversight.
> Use object literal property value shorthand consistently

- README.md
more discoverable than https://github.com/reactjs/redux/pull/1608
> use subscribe to persist to localStorage

- docs/basics/Actions.md
- docs/basics/Reducers.md
- docs/basics/Store.md
The examples in the Basics documentation use COMPLETE_TODO actions all the way up until 2.6 with the complete todo list source code, where it uses a TOGGLE_TODO action.
> Change doc examples to use TOGGLE_TODO action consistently

- examples/shopping-cart/package.json
`expect` package is missing from devDependencies and it's required to run tests in this example.
> Add expect to devDependencies to run tests

- docs/recipes/WritingTests.md
I had to add a `.babelrc` change to get the default examples to work, as described [here](http://jamesknelson.com/testing-in-es6-with-mocha-and-babel-6/). Without doing this, Mocha complained `import` was an unexpected reserved word.
I am running node 4.4.3.
> Add extra required babel configuration step

- examples/real-world/middleware/api.js
The normalizr lib has moved to a different location. Update the URL in comments to point to the new repo.
> Update api.js normalizr URL

- docs/FAQ.md
- docs/api/README.md
- docs/api/applyMiddleware.md
- docs/recipes/WritingTests.md
Hi!
Just removed semicolons from docs code, according to code style.
> Docs: remove semicolons according to code style

- docs/Glossary.md
- docs/advanced/ExampleRedditAPI.md
- docs/api/README.md
- docs/api/applyMiddleware.md
- docs/api/createStore.md
- docs/recipes/ServerRendering.md
- examples/async/store/configureStore.js
- examples/real-world/store/configureStore.dev.js
- examples/real-world/store/configureStore.prod.js
- examples/todomvc/store/configureStore.js
- examples/tree-view/store/configureStore.js
- examples/universal/client/index.js
- examples/universal/common/store/configureStore.js
- examples/universal/server/server.js
- index.d.ts
- src/applyMiddleware.js
- src/combineReducers.js
- src/createStore.js
- test/typescript/store.ts
This renames `initialState` in `createStore` and `configureStore`, as well as `window.__INITIAL_STATE__` to address https://github.com/reactjs/redux/issues/1743. It doesn't touch use of `initialState` in the reducer examples. 
There are a couple of comments that refer to `preloadedState` as 'initial state' that weren't addressed because I thought 'initial state' added to readability, e.g. https://github.com/reactjs/redux/compare/master...dliv:issue-1743?expand=1#diff-2b443c0a3e751858f6315977ee4a769aR85
> Issue 1743

- docs/recipes/WritingTests.md
Having it named mapDispatchToProps can be confusing, since connect takes
a mapStateToProps function as first argument.
> Correct first argument name into mapStateToProps

- src/combineReducers.js
- test/combineReducers.spec.js
Resolves #1748 
Pretty simple, just keeps a caches and filters keys that have already been warned about.
I had to update one of the related tests as it expected some keys to be warned about multiple times.
> Only warn for unexpected key once per key

- docs/introduction/ThreePrinciples.md
Hi Dan and the whole redux Dev Team,
I'd kindly ask you to review this little documentation change affecting the introduction/Three Principles chapter.
As proposed in the commit message I'd suggest to use the word 'change' instead of 'mutate' to avoid confusion with the concept of 'immutable state'. As we all know: While not enforced, making state objects immutable is a strongly recommended way of using redux (and only then redux plays well together with pure reducers, time traveling and so on).
I found myself felt a bit confused when reading the introduction for the first time. Furthermore I remember to have seen similar comments elsewhere here.
Maybe this little change helps people not getting on the wrong path in the very beginning.
Cheers and thanks for checking this,
Matthias
> Avoiding confusion with "mutating state"

- docs/recipes/WritingTests.md
- examples/todomvc/package.json
Fixes #1679.
Notes:
* I didn't bother updating all tests in the TODOMVC app because it's (supposedly) already being worked on, see #1471 and #1493 (and they were even removed in #1480), as well as #1481 claiming that the TODOMVC app will be "completely replaced". If you have changed your mind on that (I'm not sure where that decision came from and that was from 2 months ago), let me know and I'm happy to update the rest of the tests to use Enzyme.
* I removed mention of an old issue with `setState()` that Enzyme automatically handles.
> Update "Writing Tests" doc to use Enzyme

- docs/basics/Reducers.md
babel-plugin-object-assign is deprecated
> Directs to babel-plugin-transform-object-assign instead

- src/combineReducers.js
- test/combineReducers.spec.js
This is easy to accidentally do with import statements and `combineReducers` doesn't currently give any indication of anything going wrong, it just ignores properties that aren't functions.
```js
// forgot to export
const thing = (state, action) => ...
```
```js
import {thing} from "../actions/thing"
combineReducers({
thing
})
```
> Add a warning for undefined properties passed to combineReducers

- docs/api/combineReducers.md
It is not clear from the documentation that it is insufficient to merely avoid ever passing in `undefined` as state by using initial state. `assertReducerSanity` will test that your reducer does the right thing when passed `undefined`, even if you never intend for it to be called this way.
This documentation change makes that behavior clearer, in the hopes of saving new users from needless frustration. It was very confusing to see my reducer passed undefined even though I never intended it to be used that way. I did not suspect `combineReducers` would do this.
Hope this helps!
> document assertReducerSanity behavior

- examples/universal/server/server.js
See https://github.com/reactjs/redux/issues/1855 for details.
> fixes xss vulnerability in universal example, #1855

- package.json
This is what webpack 2 prefers. Ideally Rollup will follow along as well, at which point we can drop `jsnext:main`.
> Add module entry point for webpack 2

- index.d.ts
- test/typescript/compose.ts
Introduce more strict typings for `compose` function to allow smarter inference, e.g.:
```ts
import {compose} from "redux";
import {connect} from "react-redux";
import {withRouter} from "react-router";
compose(
withRouter,
connect(
(state, ownProps) => {
return {
foo: 'bar',
};
}
)
)(props => {
// `props` type is inferred to `{foo: string, router: Router}`
});
```
cc @ulfryk, @Igorbek
> Improve typings for `compose` function

- docs/recipes/WritingTests.md
There's an extra comma in package.json on WritingTests example recipe page that would cause some of the npm commands to fail
> Removed extra comma in package.json example

- docs/advanced/AsyncActions.md
from ”headlines for a select subreddit” to: => ”headlines for a selected subreddit”.
> small wording fix

- examples/shopping-cart/actions/index.js
- examples/shopping-cart/components/Cart.js
- examples/shopping-cart/components/Product.js
- examples/shopping-cart/components/ProductItem.js
- examples/shopping-cart/components/ProductsList.js
- examples/shopping-cart/containers/App.js
- examples/shopping-cart/containers/CartContainer.js
- examples/shopping-cart/containers/ProductsContainer.js
- examples/shopping-cart/index.js
- examples/shopping-cart/reducers/cart.js
- examples/shopping-cart/reducers/index.js
- examples/shopping-cart/reducers/products.js
The pull request I mentioned in #1883. I would appreciate feedback on this. If I have missed anything, please let me know and I will get on it right away.
> Shopping cart example updates

- docs/FAQ.md
Just a tiny change in this sentence:
> This keep(s) components decoupled from the actual data changes...
Loving the documentation, btw, great job.
> Fixed a typo

- README.md
- docs/basics/UsageWithReact.md
- examples/counter-vanilla/index.html
According to the [creator's twitter](https://twitter.com/mjackson/status/770427936449101824) and the [npmcdn's website](https://npmcdn.com/#/) the project was renamed to *unpkg* to avoid trademark issues. 
This PR updates the references to 'npmcdn.com' in Redux's examples and docs to the new link.
> Updated `npmcdn.com` links to `unpkg.com`

- .eslintignore
I broke linting of examples in #1883 because they are now linted via CRA, and it has incompatible configuration with the ancient version of ESLint we’re using. Our lint setup is a mess right now, with `rackt` config being used which is not maintained anymore. For now, I’ll just disable linting of examples altogether to try to get Travis to pass. In the future we should pick a lint config and update ESLint to a modern version.
> Don't lint examples

- SUMMARY.md
- book.json
- build/gitbook.css
- package.json
Went down this rabbit hole because I was sick of the `graceful-fs` warnings on Node 6. So, this fixes that.
Retained everything from the original Gitbook theme, as far as I can tell. The only thing missing is the read-tracking checkmarks, but honestly I didn't find much value in them. Maybe others do, though? I can look into a replacement if it's a big deal. 
Also, I'm going to go check into #1865 so the next build works for hash links.
> Update Gitbook version

- docs/advanced/UsageWithReactRouter.md
Hi,
I saw that there were no documentation yet for React-router(https://github.com/reactjs/redux/issues/1919). So I tried to create documentation following Dan's series on Egghead.io
Do we have to create an example to `/examples` for this chapter ?
This is my first significant PR to OSS, there are probably unclear explanations or mistakes in my PR I apologize for that I am still a junior dev.
How can I make my PR better ?
Thanks
> Documentation for UsageWithReactRouter.md

- docs/advanced/Middleware.md
- src/applyMiddleware.js
- test/applyMiddleware.spec.js
Recreates #1345
Closes #1240
Switched this to throw an error now.
> Warn When dispatching During Middleware Setup

- index.d.ts
- test/typescript/compose.ts
Fixes #1935.
Cc. @ulfryk @Igorbek
> Fix typings for `compose` function to accept single rest argument

- examples/counter/src/components/Counter.js
- examples/counter/src/index.js
- examples/counter/src/reducers/index.js
With this PR I would like to propose to add more ES6-like syntax in the examples. 
This is an opinionated subject since we might want to stick with some more ES5-like syntax in order for new comers to not be intimidated by the syntax on top of redux. 
Please let me know what you think.
> Fat arrow functions in the counter example

- docs/recipes/WritingTests.md
The examples now use CRA so it makes sense to also recommend Jest in the docs. 
See https://twitter.com/flashpunk/status/775350612879749121
> Suggest Jest as default

- examples/async/src/actions/index.js
- examples/async/src/components/Picker.js
- examples/async/src/components/Posts.js
- examples/async/src/containers/App.js
- examples/async/src/reducers/index.js
Convert the async example files to using fat arrows and stateless components.
This is a follow up to what I started in the counter example in #1942. 
I’ll be ok if we decide to stick to the old notation on this example since the fat arrows don’t add any feature in itself, except reduce the number of lines in files.
References #1800
> Use more ES6 syntaxes in the async example

- docs/advanced/UsageWithReactRouter.md
The guide is making reference to `containers/VisibleTodoList.js` but it currently says `components/App.js`. This change renames the section to the correct filename.
> Fixes wrong file name in docs

- examples/real-world/src/actions/index.js
- examples/real-world/src/components/Explore.js
- examples/real-world/src/components/List.js
- examples/real-world/src/components/Repo.js
- examples/real-world/src/components/User.js
- examples/real-world/src/containers/App.js
- examples/real-world/src/containers/RepoPage.js
- examples/real-world/src/containers/Root.dev.js
- examples/real-world/src/containers/Root.prod.js
- examples/real-world/src/containers/UserPage.js
- examples/real-world/src/middleware/api.js
- examples/real-world/src/reducers/index.js
- examples/real-world/src/reducers/paginate.js
- examples/real-world/src/routes.js
- examples/real-world/src/store/configureStore.dev.js
- examples/real-world/src/store/configureStore.prod.js
Convert the async example files to using fat arrows, spread operators and stateless components.
This is a follow up to what I started in #1942 and #1945
References #1800
> Use more ES6 syntaxes in the real world example

- examples/shopping-cart/src/actions/index.js
- examples/shopping-cart/src/api/shop.js
- examples/shopping-cart/src/components/Cart.js
- examples/shopping-cart/src/components/Cart.spec.js
- examples/shopping-cart/src/components/Product.js
- examples/shopping-cart/src/components/Product.spec.js
- examples/shopping-cart/src/components/ProductItem.js
- examples/shopping-cart/src/components/ProductItem.spec.js
- examples/shopping-cart/src/components/ProductsList.js
- examples/shopping-cart/src/components/ProductsList.spec.js
- examples/shopping-cart/src/containers/App.js
- examples/shopping-cart/src/containers/CartContainer.js
- examples/shopping-cart/src/containers/ProductsContainer.js
- examples/shopping-cart/src/reducers/cart.js
- examples/shopping-cart/src/reducers/index.js
- examples/shopping-cart/src/reducers/products.js
Convert the shopping cart example files to using fat arrows, spread operators and stateless components.
References  #1800
> Use more ES6 syntaxes in the shopping cart example

- examples/todomvc/src/actions/index.js
- examples/todomvc/src/components/Footer.js
- examples/todomvc/src/components/Footer.spec.js
- examples/todomvc/src/components/Header.js
- examples/todomvc/src/components/Header.spec.js
- examples/todomvc/src/components/MainSection.js
- examples/todomvc/src/components/MainSection.spec.js
- examples/todomvc/src/components/TodoItem.js
- examples/todomvc/src/components/TodoItem.spec.js
- examples/todomvc/src/components/TodoTextInput.js
- examples/todomvc/src/components/TodoTextInput.spec.js
- examples/todomvc/src/containers/App.js
Convert the shopping cart example files to using fat arrows, spread operators, static class members and stateless components.
References #1800
> Use more ES6 syntaxes in the todomvc example

- src/createStore.js
- test/createStore.spec.js
A minor issue, `listeners` is leaked as the `this` context when invoking each `listener`.
> Fix listeners array leak

- examples/todos-flow/.flowconfig
- examples/todos-flow/.gitignore
- examples/todos-flow/README.md
- examples/todos-flow/index.html
- examples/todos-flow/package.json
- examples/todos-flow/src/actions/index.js
- examples/todos-flow/src/actions/index.spec.js
- examples/todos-flow/src/components/App.js
- examples/todos-flow/src/components/Footer.js
- examples/todos-flow/src/components/Link.js
- examples/todos-flow/src/components/Todo.js
- examples/todos-flow/src/components/TodoList.js
- examples/todos-flow/src/containers/AddTodo.js
- examples/todos-flow/src/containers/FilterLink.js
- examples/todos-flow/src/containers/VisibleTodoList.js
- examples/todos-flow/src/index.js
- examples/todos-flow/src/reducers/index.js
- examples/todos-flow/src/reducers/todos.js
- examples/todos-flow/src/reducers/todos.spec.js
- examples/todos-flow/src/reducers/visibilityFilter.js
- examples/todos-flow/src/types/index.js
- flow-typed/react-redux.js
- flow-typed/redux.js
**Using Flow for statically analyzing state and actions**
This PR is a proof of concept and is not meant to be merged
Added examples (ordered by difficulty)
- `counter-flow`
- `todos-flow`
- `todomvc-flow`
Added libdefs (in the `ROOT/flow-typed` directory)
- `redux`
- `react-redux`
**Observations**
1) the best type safety is achieved by avoiding the following helpers
- `combineReducers` (you can miss a field and / or assign a wrong reducer to a field)
- `bindActionCreators` (<del>all action creator signatures are erased</del>) <= this is now type safe
`combineReducers` may be replaced by combining the reducers by hand (see the todos-flow example). `bindActionCreators` is unsafe when an object is passed in. <del>However `bindActionCreators` also accepts a single function which is safer …
> add examples with Flowtype support + libdefs for redux and react-redux

- src/createStore.js
Minor fix for JSDoc for createStore() arguments to avoid "missed argument" warning from IDE, e.g. WebStorm. Fixes #1979
> Minor fix for JSDoc for createStore() arguments

- examples/real-world/package.json
- examples/real-world/src/middleware/api.js
It’s not needed because Create React App includes a `fetch` polyfill and we’re not using server rendering here.
> Remove isomoprhic-fetch

- book.json
Following [my answer to #1982](https://github.com/reactjs/redux/issues/1982#issuecomment-250003780), this PR updates GitBook with a fix for anchor links on Firefox.
the URL is retained correctly (Chrome and Firefox), but there still some weird positioning on Firefox, I'll make another PR once we fix this issue as well.
> Update gitbook to use version 3.2.1

- examples/real-world/src/middleware/api.js
If you need to keep past promise results in scope, you can just nest.   There's no need for creating and de-structuring objects.  This makes the code look more complex than it would be in callbacks, when in reality the pyramid approach of callbacks works just as well if you accept small amounts of promise nesting.
Promises are about fixing error propagation and zalgo, not fixing the pyramid of doom.  The pyramid of doom is almost never a real/significant problem, so we should just accept it existing here.
> Simplify Promise nesting

- docs/recipes/reducers/ReusingReducerLogic.md
Reducers get called initialy to return their initial state, this action will probably not pass a filter.
Therefor it is necessary to check for undefined as the given state and return a call to the reducer,
in order to get the reducers state initialzed
> check for initialization call of redux in "Reuing Reducer Logic" example

- package.json
- src/combineReducers.js
- src/index.js
Redux seems to be great solution for managing state of browser extensions. Unfortunately it doesn't work properly with Firefox addons, because it requires global *process* object which is not available inside addon environment. This applies to both web-extensions and jetpack-based addons. In case of web-extensions it is possible make polyfill for *process* object, but it is not possible with jetpack (at least without [using custom modules loader][1]).
I've fixed this issue by checking if *process* object exists before using it. There was also issue with one of dependencies - *symbol-observable* - but it was [fixed yesterday][2].
[1]: https://gist.github.com/empyrical/f1cca44da1f81cb09a26
[2]: https://github.com/blesh/symbol-observable/pull/23
> Enable support for Mozilla Addons

- examples/async/package.json
- examples/counter/package.json
- examples/real-world/package.json
- examples/shopping-cart/package.json
- examples/todomvc/package.json
- examples/todos-flow/package.json
- examples/todos-with-undo/package.json
- examples/todos/package.json
- examples/tree-view/package.json
At react-scripts@^0.6.0 (as dev-dependencies of some examples), `eslintConifg` was removed from package.json default. (facebookincubator/create-react-app/pull/649)
At least, current value `./node_modules/react-scripts/config/eslint.js` is invalid in this version!
> Remove eslintConfig from package.json in examples

- docs/introduction/Motivation.md
Fix for parallelism:
**BEFORE:** "...we need to manage the active route, the selected tab, whether to show a spinner or not, should pagination controls be displayed, and so on."
**AFTER:** "...we need to manage active routes, selected tabs, spinners, pagination controls, and so on."
> Update Motivation.md for grammar

- package.json
In my framework I have a convenient feature that allows to automatically call AMD modules with RequireJS by their name. For instance, after `redux` installation I'm supposed to be able to do `require(['redux'], ...)` anywhere in my app and it should just work.
In order for above feature to work I'm using different keys from both `bower.json` and `package.json` in order to determine which file should be used by RequireJS to map package name alias there.
With Redux correct path is `dist/redux.js` (minified version can be inferred from here), but there is no single key with this value in current `package.json`. Existing keys are pointing to files that either doesn't work in any browser except recent Safari (ES2015 modules) or CommonJS-compatible file.
There was a key `browser` in jQuery's …
> Add hint key in package.json to detemine what file to load in browser

- docs/advanced/UsageWithReactRouter.md
> Fix typo in UsageWithReactRouter.md

- webpack.config.js
-  Fix https://github.com/reactjs/redux/issues/2054
> change webpack UglifyJsPlugin's config, which newest version do not enable IE8 support by default
see
[https://github.com/mishoo/UglifyJS2/commit/02c638209ee22816b1324ff0c0f47b27db1336af](https://github.com/mishoo/UglifyJS2/commit/02c638209ee22816b1324ff0c0f47b27db1336af)
> change webpack UglifyJsPlugin's config to fix #2054

- docs/basics/Reducers.md
Important to understand that if you move from custom combine function to combineReducers during refactoring, code: `myLastState === store.getState()` will have different behavior in some cases.
> combineReducers doc amendment

- src/compose.js
- test/compose.spec.js
In our project we found some case that can brake your application. 
It can be broken when you've tried to pass not a function in enhance array to compose function.
```
const toEnhance = [
router.enhancer,
applyMiddleware(...middleware),
window && window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__() // false in this case will cause a bug
];
const enhancer = compose(...toEnhance);
```
Of course I can filter array before passing it to enhancer, but I think it will be useful to manage it in compose function.
> Add support to compose only functions in utils/compose

- docs/api/combineReducers.md
Small typo: `combinedReducers` was fixed to `combineReducers`.
> Use the right function name for combineReducers

- docs/basics/Reducers.md
Because react-addons-update is legacy and the official doc on https://facebook.github.io/react/docs/update.html also references [immutability-helper](https://github.com/kolodny/immutability-helper) as a replacement.
> Replace react-addons-update

- docs/recipes/ServerRendering.md
This adds a comment directly in the code which most people copy and paste to do server rendering, which actually has potential to be an XSS vulnerability.
> Update ServerRendering to highlight security issue

- flow-typed/redux.js
Addresses #2114 
Updates CombineReducers flow-type
> Update argument type of reducer produced by combineReducers

- docs/recipes/ServerRendering.md
This short piece of code renders all html tags in JSON harmless, by replacing the `<` character with its unicode escape `\u003c`. Since the only place where JSON can have `<` is in strings, this is sufficient for protecting JSON from XSS injection.
Providing an easy cut'n'paste solution in the documentation ensures that more people will be protected from this problem.
> Provide example of initial state SSR scrub

- docs/advanced/UsageWithReactRouter.md
Fixed typo and improved clarity surrounding use of `<Link />`.
> Doc: clarify Navigating with React Router section

- src/compose.js
cleaned up the composer so that it doesn't rely on slicing and reversing the array of functions
> Simplify composer

- docs/basics/UsageWithReact.md
Having unique IDs on the sub-headings allows linking to sections of the documentation easier.  Without this change, the following link is ambiguous:
http://redux.js.org/docs/basics/UsageWithReact.html#container-components
> Changed sub-headings so that the IDs are unique

- docs/advanced/UsageWithReactRouter.md
* Footer component filename is listed as `containers/Footer.js` in docs
* Directory in the example app is `components/Footer.js`
* Update docs to match example app
> Fix filename typo in UsageWithReactRouter docs

- .eslintrc
- build/use-lodash-es.js
- src/applyMiddleware.js
- src/bindActionCreators.js
- src/combineReducers.js
- src/createStore.js
Fixes #2168. Updated all variable declarations to respective ES6 variants when applicable. All tests passed. No other code changed.
> Update variables to ES6

- src/compose.js
- test/compose.spec.js
1) With filtering `compose` does not have the well know definition of this function as like as in your comments https://github.com/reactjs/redux/blob/master/src/compose.js#L7-L9
2) Then I accidentally pass something what is not a function into compose, the only thing I could expect is an error not silent code execution. (there is no need at all to pass anything which is not a function)
3) Typed definition of compose (even you does not use it) will be really hard to create with filtering.
So I suggest you to remove this line.
> Remove filtering inside compose 

- test/applyMiddleware.spec.js
Behavior has been replaced with the "it warns when dispatching during middleware setup" test in the 'next' branch.
> Deletes no-longer-valid applyMiddleware test.

- docs/basics/UsageWithReact.md
Added an short blurb about having multiple containers in the component tree linking back to the FAQ for React Redux.
As discussed in the thread:
https://www.reddit.com/r/reactjs/comments/5ngjt5/passing_too_many_callbacks_from_containers_to/
> Doc: Update UsageWithReact.md

- docs/advanced/AsyncActions.md
As the example shows in `index.js` right below, it runs: 
`import { selectSubreddit, fetchPosts } from './actions'`
...but up until that point, `fetchPosts` is not exported from the `actions.js` file and would be unavailable to the `index.js` module. Changing such that `fetchPosts` is exported.
> Update AsyncActions doc

- docs/recipes/ServerRendering.md
If the reference is not removed, it cannot be GC'd. Once the store is created, there is no use for the global `window.__PRELOADED_STATE__` variable.
> SSR client: Free memory used for initial state

- examples/real-world/src/middleware/api.js
**Problem summary**
Real-world example doesn't work on browsers that are not supporting symbol data types.
**Change summary**
Updated `CALL_API` action key to be string primitive.
**Fix verification summary**
Tested on Windows, Internet Explorer 11
Resolves #2217
> Remove `Symbol()` from real-world example

- test/typescript/actionCreators.ts
- test/typescript/actions.ts
- test/typescript/compose.ts
- test/typescript/dispatch.ts
- test/typescript/middleware.ts
- test/typescript/reducers.ts
- test/typescript/store.ts
A little detail but the suffix '.d.ts' is not required for typescript imports (https://www.typescriptlang.org/docs/handbook/module-resolution.html).
The ts linter tell me `[ts] An import path cannot end with a '.d.ts' extension. Consider importing '../../index' instead.`.
> Remove .d.ts suffix for imports

- docs/api/Store.md
This commit fixes a small grammatical error in the Store API docs under the `subscribe` method.
> Fix Typo in Store API Docs

- docs/basics/UsageWithReact.md
Fixing a small mistake in the Presentational and Container Components section.
> Fix typo in UsageWithReact Docs

- docs/recipes/ServerRendering.md
If no static directory is defined, the handleRender middleware function will be called when the browser fetches for `/static/bundle.js` and will give back the index.html
> Fix issue : 2264

- docs/recipes/MigratingToRedux.md
I've recently found a new migration path and my colleague at work successfully introduced it to an existing project. 
This document was not very optimistic about the possibility of migration when I started researching it. I hope others can use the new migration path to escape dying Backbone ecosystem.
> Add reference to backbone-redux-migrator

- src/bindActionCreators.js
- test/bindActionCreators.spec.js
I've found myself debugging 'Dude, where's my prop?' situations when I've done something like
```javascript
import { doSomething } from './actions' // for whatever reason, `doSomething` is `undefined`
...
const MyComponent = props => {
...
const onClick = () => {
props.doSomething() // error at runtime --> doSomething is undefined
}
}
const mapDispatchToProps = {
...
doSomething
...
}
```
It would speed up debugging in these situations if `bindActionCreators` logged a warning when it's passed an object with non-function properties.
> Suggestion: Warn when bindActionCreators encounters non-function property

- docs/recipes/UsingImmutableJS.md
The HOC example in the UsingImmutableJS docs used a named export to import React, but it needs to be a default import.
> Update HOC example in UsingImmutableJS docs

- examples/async/README.md
- examples/counter/README.md
- examples/real-world/README.md
- examples/shopping-cart/README.md
- examples/todomvc/README.md
- examples/todos-flow/README.md
- examples/todos-with-undo/README.md
- examples/todos/README.md
- examples/tree-view/README.md
> Add additional CRA info to example READMEs

- docs/FAQ.md
There are 5 incorrect links in the Immutable section of the FAQs relating to `Immutable.JS` that have since been broken out into their own article in `/docs/recipes/UsingImmutableJS.md`. 
The links in `FAQ.md` still refer to the original location of these questions in `/docs/faq/ImmutableData.md`.
This PR simply breaks out the `Immutable.JS` questions into their own Table of Contents section, separate from the `Immutable Data` section, in `FAQ.md` to reflect their new home at `/docs/recipes/UsingImmutableJS.md`.
> Fix FAQs Table of Contents links to Immutable.JS questions

- docs/advanced/UsageWithReactRouter.md
List of changes:
containers/VisibleTodo.js 
- I have added the definition of getVisibleTodos because the case changed from 'SHOW_ALL' (original Todo tutorial) to 'all' (react-router tutorial) and vice versa for 'completed' and 'active'
containers/FilterLink.js
- This is a correction in which it should link to '/' for the 'all' link
add updated definition of index.js since it so different from the original Todo tutorial
> Correct example codes in UsageWithReactRouter.md

- test/applyMiddleware.spec.js
This is really, really minor, but object property enumeration order is not guaranteed despite being fairly consistent in browsers and node, but it doesn't hurt to take that into account and write the tests accordingly.
> applyMiddleware tests are using object property enumeration order

- docs/advanced/AsyncActions.md
- docs/advanced/ExampleRedditAPI.md
redux-logger [introduced a breaking change in import syntax](https://github.com/evgenyrodionov/redux-logger/commit/1d12b4125ad2069f1778f3541a94e90ace5e894b) some days ago. Old syntax doesn't work now:
Old syntax:
```javascript
import createLogger from 'redux-logger';
```
New syntax:
```javascript
import {createLogger} from 'redux-logger';
```
> Docs: update "import createLogger" to modern "import {createLogger}"

- src/combineReducers.js
This addresses issue https://github.com/reactjs/redux/issues/2334
This replaces `sanityError` and `assertReducerSanity` with more descriptive, less ableist language that describes what the check is actually doing (checking and asserting the shape). I'm proposing to call it `assertReducerShape` and describe the error as a `shapeAssertionError` so that we're more precise and more inclusive at the same time!
> Replace `sanity` language in combineReducers

- src/createStore.js
The repository still redirects, but it makes sense to use the name that's now in use
> docs(observable): es-observable GitHub repo moved to tc39

- docs/recipes/reducers/InitializingState.md
Fixes #2338, including a note about default values in reducers, even when using preloadedState
> Updating docs for default values w/ preloadedState

- docs/recipes/UsingImmutableJS.md
I think the `**` prior to `VALUE` in the Immutable sample HOC is a typo.
> Remove Markdown syntax from code block

- docs/advanced/ExampleRedditAPI.md
- docs/advanced/UsageWithReactRouter.md
- docs/basics/ExampleTodoList.md
- docs/basics/UsageWithReact.md
- docs/recipes/WritingTests.md
Changing the import of `PropTypes`, from `react` to `prop-types` package, as of React v15.5.0 update.
> Update docs with React v15.5.0

- docs/faq/General.md
Adding discussions links for FAQ - General
as per [1785](https://github.com/reactjs/redux/issues/1785) `Updates to Existing Questions` section
1. I re-arranged the orders of few titles like *dont use redux* to appear together
2. Omitted this discussion https://twitter.com/dan_abramov/status/801489026687651840 as I felt it might be overwhelming here
@markerikson Please review
> Faq general - Discussion links for when should i use Redux

- docs/advanced/UsageWithReactRouter.md
Since you talk about `browserHistory` a little later down anyway, it may confuse readers why it's included early on.
> Remove redundant import

- docs/introduction/CoreConcepts.md
- docs/introduction/ThreePrinciples.md
> Prettier to introduction folder

- README.md
This updates the README so that it links to the new webpack documentation site https://webpack.js.org/
> Link to latest webpack documentation in README

- examples/async/package.json
- examples/async/src/containers/App.js
- examples/async/yarn.lock
- examples/counter/package.json
- examples/counter/yarn.lock
- examples/real-world/package.json
- examples/real-world/src/components/Explore.js
- examples/real-world/src/containers/App.js
- examples/real-world/yarn.lock
- examples/todomvc/package.json
- examples/todomvc/yarn.lock
- examples/todos-flow/package.json
- examples/todos-flow/src/components/Link.js
- examples/todos-flow/yarn.lock
- examples/todos-with-undo/package.json
- examples/todos-with-undo/src/components/Link.js
- examples/todos-with-undo/yarn.lock
- examples/todos/package.json
- examples/todos/yarn.lock
- examples/tree-view/package.json
- examples/tree-view/src/containers/Node.js
- examples/tree-view/yarn.lock
* update to react-scripts@1.0.2
* Fix linting errors (https://github.com/reactjs/redux/pull/2419#issuecomment-302887134)
> Fix eslint warnings, update react-scripts

- examples/todos/src/reducers/todos.js
Hi there,
What I am proposing is removal of the [todo](https://github.com/reactjs/redux/blob/master/examples/todos/src/reducers/todos.js#L1-L21)  const and [usage of a simpler](https://github.com/dankoknad/redux/blob/todos-example-refactoring/examples/todos/src/reducers/todos.js) (IMHO) and still readable and understandable code. Purpose of this change is to make learning Redux and how to connect Redux to React a bit easier.
While learning awesome Redux and expecially how to connect Redux with React app, I have found that  const *todo* was one of the confusing pieces of code - at least it was for me. It looks exactly like a reducer - but it is **not**. It is helper function which has two arguments: *state*  and *action* (just like reducer), and *switch* statement also sugest to me that it …
> 'todo' const removal from reducers/todos.js

- examples/counter/src/components/Counter.js
Added method binding in constructor + prop checking.
> Fixed 'is undefined' error and prop checking in Counter example

- index.d.ts
This is going to be a bit roundabout, but bear with me. 😄 
Stricter checks on generics in TypeScript 2.4 correctly errored on the fact that reducers passed to `combineReducers` were expected to be more general than they actually needed to be.
Since the `A` type parameter was never used as part of the return type -  it was only used as a constraint - the appropriate next step was to replace the parameter type of `A` with the `Action` type directly:
```ts
export type Reducer<S> = (state: S, action: Action) => S;
```
However, because of excess property checks, this introduced errors when object literals were passed directly to a reducer. For example:
```ts
const rootReducer: Reducer<RootState> = combineReducers({
todos: todosReducer,
counter: counterReducer,
})
const rootState: RootState = …
```
> Fixed the definition of 'Reducer<S>' for TypeScript 2.4.

- README.md
This PR adds links to sandboxes in CodeSandbox for all examples except for the universal example (requires server) and the vanilla example (is no `create-react-app`). These links automatically stay up to date with the examples in the repository, and will update automatically when a new version of `redux` is released.
This is really helpful for beginners, since they can play with redux without installing it first. It's also very helpful when they have questions or bug reports, they can just fork the sandbox and create their own sandbox as example.
Let me know what you think!
List of examples:
* [Counter](https://codesandbox.io/s/github/reactjs/redux/tree/master/examples/counter)
* [Todos](https://codesandbox.io/s/github/reactjs/redux/tree/master/examples/todos)
* [Todos with …
> Add CodeSandboxes for almost all examples

- docs/introduction/Examples.md
This is an extension on https://github.com/reactjs/redux/pull/2486.
It adds the example sandboxes to the gitbook documentation as well.
> Add sandboxes to the examples in the docs

- docs/recipes/UsingImmutableJS.md
mapSateToProps -> mapStateToProps
> Fix a typo

- docs/faq/CodeStructure.md
Add two new links to "Code Structure" FAQ section (https://github.com/reactjs/redux/issues/1785)
I have a question regarding labels for the links, sorry if this question sounds stupid 😸
I looked through the docs and it seems that link labels are always just article/issue name. But in case of issue #384, the actual ticket is more about a naming convention but the comment is about how code structure affects time travel in devtools. Should this be mentioned in link label somehow?
> Add new links to Code Structure

- docs/recipes/WritingTests.md
I think thunk is a better example than 'singleDispatch'. The example is also more copy/paste-able.
> writing tests for middleware example changed

- CONTRIBUTING.md
CONTRIBUTING.md [contains](https://github.com/reactjs/redux/blob/master/CONTRIBUTING.md#testing-and-linting) missed `check:src` script, that was removed in https://github.com/reactjs/redux/commit/35cb4a914ea501c13534888eb01103d756e3619e. 
In this PR I'm adding `check` npm script, that includes lint and test and fix CONTRIBUTING.md.
> Remove usage of `check:src` npm script from contributing.md

- examples/real-world/src/components/Explore.js
- examples/real-world/src/components/List.js
- examples/real-world/src/containers/App.js
- examples/real-world/src/containers/RepoPage.js
- examples/real-world/src/containers/UserPage.js
Fixes https://github.com/reactjs/redux/issues/2469
This is the _simplest_ solution so the example continues to run, whether or not users have installed the top-level redux node modules. However, it may not be the approach the maintainers want to take, so feedback welcome!
> Ignoring eslint rule for defined class properties

- examples/shopping-cart/src/components/Product.js
- examples/shopping-cart/src/components/Product.spec.js
- examples/shopping-cart/src/components/ProductItem.js
- examples/shopping-cart/src/components/ProductItem.spec.js
I noticed at https://codesandbox.io/s/github/reactjs/redux/tree/master/examples/shopping-cart that the number of items left in stock isn't shown; I dug around and figured out that the `inventory` prop wasn't being passed down
> fix shopping-cart example to show inventory

- docs/basics/Reducers.md
The reducer example uses `SET_VISIBILITY_FILTER` constant,  but the import statement prior to the example is not explicitly importing it. This change explicitly imports the constant.
> Add missing SET_VISIBILITY_FILTER import

- CONTRIBUTING.md
I changed some information about the Examples section in CONRIBUTING.md:
- use the actual command to run examples tests (the old one didn't work)
- remove the build command, since it doesn't work (there's no npm script for building examples)
> Correct information about running tests for examples

- docs/advanced/AsyncActions.md
invalidateSubreddit function and its constant were missing in the actions.js after async functions changes introduced.
> added missing invalidateSubreddit action

- docs/FAQ.md
- docs/faq/DesignDecisions.md
I wrote up some answers for design decisions to the FAQ in response to [issue #1785](https://github.com/reactjs/redux/issues/1785)
I don't think that the md is perfect, and my page isn't showing up when I build the gitbook, but I wasn't sure how to proceed. Please advise on this. Thanks!
This is my first open source contribution. 😄
> Add design decisions to FAQ document

- src/applyMiddleware.js
- test/applyMiddleware.spec.js
As discussed in #2501, there's a bit of inconsistency as you can call `store.dispatch` with multiple arguments just fine, but in context of middlewares (say, thunk) only the first one is passed through. This PR tries to fix that.
> Make middleware API dispatch pass through all call arguments

- docs/advanced/AsyncActions.md
As it stands, there are multiple headings entitled `action.js`. On the official docs page, it offers a anchor to each heading, but this doesn't work because it will just match the `id` of the first `#### action.js` heading. This change adds some context, which will—in turn—make each heading unique.
> Annotate action.js headings

- examples/todomvc/src/reducers/todos.js
- examples/todomvc/src/reducers/todos.spec.js
New TODO items must be added to the bottom instead of at the top.
Closes #2574.
> TodoMVC example: add items in the correct order

- docs/basics/Store.md
Using const is more correct since you don't want unsubscribe to be mutated
> Changed unsubscribe from let to const

- examples/todomvc/src/components/MainSection.js
- examples/todomvc/src/components/MainSection.spec.js
As of todomvc-app-css v2.1.0, the "toggle-all" chevron decoration is no longer applied to the checkbox, but instead to its associated label.
Prior to this commit, the todomvc example did not use a label, so the v2.1.0 change had the effect of hiding the "toggle-all" control.
This commit adds the label -- fixing this bug.
Tests have been updated to reflect these changes.
> Fix Broken "toggle-all" in TodoMVC Example

- docs/advanced/Middleware.md
The previous URL still redirects but this updates to the latest link.
> Update GitHub URL for react-redux

- index.d.ts
- package.json
- test/typescript/compose.ts
- test/typescript/reducers.ts
- test/typescript/store.ts
This fixes many issues with the current TypeScript typings, while remaining mostly* backwards compatible:
- Add a type parameter to `Action` tracking the type of the `type` tag.
- Stop using the irrelevant state type param on `Dispatch` (but keep it around for backwards compatibility).
- Add a type parameter to `Dispatch` which is the type of things which may be dispatched (previously `Dispatch` had a polymorphic apply which allowed anything to be dispatched).
- Add type parameters `A` and `N` to `Store` which respectively track the actions it may dispatch and all other non-action things which may be dispatched. Then its `dispatch` method can take `A | N`.
- Add a type parameter `A` to `Reducer` which tracks the actions it understands, instead of just using `AnyAction`.
- Use [type …
> Revamp TypeScript typing with more type safety

- docs/advanced/UsageWithReactRouter.md
If you are skimming this guide, or already have react-router installed you will not read the section on "installing react router" - which will result in some very confused users.
Moving the warning to the top of the doc until I (or someone else) has a chance to update it to react-router 4.0
> Give a clearer warning that react-router guide is outdated

- src/combineReducers.js
While reading the source code I've noticed that this could produce such text:
`Given action an action`
which is really unnatural to say. So I've refactored it a little to be more human-friendly and produce either:
- `Given action "SOME_TYPE"`
- or `Given an action`
Also - if you dont like this `String(variable)` casting approach I may revert this change and amend my PR. But personally I think its more obvious in what it does (casting) + its shorter by 3 chars :P
> Fixed quote types inconsistency in a warning message

- src/applyMiddleware.js
Because #2200 #2131 https://github.com/reactjs/redux/pull/2128 #2028...
> Refactors applyMiddleware to reduce confusion around createStore args.

- src/bindActionCreators.js
- test/bindActionCreators.spec.js
> Make bindActionCreators transparently pass `this`.

- docs/advanced/UsageWithReactRouter.md
The recent PR by @timdorr for #2300 updated this guide to be compatible with Router v4, so the warning is now very confusing.
> Remove warning about router 2/3

- docs/recipes/ServerRendering.md
Commit message:
Starting with release 16.0.0 ReactDOM has a separate API for generating
client-side content on a page that already has server-side generated
content. This API is ReactDOM.hydrate
Link to release: https://github.com/facebook/react/releases/tag/v16.0.0
> Update Server Rendering recipe to include new ReactDOM API

- docs/recipes/MigratingToRedux.md
**What does this PR do?**
Clarifies which migration process is being described in the guide.
**Why?**
First, thanks for the docs! This is a big help as we convert our few bits of Flux to Redux.
However, when referencing this guide, a coworker and I were both confused at first glance, thinking the "Your process will look like this" line was referring to the previous line that describes migrating from Redux back to a related lib. 
Suggested edit is to move that line to the end so it's clear it's a note rather than the subject of the steps.
> MigratingToRedux

- index.d.ts
- test/typescript/store.ts
Fixes https://github.com/reactjs/redux/issues/2552
> TypeScript: Add DeepPartial type for preloaded state

- docs/basics/DataFlow.md
Minor markdown fix for documentation. I noticed that there was text being rendered in a code block (due to 4 space indent instead of 2 spaces), when it most likely should just be rendered as normal text.
> Update markdown syntax on DataFlow.md

- docs/api/compose.md
When require is given the path of a folder, node.js will look for an index.js file in that folder so no need for /index
> remove unnecessary path to file from docs

- docs/faq/Performance.md
This adds a "Will caching remote data cause memory problems?" section to the Performance FAQ. The answer includes links suggested in #1785 . cc: @markerikson
> Update FAQ: Will caching remote data cause memory problems?

- docs/advanced/AsyncActions.md
- docs/advanced/ExampleRedditAPI.md
- docs/recipes/WritingTests.md
isomorphic-fetch hasn't been updated for a while, so cross-fetch was created in order to provide a more updated, flexible and [fixed](https://github.com/matthew-andrews/isomorphic-fetch/issues/125) alternative to the community.
> Added a more updated alternative to isomorphic-fetch to the docs.

- examples/real-world/src/store/configureStore.dev.js
- examples/universal/common/store/configureStore.js
[`babel-preset-react-app` does not transform modules to CJS](https://github.com/facebookincubator/create-react-app/blob/master/packages/babel-preset-react-app/index.js#L107-L108) so I don't think we need to require `rootReducer` again
> no need to require `rootReducer` again

- src/combineReducers.js
- src/createStore.js
- src/utils/actionTypes.js
- test/createStore.spec.js
Fixes #1636 
Provides a separate private action for when we replace reducers. This allows us to specifically handle this case, which resolves a false dev-only warning for combineReducers currently.
> REPLACE action for replaceReducers

- examples/shopping-cart/src/actions/index.js
Looks like it's a miss as its already done at other instances like productId
> Use Object Literal Shorthand Syntax

- docs/basics/ExampleTodoList.md
- docs/basics/UsageWithReact.md
Add default case for `getVisibleTodos` and remove `#` from href in `Link.js`
> Get rid of console warnings in TodoApp of docs

- docs/introduction/Ecosystem.md
A small PR to include `redux-little-router` in the ecosystem docs.
> Add redux-little-router to ecosystem docs

- package-lock.json
- package.json
- rollup.config.js
`rollup@0.50` doesn't require an `externalHelpersWhitelist`. It's capable of removing `asyncGenerator` babel helper on its own.
> Rollup update

- docs/basics/Reducers.md
Make clear where reducers act on a state slice instead of on the whole state, by renaming their parameter 'state' to 'stateSlice'.
Motivation: My colleague and I were independently confused on the content of parameter 'state' in the reducers that act on a state slice.
> Make clear where reducers act on a state slice instead of on whole state

- docs/recipes/UsingObjectSpreadOperator.md
- docs/recipes/WritingTests.md
- package.json
With reference to issue #2735 updating docs to use babel-preset-env instead of es2015.
> update docs to use babel-preset-env instead of es2015

- docs/basics/Reducers.md
Instead of defining reducers by what actions are not, define reducers by what they are. A reminder of what actions are is kept in the text, for education purposes.
I am not a react/redux expert so feel free to correct any errors in the new text.
However, wording is subjective and a matter of taste. So, I'll understand if you won't consider merging the change.
> Simplify the definition of reducers

- docs/recipes/ComputingDerivedData.md
One of the basic principles of Redux - its state should never mutate. Rephrase sentence to prevent confusion about Redux state changes.
> [DOCS] Change "state mutated" to "state changed"

- test/typescript/middleware.ts
Not that it matters much, but the `logger` and `thunk` middlewares in the TS test code are in the "wrong" order. This PR switches them around to follow real-world usage.
> Better middleware order in TS test

- examples/todomvc/src/containers/App.js
- test/typescript/middleware.ts
- Update color scheme to darker versions with more contrast
- Adjusted markdown to comply with header tag hierarchy
- Add alt tag and aria-label to logo
> A11y Fixes

- docs/recipes/WritingTests.md
Since version 3, Enzyme now requires an adapter to be set up for the specific version of React.
This PR updates [Writing Tests](https://redux.js.org/docs/recipes/WritingTests.html) section of the docs to include the necessary setup instructions.
> Update setup instructions for testing with Enzyme

- docs/README.md
- docs/introduction/Ecosystem.md
- docs/introduction/LearningResources.md
Splits the "Ecosystem" docs page into "Learning Resources" and "Ecosystem", and updates both pages with content from my articles list and addons list.
Fixes #2588 .
> Restructure ecosystem page

- docs/basics/UsageWithReact.md
- docs/faq/ImmutableData.md
- docs/introduction/Ecosystem.md
- docs/recipes/UsingImmutableJS.md
This PR contains four commits with the following purposes:
1. Replace an instance of `presentional` with `presentational`
2. Remove trailing whitespace from two lines
3. Replace an instance of `Devtools` with `DevTools`
4. Replace one instance each of `emphasising`, `realising`, and `optimise` with their spellings in US English, in line with how similar words are spelled elsewhere in the documentation
I think that 1 is the only definite correction. If you don't think that 2, 3, or 4 are changes worth making, I'm happy to remove those commits from the PR.
> Spelling, capitalization, and whitespace changes

- examples/todos-with-undo/src/reducers/todos.js
* Add action filter to reducer undoableTodos
Details: In the example `todos-with-undo`, currently the reducer `undoableTodos` would respond to every single action, including the action(s) related to the reducer `visibilityFilter`, which should not be what to be expected.
> Fix example: todos-with-undo

- docs/advanced/UsageWithReactRouter.md
Before: 
>This is because we are filtering from `<VisibleTodoList />`'s `mapStateToProps()` is still bound to the `state` and not to the URL.
After:
>This is because we are filtering from `<VisibleTodoList />`'s `mapStateToProps()`, which is still bound to the `state` and not to the URL.
> DOCS: Fix grammatical error in UsageWithReactRouter.html#reading-from-the-url

- src/createStore.js
Fixes for https://github.com/reactjs/redux/issues/2810
And what do you say about function for errors like this:
```
function errorWithExpectedType(actual, expected) {
throw new TypeError(`Expected the ${actual} to be a ${expected}.`)
}
```
Instead of simple TypeError.
> Fixed article

- docs/basics/UsageWithReact.md
Minor tweak—but in this sentence, _case_ requires _the_ because the specificity of the prepositional phrase _of this tiny component_.
> Typo: Added 'the' before 'case of..'

- docs/advanced/UsageWithReactRouter.md
Change destination's link to learn React Router API V4 instead of V3
> Change destination's link : learn React Router API

- package.json
Use double quotes instead of single quotes for glob patterns. This is explained in the [prettier docs](https://prettier.io/docs/en/cli.html).
Closes #2828
> Fixed prettier glob pattern under windows

- docs/basics/UsageWithReact.md
Import and use the VisibilityFilters const from the actions file in the
documentation instead of using a hardcoded string.
I believe this will make things easier for the reader (as it did for me). Also, it doesn't seem to be a good practice to keep repeating constants throughout the codebase.
Some other places in the docs could benefit from this change. I didn't update them yet because I would like some feedback first.
> Update Footer to use to use VisibilityFilters from actions

- .gitbook.yaml
This PR fixes the issue about urls mentioned in #2837 and #2842.
You can test it on the test project (https://redux.gitbook.io/redux-test/) which is synced with my fork `SamyPesse/redux`:
- https://redux.gitbook.io/redux-test/docs/introduction/index.html
- https://redux.gitbook.io/redux-test/docs/basics/index.html
- https://redux.gitbook.io/redux-test/docs/advanced/index.html
- https://redux.gitbook.io/redux-test/docs/recipes/index.html
- https://redux.gitbook.io/redux-test/docs/Glossary.html
> Fix redirects in docs for previous urls

- README.md
This is in response to https://github.com/reactjs/redux/issues/2797
I read the contributing guidelines, and I saw something about publishing the docs via `npm run docs`. Is that needed for a change such as this?
> Added small summary of when to use redux

- package.json
See https://github.com/webpack/webpack/tree/master/examples/side-effects
Webpack 4 can more effectively tree shake when a module defines itself as having no side effects (aka, doesn't talk to things external to the module at the top level). I believe we qualify, but I'm putting this in as a PR just to be sure. Looks like it can easily net some byte savings for end users 👍
> Add a sideEffects: false flag for Webpack 4

- docs/introduction/Examples.md
IMHO, there is no need to specify this command in the documentation since all the examples are based off `create-react-app` and executing the `npm start` script calls the `openBrowser` method that does this by default. Would love to remove this `open ...` command to avoid confusion.
> [docs] [examples] remove the open localhost cmd from examples

- docs/recipes/ServerRendering.md
According to the [validator.js documentation](https://github.com/chriso/validator.js), XSS sanitization was removed from the library in late 2013. Because of this, I believe it makes sense to remove it as a suggestion from the SSR recipe. At the time, the maintainer suggested checking out [Google Caja](https://code.google.com/archive/p/google-caja/source/default/source). I also did some searching on NPM and found the following two packages, both of which seem full featured and popular:
https://www.npmjs.com/package/xss
https://www.npmjs.com/package/xss-filters
Should we replace the suggestion with one of the alternatives above? Definitely open to suggestions — thanks!
> Remove validator.js suggestion

- README.md
In the Examples section, the bulleted titles were linking to non-existing pages. Removed these links  and tweaked the formatting to improve readability a bit.
> README: Fix broken example links

- docs/faq/DesignDecisions.md
I found a little, not so relevant typo in the design decisions document. If you find it relevant, please merge.
> Fixed a typo in DesignDecisions markdown file

- examples/todos-flow/package-lock.json
- examples/todos-flow/package.json
- examples/todos-flow/src/containers/AddTodo.js
- examples/todos-flow/src/containers/FilterLink.js
- examples/todos-flow/src/containers/VisibleTodoList.js
React-redux flow libdefs has updated significantly since last update and does not need `Connector` type anymore: https://github.com/flowtype/flow-typed/pull/1731 .
I would have updated other packages too, but due to react-scripts issue https://github.com/facebook/create-react-app/issues/871 I couldn't run the scripts.
> Update todos flow to follow up-to-date libdefs

- docs/basics/ExampleTodoList.md
- examples/todos/src/actions/index.js
- examples/todos/src/components/Footer.js
- examples/todos/src/components/Link.js
- examples/todos/src/components/TodoList.js
- examples/todos/src/containers/AddTodo.js
- examples/todos/src/containers/FilterLink.js
- examples/todos/src/containers/VisibleTodoList.js
- examples/todos/src/index.js
- examples/todos/src/reducers/index.js
- examples/todos/src/reducers/todos.js
Some code clean-up for easier understanding and better conventions (i.e no temporary variable for connecting a component to the store).
> [todos] [refactor] improve the general style of the approach to React

- docs/recipes/reducers/PrerequisiteConcepts.md
http://www.t4d.io/javascript-and-immutability/ results in 404, so I removed it.
I did a few searches to see if the page had moved, but I came up empty.
> Remove dead link from Immutability reading list

- README.md
- docs/recipes/README.md
Added a large "Learn Redux" section near the front
Changed "Learn from the Creator" to "Learn from the Authors", and
expanded it to cover Dan's second video course, my "Practical
Redux" course, and my workshops
Misc cleanup:
Updated the React docs link
Removed the outdated IRC badge
Moved the "Testimonials" section
> Rewrite the README to add more learning resources and clean up

- docs/recipes/ComputingDerivedData.md
Added code that shows the reducers/actions needed for the "Accessing props in selectors" example in Computing Derived Data.
Closes https://github.com/reactjs/redux/issues/2896
> Add more code samples to example in Computing Derived Data recipe

- docs/advanced/Middleware.md
- docs/advanced/UsageWithReactRouter.md
- docs/api/Store.md
- docs/api/applyMiddleware.md
- docs/api/combineReducers.md
- docs/api/createStore.md
- docs/basics/Store.md
- docs/basics/UsageWithReact.md
- docs/recipes/reducers/InitializingState.md
Noticed that code examples use:
`let store = createStore(...)`
Since store is never reassigned, we should use `const`.
> docs: Change lets to const when creating store

- src/createStore.js
- test/createStore.spec.js
Redux briefly checks that observer received in observe function is a valid object and throw TypeError with useful user message if is not. 
However, it missed null case, as `typeof null === 'object'` (well-known js issue) and then failed with the obscure error message `Cannot read property 'next' of null`.  I'm sure that there is no reason to not to show the correct error message in all relevant cases
https://github.com/reactjs/redux/blob/master/src/createStore.js#L237
This PR fixes that inconsistency by throwing TypeError with the same useful message in case of null observer 
Note that this PR is not a breaking change in any way
> Fix missed case in "observe" type check

- src/applyMiddleware.js
Hello - I've been reviewing the Redux source and was trying to figure out what the purpose of assigning`chain` to an empty array was in `applyMiddleware`. There doesn't seem to be a scenario where `chain` is not immediately updated to `middlewares.map(middleware => middleware(middlewareAPI))`. Please let me know if I'm missing something here and thanks for a great library.
> Remove unneeded chain declaration

- docs/introduction/LearningResources.md
I just renamed the project to "Webamp" and figured I'd update references to it where possible.
Thanks!
> Winamp2-js has renamed to Webamp

- docs/advanced/ExampleRedditAPI.md
The use of `<a />` with `href="#"` is not compatible with [eslint-plugin-jsx-a11y](https://github.com/evcohen/eslint-plugin-jsx-a11y) which is a part of `create-react-app`. When a developer tries to copy an example and play with it locally, they see next warning:
```
Line 60:  Links must not point to "#". Use a more descriptive href or use a button instead  jsx-a11y/href-no-hash
```
While this being trivial, there still no that much justification for using anchor element as a button.
> Replace <a /> with <button /> in reddit example

- docs/introduction/CoreConcepts.md
Reflecting a few years later this was a bit of a silly thing to write in the docs.
Of course it's not simple to people learning it.
> Remove "Redux itself is very simple"

- docs/api/applyMiddleware.md
`middleware` is reassigned in the if-statement and hence must not be const.
This pull request is in regard to #2958.
> Fix erroneous use of const in docs

- examples/todos/src/containers/VisibleTodoList.js
- examples/todos/src/reducers/visibilityFilter.js
Two months ago the VisibilityFilters export was created. This commit removes the missed places where strings were still used and replaces it with VisibilityFilters
> Todos example: Always use VisibilityFilters instead of strings

- index.d.ts
- test/typescript/store.ts
When performing a refactor, I noticed that removing the `preloadedState` param from a `createStore` call resulted in a different type than calling `createStore` with `preloadedState`. This is due to the return type of `StoreCreator` being slightly different for each signature. Specifically, the one without `preloadedState` does not include a type param for the action type.
This PR adds the action as a type param for the return type of the `createStore` function without a `preloadedState` param, as well as a couple of additional tests in `tests/typescript/store.ts` that make sure the action type param is included in the return type for both signatures.
> Use same return type for both StoreCreator signatures in TS typings

- docs/recipes/ReducingBoilerplate.md
I think that writing `newState` in this case is more correct.
I propose to make it similar to this text https://github.com/reduxjs/redux/blame/master/docs/faq/Actions.md#L61
> [docs] Returning a newState

- package.json
This allows unpkg.com to point to the UMD build of redux via https://unpkg.com/redux. Currently, this points at lib/redux.js (as it falls back to using the `main` field) which will not run in browsers.
> Add unpkg field to package.json

- docs/faq/CodeStructure.md
Based on #2854 i added a new question to the FAQ Code structure page answering where to put persistent connections. I tried to not go in depth about things that already have a section in the faq.
Looking forward for feedback! :)
>  Docs(faq): Where should persistent connections live?

- docs/introduction/LearningResources.md
Because "many resources" is plural, I think the sentence should begin with "There are" rather than "There's" or "There is". 
Grammarly reference: https://www.grammarly.com/blog/there-is-there-are/
> Change "there's" to "there are" in Learning Resources documentation

- docs/README.md
- docs/recipes/ConfiguringYourStore.md
- docs/recipes/README.md
Recipe doc for creating a `configureStore` function, based on the discussion in issue #2587.
First draft, so probably doesn't flow perfectly and will likely contains some errors - always find it better to revisit after a couple of days to clean things up. If you spot anything which could be improved please point it out, no matter how small (or large) a detail!
Couple of thoughts/questions:
- Not sure whether this is being added to the right place. In a sense it builds on from the basics section, but on it's not really exploring a basic part of redux.
- Could do with closing statement and links to further reading.
- Should this new code be added to the example? Could be a useful addition, but then it would break the flow of the doc (since it links through to the code at the start) - maybe …
> Docs(recipes): add configureStore recipe

- docs/recipes/ConfiguringYourStore.md
Should be imported `composeWithDevTools`,  instead of `composeWithDevtools`.
Misspelling appears to compile fine in the console, but the browser returns an error: `TypeError: Cannot read property 'apply' of undefined`
> docs: fix `composeWithDevTools` capitalization

- docs/recipes/UsingObjectSpreadOperator.md
In docs/recipes/UsingObjectSpreadOperator.md
On line 20, to say **recently added** instead of **recent added**.
> Fixed grammatical error

- index.d.ts
When wrapping `createStore()` using typescript, the typescript definition prevents an optional `preloadedState` argument:
```typescript
function myCreateStore<S>(reducer: Reducer<S>, preloadedState?: Redux.DeepPartial<S>) {
return createStore(reducer, preloadedState);
}
```
This will complain that type `undefined` is not assignable to `DeepPartial<S>`. Marking the `preloadedState` argument as optional fixes this problem.
> Mark StoreCreator's preloadedState argument as optional

- docs/recipes/WritingTests.md
We should be more consistent in example code for writing tests.
> Remove unnecessary semicolons from WritingTests.md

- docs/recipes/ConfiguringYourStore.md
It was pointing to the "Basics" section
> Fix the link to "Advanced" from "Recipes/Configuring Your Store" footer

- docs/basics/DataFlow.md
Changing `‘` to `'` for consistency in DataFlow.md.
Per [contributing#doc](https://github.com/reduxjs/redux/blob/master/CONTRIBUTING.md#docs) section, we should use `'`.
> Changing ‘ to ' for consistency in DataFlow.md

- docs/basics/UsageWithReact.md
It's great to provide links to more in-depth material, but what if we made it seem more optional? It might be better to allow the reader to keep their momentum here.
This is loosely related to #2591.
> The Medium article should be optional reading.

- src/createStore.js
- test/createStore.spec.js
This commit adds a check for whether the user is passing several
enhancers to the `createStore` function.
Fixes #3114.
> fix: Throw error if createStore is passed several enhancers

- examples/async/package-lock.json
- examples/async/package.json
- examples/counter/package-lock.json
- examples/counter/package.json
- examples/real-world/package-lock.json
- examples/real-world/package.json
- examples/shopping-cart/package-lock.json
- examples/shopping-cart/package.json
- examples/todomvc/package-lock.json
- examples/todomvc/package.json
- examples/todomvc/src/components/Link.js
- examples/todos-flow/package-lock.json
- examples/todos-flow/package.json
- examples/todos-flow/src/components/Link.js
- examples/todos-flow/src/components/__snapshots__/App.spec.js.snap
- examples/todos-flow/src/components/__snapshots__/Footer.spec.js.snap
- examples/todos-flow/src/components/__snapshots__/Link.spec.js.snap
- examples/todos-flow/src/components/__snapshots__/Todo.spec.js.snap
- examples/todos-flow/src/components/__snapshots__/TodoList.spec.js.snap
- examples/todos-flow/src/containers/__snapshots__/AddTodo.spec.js.snap
- examples/todos-flow/src/containers/__snapshots__/FilterLink.spec.js.snap
- examples/todos-flow/src/containers/__snapshots__/VisibleTodoList.spec.js.snap
- examples/todos-with-undo/package-lock.json
- examples/todos-with-undo/package.json
- examples/todos-with-undo/src/components/Link.js
- examples/todos/package-lock.json
- examples/todos/package.json
- examples/tree-view/package-lock.json
- examples/tree-view/package.json
- examples/tree-view/src/containers/Node.js
This upgrades all examples using `react-scripts` to v2. All examples were tested by hand and are working correctly.
> Switch examples to Babel 7, Jest 23, and Webpack 4

- docs/FAQ.md
Fixes the TOC links under general with the correct anchor tags
Issue: https://github.com/reduxjs/redux/issues/3090
> docs(faq): fix faq toc general anchor links

- docs/introduction/LearningResources.md
[DEV Community](https://dev.to) Community is a burgeoning source of guidance and discussion on software topics, especially web dev. This will be a useful link to point to the official place to discuss Redux matters on the platform.
A few additional links pertaining to [dev.to](https://dev.to)
Traffic stats: https://www.similarweb.com/website/dev.to
Twitter: https://twitter.com/thepracticaldev
Redux tag (as included in PR): https://dev.to/t/redux
Some example Redux posts:
https://dev.to/oathkeeper/learning-redux-and-notes--43ae
https://dev.to/websavi/how-to-code-split-redux-store-to-further-improve-your-apps-performance-4gg9
https://dev.to/saigowthamr/build-your-own-redux-from-scratch-5a4d
https://dev.to/bnorbertjs/async-react-basics-with-redux-thunk--redux-saga-4af7
Happy coding ❤️
> Add dev.to link as a learning resource

- docs/recipes/WritingTests.md
In the [fetch-mock docs](http://www.wheresrhys.co.uk/fetch-mock/#api-lifecyclerestore_reset), restore() is an alias for reset()
Remove reset() since both accomplish the same task
> Update async action creators test: Remove redundant method

- README.md
Old link: CommonJS Webpack docs v1 (not working, redirects to webpack homepage)
New link: CommonJS topic in the webpack wiki
> Update outdated CommonJS link

- examples/todomvc/src/components/MainSection.js
- examples/todomvc/src/components/TodoTextInput.js
get the Warning:
```
index.js:1452 Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. 
This will render a read-only field. 
If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
in input (at MainSection.js:12)
in span (at MainSection.js:11)
in section (at MainSection.js:8)
in MainSection (created by Connect(MainSection))
in Connect(MainSection) (at App.js:8)
in div (at App.js:6)
in App (at src/index.js:13)
in Provider (at src/index.js:12)
```
line 12, input set readOnly
get the Warning: 
```
Warning: Received the string `true` for the boolean attribute `autoFocus`. Although this works, 
it will not work as expected if you pass the string "false". Did you mean autoFocus={true}?
in input (at …
```
> examples/todomvc: fixed two Warning about checkbox set either `onChange` or `readOnly` and input autoFocus

- docs/api/Store.md
The internal links / bookmarks in the _Store Methods_ section on _Store_ page in the docs don't work properly.  This PR is a fix for this problem.
> Fix - docs store page internal links

- examples/real-world/src/containers/UserPage.js
Fix a TypeError exception, raised because wrong argument is passed to a function call.
> Fix a TypeError exception in real-world example

- CONTRIBUTING.md
- README.md
- docs/api/combineReducers.md
- docs/basics/Actions.md
- docs/basics/UsageWithReact.md
- docs/introduction/Examples.md
- docs/recipes/ConfiguringYourStore.md
- docs/recipes/ImplementingUndoHistory.md
- docs/recipes/ServerRendering.md
- docs/recipes/WritingTests.md
This PR adds a language identifier to all the code blocks under `/docs` that were missing one.
There are two cases where a `js` identifier was missing, causing the block not to be highlighted.
Apart from those two, this PR adds a `sh` identifier to all blocks containing shell commands.
In case the latter is not wanted, let me know and I can change this to only add the two missing `js` identifiers.
> docs: Add language identifier to all code blocks

- docs/introduction/LearningResources.md
Just went through the Redux resources page and saw an outdated link from my website. It shows how to use normalizr, but I feel guilty because I really need to update it. 
A better resource for learning Redux in React would be Taming the State in React though :) Would love to get it into the books section.
> Remove outdated Link, Add Redux Book

- docs/introduction/Ecosystem.md
removed... 
**[ReactTraining/react-router-redux](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux)**  
Keep your state in sync with your router
According to their page:  """"Redux users: The react-router-redux package is now deprecated."""""
> -dprctd react-router-redux +connected-react-router

- docs/api/Store.md
The anchor wasn't matching the target element so it wasn't scrolling.
> Fix wrong anchor in Store documentation

- docs/basics/Reducers.md
Removed unnecessary semicolon in the docs [(Basics > Reducers#handling-actions)](https://redux.js.org/basics/reducers#handling-actions)
> Removed unnecessary semicolon

- docs/api/bindActionCreators.md
- src/bindActionCreators.js
Fix typo - object arguments to object properties
Clear words - single function to action creator for bindActionCreators`s first argument
> Fit bindActionCreators docs more clearly

- docs/advanced/UsageWithReactRouter.md
- docs/basics/UsageWithReact.md
- docs/faq/DesignDecisions.md
- docs/faq/ImmutableData.md
- docs/faq/ReactRedux.md
- docs/introduction/Installation.md
- docs/recipes/WritingTests.md
Actual API docs are a little nicer to read than a file in the repository
> More links to docs sites instead of repo markdown

- docs/faq/Performance.md
**Description**
The Performance FAQ's TOS contains a broken anchor link. "Won't calling 'all my reducers' for each action be slow?" currently links to:
https://redux.js.org/faq/performance#wont-calling-all-my-reducers-for-each-action-be-slow
However, with the section title containing an apostrophe, the generated id contains a dash, meaning the link should be:
https://redux.js.org/faq/performance#won-t-calling-all-my-reducers-for-each-action-be-slow
> Documentation: Add dash to handle apostrophe in title

- docs/recipes/UsingImmutableJS.md
You can view the compiled markdown [here](https://github.com/msrose/redux/blob/2ed8ca5b7602fcdac78010079ea2a175ae1847d2/docs/recipes/UsingImmutableJS.md#your-selectors-should-return-immutablejs-objects).
The info on this doc page was really helpful for us standardizing our usage of selectors with Immutable.js at Top Hat, so I just wanted to expand on some of the points already made to afford a bit more clarity. 
We have also been using the suggested HOC for converting Immutable.js props to plain JS objects to avoid polluting our presentational components; we found the same HOC cropping up in various incarnations in our front-end projects, so we've released the NPM package [with-immutable-props-to-js](https://www.npmjs.com/package/with-immutable-props-to-js). Hoping other may find it …
> Expand docs for using Immutable.js with selectors

- docs/recipes/ServerRendering.md
Since React 15, the `data-reactid` attribute is gone: https://reactjs.org/blog/2016/03/07/react-v15-rc1.html
> ServerRendering docs: remove ref to data-react-id

- docs/faq/ReactRedux.md
The link to `connect()` API is not working
https://redux.js.org/faq/react-redux#further-information-4
> Docs: Fix `React Redux API: connect()` link

- website/static/css/custom.css
Note that the "Learning Resources" is off alignment from the left and right columns. There's custom CSS which changes the default top padding which messes with the alignment especially on mobile view:
On mobile view, the header doesn't get hidden behind the navigation.
> Fix documentation container alignment

- docs/api/Store.md
- website/static/css/custom.css
When accessing to docs of API methods such as [`store.dispatch()`](https://redux.js.org/api/store#dispatch), the title gets cover by the navbar, but clicking on the anchor shortcut, gets rendered without problems. This PR adds the class used by the anchor, in order to have the same behavior.
> fix(docs): Fixes navigation for shortcode headings

- docs/introduction/Installation.md
"As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. The other save options still exist and are listed in the documentation for npm install."
https://stackoverflow.com/a/19578808/142358
> Remove --save option as it isn't required anymore

- docs/recipes/CodeSplitting.md
`this.` does not work in this scenario.
Proof: https://codesandbox.io/s/w07qqwlkq5 --> replace store.asyncReducers with this.asyncReducers. In utils/createStore
> (docs) minor correction

- .travis.yml
- src/applyMiddleware.js
- src/bindActionCreators.js
- src/createStore.js
Even though this code has no impact on the overall performance of the application `for in` is faster in modern browsers (https://jsperf.com/object-keys-vs-for-in-with-closure/138). 
I propose this change only as readability improvement.
> Iterate using for in instead of Object.keys and minor fixes

- docs/recipes/UsingObjectSpreadOperator.md
update the Using Object Spread Operator article mentioned in  the official documentation.
According to [@babel/plugin-proposal-object-rest-spread](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread), the plugin's name will be **@babel/plugin-proposal-object-rest-spread** not **transform-object-rest-spread**
> update babel/plugin-proposal-object-rest-spread link and plugin

- .travis.yml
- index.d.ts
Fixes https://github.com/reduxjs/redux/issues/3368
> Fix `DeepPartial` type

- docs/recipes/UsageWithTypescript.md
The comments in the chat action creators imply that `TypeScript infers that this function is returning DeleteMessageAction`, while the returned union type is not defined.
If the return type is not manually linked to the Union Type, I have no idea how the inference based on just the constant should work.
> Fix chat action creators in UsageWithTypescript

- docs/recipes/structuring-reducers/UpdatingNormalizedData.md
Hey guys, this is a [requested](https://stackoverflow.com/questions/55475808/module-descriptors-concept-in-redux-orm/55548296#comment97876038_55548296) update to the state management section describing Redux-ORM. It's actually been outdated since version 0.9 (we're at v0.13.2 now). We also moved the repository to a GitHub organization.
To prevent confusion, I simplified some payload properties and removed the part about "queued updates" which is an implementation detail regarding performance. The paragraph that I added in the end is supposed to make the benefits of managed relationships a bit more obvious.
> Update docs to describe current version of Redux-ORM

- src/createStore.js
`reducer` should wrapped with `[]` just the same as `preloadedState` and `enhancer`
> Add bracket for comments

- index.d.ts
- test/typescript/reducers.ts
This change allows for `combineReducers` to completely infer both the state and action types for its returned reducer.
From experience with large TypeScript projects, it's common to see that the action type is not explicitly specified, which results in `AnyAction` in the resulting reducer type. Unfortunately, this will propagate through the type inference for `createStore` resulting in `dispatch` being very weakly typed. This change alone causes a chain reaction of a more correctly (and strongly) typed project with regards to Redux.
> Infer action types from combineReducers

- test/typescript/tsconfig.json
The entries in `paths` should be arrays. See the [schema](http://json.schemastore.org/tsconfig).
> test(typescript): fix invalid tsconfig.json

- docs/recipes/structuring-reducers/UpdatingNormalizedData.md
inspired by #2950 - I think using "obviously" here can be confusing by assuming a reader knows it's obvious (and why), vs just stating that it's the most common.
> remove "obviously"

- docs/faq/Performance.md
I noticed in the v7 release we added support for the `batch()` API. I know there are docs planned for upcoming releases but thought it could be something to mention in the Performance FAQ. In the section where we talk about batching updates, we still recommend in the FAQ other packages i.e. `redux-batched-actions`, etc. 
I feel it would be good to give users a heads up in this section to take a look if upgrading and using the new `batch()` API would address their needs. I still left text relevant to users who have not upgraded yet though. 
If you feel this is unnecessary or if I can improve the docs in any way, feel free to reject or let me know :) We started using the `batch()` API and it's been great.
> Add docs about `batch()` API to Performance FAQ

- docs/recipes/CodeSplitting.md
The docs have the `keysToRemove` array set to a const but then later in the code try to reassign the variable to another array.
> [DOCS]: Fixing small typo

- website/static/css/custom.css
Resolves https://twitter.com/acemarke/status/1134315647427440642
It does feel weird to have a media rule for both 1023px and 1024px but with 1023px we could observe the wrong color for an instant when resizing the window.
It might be better to enforce the rule on any resolution so it won't break if docusaurus changes the way it handles this?
> Website: keep header searchbar background consistent on mobile

- website/static/css/custom.css
What does this PR do?
---
Fixes #3427
So I've dug a bit more around the header anchor. There are four `<a />`s here: 
The first and the third are not shown because there is no content inside.
The second one, one with class name `.hash-link`, is the anchor for the icon. And the fourth one, one without any class name, is the one for the header.
Here are the two CSS rules involved, both in custom.css:
```css
.post article blockquote a:hover,
.post article blockquote a:focus,
.post article blockquote a:active {
position: relative;
}
```
and 
```css
.post article .hash-link {
position: absolute
}
```
The `.hash-link` has `position: absolute` which give it the desired positioning. It gets broken when the first rule is in action because it has higher CSS specificity.
> fix(docs): Fix header anchor link positioning

- examples/todos-with-undo/src/reducers/todos.js
distinctState() filter, which is deprecated, is now auto applied.
>  remove distinctState() filter from example

- index.d.ts
- test/typescript/reducers.ts
> Revert "Infer action types from combineReducers"

- docs/faq/ReactRedux.md
What does this PR do?
---
Addressing [this tweet](https://twitter.com/acemarke/status/1144126161296875520?s=20), adds an entry explaining the difference between Redux and React's Context API.
> docs: add redux v.s. context difference FAQ entry

- docs/advanced/AsyncActions.md
- docs/advanced/Middleware.md
- docs/advanced/UsageWithReactRouter.md
- docs/api/Store.md
- docs/api/combineReducers.md
- docs/basics/Actions.md
- docs/basics/Reducers.md
- docs/faq/General.md
Currently some blockquotes are broken into several blocks as below. This PR simply fixes it.
Signed-off-by: Luffy Xiao <luffy.xiao@airbnb.com>
> Update docs to improve readability

- docs/api/Store.md
This page has a table of contents *and* a sidebar which I guess is a bit tricky in docusaurus. I put the ###s back to plaintext, which made the sidebar prettier, then switched the ToC to use hashes that those linked to to ensure that that works too.
<3
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/4138357/60469838-bff7fe80-9c23-11e9-9f93-52446bda9b95.png)|![image](https://user-images.githubusercontent.com/4138357/60469859-cab29380-9c23-11e9-87cd-840d262bc3b6.png)|
> docs: fix Store api sidebar links

- docs/recipes/structuring-reducers/PrerequisiteConcepts.md
The original link was to a site that is no longer up. The book is now hosted on a different site, so changed link to that.
> Fix broken link to database design book

- docs/recipes/UsageWithTypescript.md
`ChatActions` is not used in the commented file.
> removing `ChatActions` import line

- docs/basics/Reducers.md
In this code example, SET_VISIBILITY_FILTER is used in a switch case, but it is never imported first. It is imported in the subsequent example code block in the docs. This is confusing, especially for users who aren't familiar with switch statements.
> Add import statement to visibilityFilter example

- docs/faq/Performance.md
- docs/faq/ReactRedux.md
A couple of links in tables of contents were broken.
These were links where the URL fragment in the target was
auto-generated. When that happens, most special characters are removed
from the heading.
When the links in the tables of contents were written, the ones I am
fixing replaced some of the special characters with `-`, instead of
stripping them.
I tested the links on my fork on the [Performance](https://github.com/douglasnaphas/redux/blob/broken-links-quotes-in-headings/docs/faq/Performance.md) and [React Redux](https://github.com/douglasnaphas/redux/blob/broken-links-quotes-in-headings/docs/faq/ReactRedux.md) pages.
These screenshots show that the currently live auto-generated URLs
match what I am changing the links to:
> Fix links to some headings with special chars

- CONTRIBUTING.md
In PR #1874, a mass replacement of angled single quotes ’ with ASCII
single quotes ' was approved. Since then, the docs have contained a
mixture of angled and ASCII single quotes:
```
$ git log -S’ --since="Mon Aug 1 16:45:58 2016 -0400" --pretty=oneline | wc -l
17
```
so it does not make sense to state a rule on them.
> Remove outdated rule on single quotes in docs

- docs/Glossary.md
- docs/Troubleshooting.md
- docs/advanced/AsyncFlow.md
- docs/advanced/Middleware.md
- docs/api/README.md
- docs/api/Store.md
- docs/api/applyMiddleware.md
- docs/api/bindActionCreators.md
- docs/api/createStore.md
- docs/basics/Actions.md
- docs/basics/DataFlow.md
- docs/basics/Store.md
- docs/basics/UsageWithReact.md
- docs/recipes/ReducingBoilerplate.md
- src/createStore.js
All links to [Store methods](https://github.com/reduxjs/redux/blob/master/docs/api/Store.md#store-methods) seem to be outdated.
| before           | after                      |
|------------------|----------------------------|
| #dispatch       | #dispatchaction          |
| #subscribe      | #subscribelistener        |
| #replaceReducer | #replacereducernextreducer |
> docs: fix store methods link

- docs/basics/Reducers.md
A slight improvement to the language, because:
1. "anymore" is not word
1. the second usage is also ambiguous - does it mean "we don't use it fromhereonin" or "we no longer use it"?
> Minor language fix

- index.d.ts
- package.json
- test/typescript/reducers.ts
* Strictly infers state shape and actions from the reducers object map.
* Updated tests and comments to match new strict type inference.
* Tested and working in typescript 2.8.
> #2979 Add strict type inference overload for combineReducers.

- src/combineReducers.js
- test/combineReducers.spec.js
State doesn't update when replaceReducers is called with combineReducers and one of the reducers passed to it is removed.(https://github.com/reduxjs/redux/issues/3488)
> Fixed combineReducers changeDetection logic(#3488)

- test/applyMiddleware.spec.ts
This PR converts the `applyMiddleware` test to typescript.
In the interest of simplicity, there is one major compromise: the example based on `thunk` does not pull in all of the massive complexity of that type. Instead, it just does a double typecast to force the value we already know works. If this feels too brittle, it is not trivial, but totally doable to fix this.
> migrate applyMiddleware test to typescript

- test/bindActionCreators.spec.ts
This test was easy to migrate, all of the failures involved testing against type mis-matches that can only occur in javascript.
> migrate bindActionCreators test to typescript

- test/compose.spec.ts
This one was relatively simple, and required no changes to the existing types or source code
> convert the compose test to typescript

- index.d.ts
- src/createStore.js
- test/replaceReducers.spec.ts
Currently, the `replaceReducer` function assumes that the reducer state stays in the same shape. This does not make sense, as the purpose of `replaceReducer` is to change the store state.
However, typescript types are static, and replaceReducer changes the type at run-time.
To solve this issue, we either need to cast the existing store to the new store type, or transform the store.
As it turns out, a simple solution is to modify the signature for `replaceReducer` to return the existing store, and this gives us the ability to typecast to the new reducer type in a graceful way.
With this change, the `combineReducers` test passes when converted to typescript with minimal changes.
This *may* also fix #3482
> fix replaceReducer type

- index.d.ts
- test/combineReducers.spec.ts
This PR converts the `combineReducers` test to typescript. The changes are mostly typing of parameters, but also requires 2 major additions to the typings. The first is export of `__DO_NOT_USE__ActionTypes` and the second is a change to the definition of `replaceReducers` which also requires a small change to `createStore`
The change to `createStore` is duplicated in PR #3507, which is against master, whereas this PR is against `ts-conversion`
> convert combineReducers test to typescript

- package.json
- test/createStore.spec.ts
Funny story: the package.json regex for jest did not select `.ts` tests. So this PR does 2 things:
enable the ts tests, and convert `createStore` test to typescript
> convert the createStore test to typescript - and run the tests

- test/typescript/replaceReducer.ts
There was some concern that the fix for #3482 in the `ts-conversion` branch does not strongly type the reducer returned from `replaceReducer`.
This PR adds a test to prove it does.
> add a new test to verify replaceReducer typings work

- .gitignore
- package-lock.json
- package.json
- rollup.config.js
It turns out that even with the `nodeResolve` fixes, we still need the `typescript` plugin to build with rollup. This PR fixes that
> fix typescript config for rollup

- test/replaceReducers.spec.ts
The `replaceReducer` new reducer in the test was only returning `5`, which is almost certainly an error in the real world. This PR changes the test so that it returns a more realistic object, removing the warning
> fix warning in replaceReducer test

- src/bindActionCreators.ts
This converts `bindActionCreators.js` to typescript, and supplants #3520. It is a step on the path to #3500
> convert bindActionCreators to typescript

- index.d.ts
- src/applyMiddleware.ts
This converts `applyMiddleware` to typescript. In order to do this, there is a bug in the type definition of `Dispatch` that needs to be fixed to reflect the changes introduced in the fix for #2501.
In addition, this conversion makes more explicit the reducer passed to `createStore` and the action passed to `dispatch`. This supplants part of #3520 and is a step on the path to #3500
> Convert applyMiddleware.js to typescript

- src/compose.ts
This converts `compose.js` to typescript, supplanting #3520 and a step on the path to #3500
> convert compose to typescript

- src/createStore.ts
supplants #3520, a step on the path to #3500
> convert createStore to typescript

- src/combineReducers.ts
This converts `combineReducers` to typescript. It supplants #3520 and is a step on the path to #3500
> convert combineReducers to typescript

- src/combineReducers.ts
a step on the path to #3500 
This copies the types for `combineReducers` verbatim from `index.d.ts` into `combineReducers.ts`
> merge type definitions from index.d.ts into combineReducers

- src/index.ts
- test/typescript/tsconfig.json
- tsconfig.json
This is the last of the first step for #3500 
woot!
> export types, prepare TS config for migrating files

- src/types/actions.ts
- src/types/store.ts
Extract all things action types from `index.d.ts`
Note: this PR also fixes an oversight in the extraction of store-related types, which is the declaration of observable in `types/store.ts`
> extract action types from index.d.ts

- src/combineReducers.ts
the `default` is all-important or overloads don't match up properly
> fix combineReducers overload exports, and import of Reducer type

- test/typescript/enhancers.ts
This is a subtle problem. If we import `PreloadedState` from `../../index`, and `createStore` from `redux`, we end up with different versions of the declared `$CombinedState` symbol, and so the types never match.
Also, we should be consistent about always loading the types from our aliased `redux`
> fix import inside enhancers typescript test

- src/applyMiddleware.ts
- src/compose.ts
Because `applyMiddleware` relies upon `compose`, these two need to be committed at the same time. The comment changes in `compose.ts` are because of subtle differences between the comments in `index.d.ts` and `compose.ts`. Where there was a conflict I chose the `index.d.ts` version
> add overloads to compose.ts and applyMiddleware.ts

- src/bindActionCreators.ts
this adds overloads to `bindActionCreators` and fixes the import
> fixes to bindActionCreators overloads

- index.d.ts
- src/applyMiddleware.ts
- src/createStore.ts
- src/index.ts
- src/types/store.ts
- test/typescript/enhancers.ts
- test/typescript/store.ts
This fixes #3482 (replaceReducer typing fails for store enhancers that update the state or extend the store) without requiring any change to the use of existing types (fully typing backwards compatible).
It adds 2 new templates to the generic for defining a `Store`, the extension to state, and the extension to the store definition.
By adding these 2 template parameters, we can mix them with the new reducer state from `replaceReducer`:
```ts
replaceReducer<NewState = S, NewActions extends A = A>(
nextReducer: Reducer<NewState, NewActions>
): Store<NewState & StateExt, NewActions, StateExt, Ext> & Ext
```
and return a store that has the correct typings for both state and the store extension.
To enable this functionality for store enhancers, it requires these 3 related changes:
1. the …
> fix replaceReducer with a store enhancer

- docs/introduction/Installation.md
The current link to Webpack's CommonJS no longer resolves.
> Fix broken link to CommonJS.

- test/createStore.spec.ts
- test/helpers/reducers.ts
not so important, but I was running some tests and saw these warnings.
- for some tests, like for `dispatchInMiddle`, I saw some helpers unreachable lines (cause exceptions were being tested) and led to these uncovered warning.
- another helper, `id`, was function with an unused branch, that was an unused default value for a param
- and finally, there was an uncovered function on store `observable` return
(there's still an uncovered line for a warning shown on redux.js bundle)
> increase test cov of reducers test helpers and observable return

- docs/introduction/LearningResources.md
I thought one of the tutorial links was broken, but turns out it had been moved.
Old link: https://www.pshrmn.com/tutorials/react/redux/ 
New: https://github.com/pshrmn/notes/blob/master/redux/redux.md 
Issue: https://github.com/reduxjs/redux/issues/3562
> fix: update tutorial link

- docs/introduction/LearningResources.md
Since storify link is broken and twitter thread is not relevant anymore, removed both links and adjusted the description.
> 3605 Removing broken storify link from docs

- docs/introduction/GettingStarted.md
- docs/redux-toolkit/overview.md
- website/package-lock.json
- website/package.json
- website/sidebars.json
This PR adds a new "Redux Toolkit" top-level category to the docs, with an "Overview" page that:
- Describes what Redux Toolkit is and why you should use it
- Describes the functions that are included
- Links to the existing Redux Toolkit individual docs pages
Related issue: #3614 
I also bumped Docusaurus to the latest v1 version along the way.
> Add RTK Overview page

- .github/PULL_REQUEST_TEMPLATE.md
- docs/style-guide/style-guide.md
- website/sidebars.json
- website/static/css/custom.css
---
---
Adds a new page
- #3601
- **Page**: Overview
Good question. It's somewhere between an "explanation" and a "reference".
All users who understand the basics and are looking for best practices.
General knowledge of how Redux works; terms like "action creator", "reducer", "side effects", etc.
Readers will know what the recommended approaches are for writing good Redux code.
A bit hard to narrow it down given the length, but I'd say the first few "Essential" priority items.
> [Docs Rewrite] Add Style Guide docs page

- docs/style-guide/style-guide.md
---
---
- **Section**:  Style Guide
- **Page**:  Style Guide
The word "automatically" is used twice in a sentence.
Removes one of the "automatically"s.
> Remove superfluous "automatically" from style guide

- package-lock.json
- package.json
- src/createStore.ts
- src/types/store.ts
- src/utils/symbol-observable.ts
- test/createStore.spec.ts
Partialy fixes #3567 
Removed `symbol-observable` from `package.json` and added a polifyll to `/src/utils/symbol-observable`, similar to RxJs implementation.
_Sorry for the mess, I do not know what is wrong with my pc and why it keeps messing up the formatting._
> Dropping symbol-observable dependency, realizing internal implementation

- src/utils/actionTypes.ts
- src/utils/symbol-observable.ts
Similar to what got added to react-redux - it lets minifiers to remove those 3 small calls when `redux` stays unused in the bundle.
> Add PURE annotations

- docs/recipes/UsageWithTypescript.md
- test/typescript/enhancers.ts
https://redux.js.org/recipes/usage-with-typescript#type-checking-reducer
`SystemActions` import is not required, nor is it in `types.ts`.
Remove `SystemActions` from `import`
> Docs: remove bad import

- rollup.config.js
Most likely when you have migrated to TS you have missed that Babel has actually stopped transpiling files - because by default it only operates on .js, .jsx, .es6, .es, .mjs extensions and .ts is not one of them.
So this fixes dist files from being es6+ to es5.
> Fix rollup-plugin-babel usage

- website/core/Footer.js
Netlify has updated their OSS plan to require attribution: https://www.netlify.com/legal/open-source-policy/
> Add Netlify Badge to Docs

- website/docs/style-guide/style-guide.md
---
name: Documentation Fix
---
- No, but I can create an issue if you need me to
- **Section**: name-state-slices-based-on-the-stored-data
- **Page**: style-guide
There was a duplicated section
Removes the duplicated section
> Remove duplicated section in style guide

- README.md
---
---
^^ This content was auto populated.
README
The current API reference link doesn't work.
Updates the link to one that works, but I don't know if the old is supposed to and something else is wrong (not doing a redirect or loading an index it should be).
> Fix API reference link

- CONTRIBUTING.md
- website/docs/recipes/structuring-reducers/RefactoringReducersExample.md
Fixed Reducing Boilerplate link in Recipes > Structuring Reducers > Refactoring Reducers Example
Fixed links to the examples page and a link to the docs in contributing.md
> Fixed broken links in the docs and in contributing.md

- README.md
---
---
- N/A
/README.md
Link to the "Advanced" docs section is 404.
Previously this link went to `/advanced` which no longer appears to exist.
Link to the first page in the advanced section.
> Fix broken "Advanced" docs link

- website/src/css/custom.css
---
name: "\U0001F41B Bug fix or new feature"
---
This PR adjusts the `navbar__items` flex declaration to prevent the items from wrapping.
`flex: 1 0 0` will create equal width items, causing the `navbar__items--right` to not have enough space. Adjusting to `flex: 1 1 auto` will allow the items to fill their available space.
**BEFORE**
**AFTER**
> Fix documentation navigation items from wrapping

- docs/recipes/structuring-reducers/ImmutableUpdatePatterns.md
---
---
Opened this purely from GitHub, can follow up if this there's support for making this change.
- **Section**: Structuring Reducers
- **Page**: Immutable Update Patterns
This is a nit, but this is my go-to page to direct folks at for examples of immutable updates (regardless of whether they're using Redux). As it stands right now, the first 2 things they see are broken code, which isn't immediately apparent from a quick skim. This seems likely to introduce some confusion.
It moves the correct example so it's the first thing on the page. Since the other examples don't have subtly-broken variations, I think this is a minimal change that will have a slight positive impact.
> Move correct deep state update example to the top

- website/src/css/custom.css
- no need; it’s a tiny change
- N/A – I see no lint rules for docs CSS
- **Page**: Style Guide
The cursor turns to `pointer` when hovering over non-clickable parts of `details` elements.
In the CSS, make the cursor turn to `pointer` only when hovering over the `summary` element, which is the clickable part.
> Docs CSS fix: show pointer only on clickable part of details

- docs/recipes/UsageWithTypescript.md
Currently, the docs suggest `null` as type for the `extraArgument` generic argument of `ThunkAction`.
This only works if the `ThunkMiddleware` is invoked with `null` as `extraArgument` as well. The default value for `ThunkMiddleware` is `unknown` though, making these thunks incompatible with the default-typed `ThunkMiddleware`.
This change suggests to use `unknown` instead, which would work with Middlewares typed for any type of `extraArgument`.
> Docs update: recommend `unknown` instead of `null` as ThunkAction extraArgument type

- website/docusaurus.config.js
Currently:
With this change:
(The "end-year" is dynamic, using the same code that Docusaurus uses on their own site.)
> Use a proper copyright symbol, en-dash, and current year in the footer

- README.md
- docs/advanced/UsageWithReactRouter.md
- docs/basics/UsageWithReact.md
- docs/introduction/GettingStarted.md
- docs/recipes/ConfiguringYourStore.md
- docs/recipes/ImplementingUndoHistory.md
- docs/recipes/ServerRendering.md
- docs/redux-toolkit/overview.md
---
name: "Documentation Fix"
---
- https://github.com/reduxjs/redux/pull/3357
Multiple sections and pages which have `npm install --save`
- **Section**:
- **Page**:
Follow up to https://github.com/reduxjs/redux/pull/3357 
--save is not required for `npm install`
Brings more consistency.
> Remove redundant save options for npm install

- docs/basics/UsageWithReact.md
- **Section**:
Basic Tutorial
- **Page**:
Usage with React > [`components/TodoList.js`](https://redux.js.org/basics/usage-with-react#componentstodolistjs)
When todo item clicking, wrong record is processed.
Use `todo.id` instead of `index`,  like as "[Example: Todo List](https://redux.js.org/basics/example#componentstodolistjs)" page, 01dc17e0821.
> fix click bug like as 01dc17e0821

- docs/recipes/WritingTests.md
---
---
- **Page**: Writing Tests
It seems to link to [old documentation](https://github.com/reduxjs/react-redux/blob/eae14cc92b79dfbc4f37131d31698b3446a9857d/website/versioned_docs/version-5.x/api/api.md).
Link to the latest documentation.
> docs: fix link

- docs/recipes/UsageWithTypescript.md
- **Section**: recipes
- **Page**: UsageWithTypescript
The example was incorrect as the type of `createAction` is `number` but the payload is of type `string`.
Payload is changed to be a number :-)
> docs: fix syntax error for createAction with TypeScript

- website/docusaurus.config.js
- website/src/css/custom.css
- website/src/pages/styles.module.css
---
name: "Add Dark Mode"
about: Adding variables and changing Docusaurus config to enable dark mode.
---
- #3762
Viewing redux docs at 1am in light mode hurts my eyes.
- Modifies the docusaurus config to enable the classic theme's built-in dark mode.
- Adds new dark-mode-specific variable overrides to the custom Docusaurus css.
- Changes the 'recommendation' colors from hard-coded hex values to some color variables provided by Docusaurus.
- Fixes a css bug with the front page to correctly style the Feature svgs with the base font color (was previously typoed to an incorrect variable name and rendered as #000).
> [Docs] add dark mode variables (issue #3762)

- package-lock.json
- package.json
- src/types/store.ts
- test/typescript.spec.ts
---
name: "Re-enable TypeScript tests"
about: Testing is important
---
Internal change.
See https://github.com/reduxjs/redux/issues/3500#issuecomment-542363238 and following. I tried out `tsd`, but I did not like it as much. The `expect()` method syntax made it more cumbersome to assert in some scenarios. It also wasn't very well documented. I had to read the source code to figure out how to use it. So, I think sticking with `typings-tester` is preferable for now.
Note, I also needed to add an import in `types\store.ts` in order to get the global `Symbol.observable` definition working in the type outputs.
- No, this is an internal change.
Types can break.
The ability to test types.
Re-enables types testing.
> Re-enable TypeScript tests

- docs/basics/UsageWithReact.md
- **Section**: Basic Tutorial
- **Page**: Usage With React 
`Link` component should return `span` with no `onClick` listeners in case if it's **inactive**. In case if it's **active** it should return an `a` with `onClick` listener
It's fixing the code
Notes: in *Basic Tutorial* -> *Example: Todo List* `List` implementation is a little bit different and doesn't suffer from this bug
> [Docs] fix typo in code example of Usage With React section

- docs/recipes/structuring-reducers/UpdatingNormalizedData.md
Instead of only: _"Adding comments to a post"_ we actually describe how to Add/Update (-can be done with both: Simple Merging & Slice Reducer Composition solutions) or Delete (-which can be done with Slice Reducer Composition solution only-). So we should rather say: _"We'll use the example of handling mutations for Comments on a Post"_
Instead of: _"we need to do a deep recursive merge, not just a shallow copy"_, which is not correct because we don't have to, if we don't plan to have update actions with only partial items, we should rather say:  _"we can use deep recursive merge, not just a shallow copy, to allow for actions with partial items to update stored items."_
Click the "Preview" tab above, …
> Clearify merge approach example for updating normalized data

- README.md
---
---
- README.md
"Introduction" link was page not found.
Update link to Introduction/getting-started
> Fix "Introduction" link of README.md

- docs/recipes/WritingTests.md
---
name: "\U0001F4DD Documentation Fix - Formatting problem with WritingTests"
about: Format the WritingTests page again.
---
- **WritingTests**:
Linting problem.
I ran `yarn:format` again.
> docs: Fix formatting for WritingTests

- docs/basics/UsageWithReact.md
The `Link.js` in 
https://github.com/reduxjs/redux/blob/master/docs/basics/ExampleTodoList.md#componentslinkjs
and 
https://github.com/reduxjs/redux/blob/master/docs/basics/UsageWithReact.md#componentslinkjs
is not consistent, moreover in latter, the logic is not correct:
should be:
```js
if (active) {
return <span>{children}</span>
}
```
not:
```js
if (!active) {
return <span>{children}</span>
}
```
> Make the script snippet of basic example consistent

- docs/recipes/WritingTests.md
---
---
- **Page**: Writing Tests
The word "wheter" is used, but this seems to be a mistake.
It correct the word "wheter" to "whether".
> [Docs] fix typo on Writing Tests page

- docs/tutorials/essentials/part-1-overview-concepts.md
---
---
Resolves #3809 
- #3809 
- **Section**: Tutorials > Redux Essentials
- **Page**: Redux Overview and Concepts
- **URL**: https://redux.js.org/tutorials/essentials/part-1-overview-concepts#redux-application-data-flow
The img src link to `ReduxDataFlowDiagram.gif` is broken.
Point to `https://redux.js.org/img/tutorials/essentials/ReduxDataFlowDiagram.gif`
> Broken image src link to ReduxDataFlowDiagram.gif

- src/combineReducers.ts
- src/types/reducers.ts
Fixes a bug.
It fixes a typing issue I and some other folks have with the `combineReducers` function: https://github.com/reduxjs/redux/issues/2709
- https://github.com/reduxjs/redux/issues/2709 (it is closed, but many people are still affected)
Unfortunately, I failed to create a simple reproduction example. Still, it happens that TypeScript would fail to infer the proper generic type to `combineReducers` function. In my case, I'm doing something like this:
```ts
interface FooState {…}
interface AppAction extends Redux.Action<string> {}
interface FooAction0 extends AppAction {…}
interface FooAction1 extends AppAction {…}
type FooActions = FooAction0 | FooAction1;
function fooReducer(state: FooState, action: FooActions): FooState {
return state;
}
// Type error:
// Argument of type …
```
> Fix combineReducers typings.

- docs/tutorials/essentials/part-4-using-data.md
---
name: "Fix error in Redux Essentials tutorial"
about: Fixes a type error in the Redux Essentials tutorial
---
This PR fixes a bug in the Redux Essentials Tutorial, fixing issue #3812.
New users who go through the Redux Essentials tutorial will have code that might not work as expected if this fix is not added.
- See #3812.
See above.
When the user visits the route `/posts/1` or `/posts/2`, the not found screen appears.
The post for id `1` or id `2` should display.
This PR adds a `.toString()` call in a comparison function to fix a type error where the selector was comparing an integer and a string (which will always return false).
> Fix type error in Redux Essentials.

- src/applyMiddleware.ts
---
name: "Tighten applyMiddleware types"
about: More correctly types applyMiddleware
---
Fixes types
The `applyMiddleware` enhancer should not be allowed to accept any arguments, since it is only guaranteed to accept `preloadedState?` as its second argument.
Also the `createStore` parameter should not be `StoreCreator` since it doesn't allow for enhancers. It should match [the parameter type for `StoreEnhancor`](https://github.com/reduxjs/redux/blob/master/src/types/store.ts#L259-L261).
- Simple enough that it probably doesn't need an issue.
It's implied that more than 2 arguments are accepted by this enhancer, when it should it only be called with 2 arguments.
TypeScript should produce an error if trying to pass more than the two defined arguments.
It tightens the arguments' types.
> Tighten applyMiddleware types

- docs/Glossary.md
- src/types/actions.ts
- test/typescript/actionCreators.ts
Following up https://github.com/reduxjs/redux/pull/3541#discussion_r437355966
We are allowing Action creators to be typed by declaring their return type as well as the argument type so function calls keep the expected parameter types.
---
name: "allow type-setting args on ActionCreator"
about: improving type declarations on Redux
---
It sort of adds a new feature, but it's opt-in for the type usage defaulting to the same as the previous behaviour. 
Allow developers to use Redux provided typings in order to implement ActionCreators
> refactor(types/actions): allow type-setting args on ActionCreator

- docs/tutorials/essentials/part-3-data-flow.md
- docs/tutorials/essentials/part-4-using-data.md
---
name: "Fix type error in Redux Essentials"
about: Update documentation content as per #3812 
---
- #3812 
- **Showing Single Posts**:
- **Redux Essentials, Part 4: Using Redux Data**:
This fixes a type error in the documentation by updating the IDs in the initial store data to be strings, not numbers. This removes the need for `.toString()` methods.
Removes the `.toString()` method from Part 4 of the tutorial and updated the initial store data in Part 3 of the tutorial to use strings for IDs.
> Fix type error in Redux Essentials

- src/types/store.ts
- test/typescript/store.ts
This is the same as #3805, except it's targeting master instead of 4.x.
> Only apply mapped types to un-branded types

- docs/tutorials/essentials/part-4-using-data.md
- **Page**: Redux Essentials, Part 4: Using Redux Data
The line 482 doesn't have the highlight. For people who are writing code manually maybe they don't notice that they need to add that line.
Add: **// highlight-next-line**
> Add hightlight to Tutorials/Using Redux Data

- docs/tutorials/essentials/part-1-overview-concepts.md
---
---
- https://github.com/reduxjs/redux/issues/3828
- **Section**: tutorials
- **Page**: overview-concepts
`const obj1 =` in the "In order to update values immutably, your code must make copies of existing objects/arrays, and then modify the copies" section should be `const obj =` as it is referenced below it as just `obj`
change `const obj1` = to `const obj =`
> docs: overview-concepts obj reference

- website/src/css/custom.css
---
name: Bug fix\
about: Fixing a styling problem with Redux website
---
Fix a bug. Resolves #3839
Without this PR the navbar items will wrap between 997 and 1157px.
- Resolves #3839
~~[ ] Have the docs been updated to match the changes in the PR?~~
~~[ ] Have the tests been updated to match the changes in the PR?~~
Website navbar overflows between 997 and 1157px. Can be viewed on any browser.
Navbar items shouldn't wrap if this behaviour breaks layout and impedes user interaction. 
PR will modify the `flex-wrap` rule on the navbar to keep items on one line.
> Fix navbar wrapping between 997 and 1157px

- docs/tutorials/essentials/part-4-using-data.md
---
---
-  https://github.com/reduxjs/redux/issues/3841
- **Section**: Editing Posts > Creating an Edit Post Form
- **Page**: Redux Essentials, Part 4: Using Redux Data
- **Listing**: `features/post/SinglePostPage.js`
Missing import of `Link` from `react-router-dom`
Adds the import to the code listing
> Add missing `Link` import from `react-router-dom`

- docs/tutorials/essentials/part-3-data-flow.md
---
---
- no
- yes: npm run format:check
- **Section**: Showing the Posts List
- **Page**: part-3-data-flow
- **code listing**:  features/posts/PostsList.js
Missing `key` for `<article>` inside of `map()`
Add the key
> added key prop to <article> inside of  map()

- docs/tutorials/essentials/part-4-using-data.md
---
---
- no
- yes
- **Section**: Creating an Edit Post Form
- **Page**: part-4-using-data.md
Minor grammar / typo.
Change the word 'uses' to 'use'.
> grammer uses should be use.

- docs/tutorials/essentials/part-5-async-logic.md
---
---
- no
- yes
- **Section**: Reducers and Loading Actions
- **Page**: part-5-async-logic.md
Not sure but looks like the section titled "Reducers and Loading Actions" should be a h3 but is formatted as a h4.
Changed 
to
> changed heading from h4 to h3

- docs/tutorials/essentials/part-6-performance-normalization.md
---
---
- Resolves #3864
- **Section**: #adding-notifications
- **Page**: /tutorials/essentials/part-6-performance-normalization
1. Adding the Notifications List
Omitted step about adding NotificationsList route to App.js. Without this, we can't navigate to the Notifications tab.
2. Showing New Notifications
While briefly mentioned, we don't show the changes to Navbar.js needed to show the counter for when we have new notifications. I think this should be covered as the next section on Investigating Render Behavior uses that counter as the example.
1. Add mention and snippet for the changes to App.js
2. Add mention and snippet for the Notifications counter in the Navbar
> Docs: Missing information under "Adding Notifications" section

- docs/faq/CodeStructure.md
---
---
- **Section**: Redux FAQ
- **Page**: Code Structure
It's saying the opposite.
> Fix a typo in Code Structure doc

- docs/tutorials/essentials/part-1-overview-concepts.md
---
---
Updates an existing page.
- **Section**: Essentials
- **Page**: 1
I think there should be more emphasis on the correspondence with the familiar event loop to mitigate the terminology learning curve.
They assume a newcomer to Redux, which I believe is already the target audience for this page.
> Master event loop correspondence

- .github/PULL_REQUEST_TEMPLATE/bugfix.md
- .github/PULL_REQUEST_TEMPLATE/documentation-edit.md
- .github/PULL_REQUEST_TEMPLATE/documentation-new.md
When creating a PR from a template, the emoji-unicode displayed as a plain text.
Changing to "markdown emoji markup" fixes this.
> [Docs] fix PR-template emojis

- docs/advanced/AsyncActions.md
Remove this note: https://redux.js.org/advanced/async-actions#note-on-fetch
Obsolete and irrelevant for redux tutorial.
> [Docs - Advanced - Async Actions] remove note about fetch

- docs/tutorials/essentials/part-2-app-structure.md
The tutorial currently says to select the last "counter/increment" entry however the tutorial talks about and shows the last "counter/incrementByAmount" entry as seen directly below the changed line.
> Small fix to tutorials/essentials/part-2-app-structure

- docs/recipes/UsageWithTypescript.md
---
---
It updates an existing page.
- **Page**: Usage With TypeScript
It was pointed out in a Reactiflux conversation last night that the TypeScript
examples provided by Redux currently do not demonstrate how to type a middleware
function. This patch adds a brief section to the docs that shows how to define a
typed middleware.
This recipe assumes an entry-level knowledge of Redux and TypeScript and the new example aims to remain in line with these expectations.
> docs: Add an example of type checking a middleware function

- docs/tutorials/essentials/part-5-async-logic.md
---
---
- **Section**: Async Logic and Data Fetching
- **Page**: Checking Thunk Results in Components
Naming of function being replaced is inaccurate.
Correctly names function to be replaced with thunk.
> Fix naming when thunk-ifying AddPostForm.js.

- README.md
- docs/introduction/GettingStarted.md
- **Section**:
- **Page**:
Old Reactiflux invite links lead to a broken page.
Using the main invite linke takes new members to the welcome channel. See also reduxjs/redux-toolkit#768
> Use main Reactiflux invite

- src/types/reducers.ts
Explicit type argument any can be removed in "src/types/reducers.ts".
> refactor: Explicit type argument any can be removed.

- docs/tutorials/fundamentals/part-1-overview.md
- docs/understanding/history-and-design/middleware.md
- website/sidebars.js
---
---
New-ish, sorta!  Same old "Middleware" page we just removed, but in a new location.
- #3595
- **Section**: "Understanding Redux"
- **Page**: "Middleware"
> [Docs Rewrite] Re-add "Middleware" page in "Understanding Redux"

- docs/recipes/MigratingToRedux.md
- docs/recipes/Troubleshooting.md
Easy Navigation and easy reading for others 
(Fix broken url in MigratingToRedux.md and Troubleshooting.md)
> docs: Fix broken url in docs

- netlify.toml
Hi, while I was preparing a Japanese translation of the Redux docs using the fork-based approach, I noticed that Netlify refuses to rebuild and deploy the forked site even after I pushed some translated docs under `/docs`. The deploy log says:
```
12:27:22 PM: No changes detected in base directory. Returning early from build.
12:27:22 PM: Failed during stage 'checking build content for changes': Canceled build due to no content change
```
And this is due to [the change Netlify made in October 2019](https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds):
> For sites connected to a Git repo after October 3rd, 2019, Netlify tries to determine if there are any changes in the site's base directory by comparing the last known version of the files within that …
> Always rebuild docs on Netlify

- docs/tutorials/fundamentals/part-5-ui-and-react.md
---
---
-https://github.com/reduxjs/redux/issues/3933
- **Section**: Redux Fundamentals/UI and React
- **Page**: [UI and React](https://redux.js.org/tutorials/fundamentals/part-5-ui-react)
There's a missing end-parenthesis, and the undefined`handleSubmit` is being called, whereas handleKeyDown has been declared.
The ones mentioned above :smile: ☝️
> docs: add mising end-parenthesis, use the right function

- docs/introduction/Ecosystem.md
---
name: :book: Updated Documentation Content
about: Update Ecosystem.md content
---
The PR update the ecosystem.md section corresponding to the introduction page.
- https://github.com/reduxjs/redux/issues/3941
- **Section**: Ecosystem
- **Page**: Introduction
Remove links to github repositories that are deprecated/archived.
> remove deprecated and archived repositories from ecosystem.md

- docs/tutorials/essentials/part-5-async-logic.md
---
---
- **Section**: Fetching Data with createAsyncThunk
- **Page**: Redux Essentials, Part 5: Async Logic and Data Fetching
The missed opening quote in action name
Added missed opening quote
> Add missed quote

- docs/recipes/UsageWithTypescript.md
---
---
- [issue 3972](https://github.com/reduxjs/redux/issues/3972)
- **Page**: Usage With TypeScript
In the paragraph [Usage with Redux Thunk](https://redux.js.org/recipes/usage-with-typescript#usage-with-redux-thunk), the concept of thunk is wrongly explained.
> A thunk is a function that returns another function that takes parameters dispatch and getState.
This definition corresponds to a **thunk action creator** but not to a thunk.
Explain correctly what a thunk is.
> [Docs: Rephrase] Explain correctly what a thunk is

- README.md
- docs/introduction/GettingStarted.md
- website/docusaurus.config.js
---
---
- **Page**: Getting Started with Redux
Links go to Reactiflux's #welcome channel which isn't specifically for Redux
Link directly to #redux like other repositories in the organization
> Link directly to #redux on Reactiflux

- docs/recipes/structuring-reducers/NormalizingStateShape.md
---
about: Fixed typo in id
---
- **Section**: Recipes/Structuring reducers
- **Page**: Normalizing State Shape
There was a typo (`commment4`) in one of the examples.
Based on logic of example, a typo was corrected for the corresponding `id`
> Fix id in example

- README.md
Fixing link to the WordPress Redux site in readme.
---
---
- **Section**: Intro
- **Page**: Top of first page
Outdated/broken link.
Updates readme with correct link.
> Fixing link to WP redux site

- docs/tutorials/fundamentals/part-7-standard-patterns.md
- i don't know
- no
- **Section**: Memoizing Selectors with `createSelector`
- **Page**: [Standard Redux Patterns](https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#memoizing-selectors-with-createselector)
Missing import
adds the import
> [Docs] Add a missing import

- docs/recipes/ImplementingUndoHistory.md
- No
- **Page**: Implementing Undo History
distinctState() has been deprecated in the [redux-undo](https://github.com/omnidan/redux-undo) library used with this example 
Removes the distinctState in the code example, and removes the sentence relating to distinctState.
> docs: remove distinctState from implementing undo history recipe

- docs/tutorials/fundamentals/part-4-store.md
Corrected a syntax error on the todosSlice reducer.
---
---
- **Page**: part-4-store
The example for the unit-testing of the reducer did not have the proper syntax and was giving the following error
`Parsing error: Binding invalid left-hand side in function parameter list` 
I corrected the syntax to the proper one. Really minor fix.
> Update test example on todosSlice reducer

- docs/introduction/LearningResources.md
No 
- **Page**: LearningResources
The link for a specific redux tutorial is not updated. It directs to a page that later asks the users to go to the new tutorial page. It would be better if the new link is added to save time and be on the safer side (just in case the older link is closed by the author).
No, they do not change any assumptions.
> Update egghead links in Learning Resources

- docs/introduction/Ecosystem.md
- docs/recipes/CodeSplitting.md
---
---
Update existing pages
- No existing issue.  Happy to create one if you want?
- **Introduction**:
- **Ecosystem**:
- **Recipes**:
- **Code Splitting**:
There are references to some (of my) libraries that have recently been deprecated and archived:
ioof-holdings/redux-subspace#546
ioof-holdings/redux-dynostore#484
Removing them will help users not to choose an unmaintained option.
No.
> [Docs] Remove references to deprecated libraries in docs

- index.d.ts
---
name: Declare EmptyObject interface to wrap $CombinedState
about: Adding interface for $CombinedState appeases latest version of Typescript, allows exporting result of `combineReducers`
---
Fix a bug with lastest version of Typescript
No changes to exports are included, but the internal change from type->interface allows Typescript to correctly reference/export usage of `$CombinedState`
- closes https://github.com/reduxjs/redux/issues/4030
- Previous PR, different attempt at solution https://github.com/reduxjs/redux/pull/4026
None, just maintains support of typescript with latest 4.2.x releases
None
Upgrade to typescript v2.4.2
Create a file `example.ts` with the following content:
```
import { combineReducers, $CombinedState } from 'redux';
export default combineReducers({})
```
make …
> fix: Declare "EmptyObject" interface to wrap $CombinedState

- docs/tutorials/fundamentals/part-5-ui-and-react.md
Related to Redux Fundamentals Tutorial - Part 5, UI & React. Previously
the `handleKeyDown` event handler was evaluating key press values using
`e.which`, which is deprecated. Updated to `e.key`. [This property has
wide browser
support](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#browser_compatibility)
---
---
- [√ ] Is there an existing issue for this PR?
- [Issue](https://github.com/reduxjs/redux/issues/4040)
- **Section**:  [Redux Fundamentals, Part 5 : UI & React](https://redux.js.org/tutorials/fundamentals/part-5-ui-react#redux-fundamentals-part-5-ui-and-react)
- **Page**:  [Dispatching Actions with useDispatch()](https://redux.js.org/tutorials/fundamentals/part-5-ui-react#dispatchin …
> Update key event property - Closes Issue #4040

- docs/recipes/UsageWithTypescript.md
- docs/style-guide/style-guide.md
---
---
Updates the "Usage with TypeScript" page
- #4025
- **Page**: Usage with TypeScript
- Dropped legacy section that showed use of action type unions andhand-written action creators
- Copied TS quick start section from RTK docs
- Added "what you'll learn / prerequisites" boxes
- Added additional details for typing reducers / thunks / middleware
- Removed now-duplicate RTK usage info
- Added additional RTK common usage patterns info
- Added "recommendations" section
Also added a new Style Guide entry that says to "organize state by data type, not components"
> Rewrite "Usage with TS" guide page

- docs/recipes/structuring-reducers/ImmutableUpdatePatterns.md
- docs/style-guide/style-guide.md
- docs/tutorials/essentials/part-2-app-structure.md
- docs/tutorials/essentials/part-4-using-data.md
- docs/tutorials/fundamentals/part-8-modern-redux.md
---
---
No existing issue
Problem raised by `Noob!` on the `Reactiflux` discord: https://discord.com/channels/102860784329052160/103538784460615680/823140384917159946
Yes - only existing files altered with no formatting changes.
All pages linking to `immer` docs:
- **Section**: Recipes/Structuring Reducers
- **Page**: Immutable Update Patterns
- **Page**: Style guide: Best Practices
- **Section**: Tutorials/Redux Essentials
- **Page**: Redux App Structure
- **Section**: Tutorials/Redux Essentials
- **Page**: Using Redux Data
- **Section**: Tutorials/Redux Fundamentals
- **Page**: Modern Redux with Redux Toolkit
Immer's documentation now has a different format. e.g. what was …
> Fix broken immer docs links

- .github/workflows/size.yaml
- index.d.ts
- package-lock.json
- package.json
- src/createStore.js
- src/utils/symbol-observable.js
- test/createStore.spec.js
- test/typescript/store.ts
This PR:
- Drops the legacy `symbol-observable` and `loose-envify` dependencies
- Inlines the `symbol-observable` polyfill
> Remove symbol-observable and loose-envify deps

- docs/tutorials/fundamentals/part-4-store.md
- docs/tutorials/fundamentals/part-6-async-logic.md
Adding a small fix and some extra clarity to a point of friction I found in the tutorial
> Tutorial Documentation edit - Being explicit about storeAPI object

- docs/recipes/ImplementingUndoHistory.md
The Prerequisites box in ImplementingUndoHistory.md did not render because it was missing the 'important'.
---
---
- **Section**:  https://redux.js.org/recipes/implementing-undo-history#implementing-undo-history
- **Page**:  https://redux.js.org/recipes/implementing-undo-history
The Prerequisites box not rendering.
Makes the Prerequisites box render.
> Docs: fix info box in ImplementingUndoHistory

- docs/faq/ImmutableData.md
---
about: Broken in-page links on Immutable Data FAQ 
---
- #4083 
- **Section**: FAQ
- **Page**: Immutable Data
All of the in-page anchor links on the first bullet point here are pointing to IDs that don't exist on the page:
It looks like these headings were rephrased at some point so I updated the links to point to the newer headings.
> Fix broken in-page links in immutable data FAQ

- docs/tutorials/essentials/part-2-app-structure.md
---
---
- **Section**: Detailed Explanation: Thunks and Async Logic
- **Page**: Redux Essentials, Part 2: Redux App Structure
`extraArgument` is part of the redux-thunk middleware but it's out of context for the purposes of this example.
Remove the `extraArgument` to avoid confusion.
> Docs: remove extraArgument from code example

- src/utils/kindOf.js
---
name: :bug: Bug fix or new feature
---
It fixes a bug.
Currently redux cannot be run in ES5 environments even if Babel is used.
- #4089
Please refer to #4089.
**TL;DR** There are functions declared inside an `if` statement, which ES5 forbids and Babel does not fix.
Redux should run without any syntax errors, if it's being bundled and transpiled in the standard manner for ES5.
It moves the aforementioned functions out of the if statement and into the file's scope.
The diff looks huge but it's mostly due to the indentation changing.
> Move miniKindOf out of if scope to fix ES5 compatibility issue

- docs/tutorials/fundamentals/part-5-ui-and-react.md
---
---
- **Section**: Tutorial
- **Page**: 5
<TodoListItem> should be <TodoList>
> [Tutorial Docs] Fix incorrect reference

- docs/recipes/WritingTests.md
---
---
Existing
- https://github.com/testing-library/testing-library-docs/issues/570
- **Section**: Components and Connected Components
- **Page**: Writing Tests
The Components and Connected Components sections are merged together, using React Redux hooks as an example of connected components (since they're not usually separate from unconnected components any more). This makes them more consistent with the [Testing Library recipe](https://testing-library.com/docs/example-react-redux) (which I'd like to remove in favor of this one) and easier to understand for new hook-based components.
They assume …
> Simplify Writing Tests recipe with hooks

- docs/tutorials/essentials/part-2-app-structure.md
We don't use "that" in descriptive clause.
> [docs/tutorials/essentials/part-2]: grammatical error fixed

- docs/introduction/Examples.md
The links and CodeSandbox iframe in the "Todos w/ Flow" example are broken: https://redux.js.org/introduction/examples#todos-w-flow
The actual example files were removed in a previous commit: https://github.com/reduxjs/redux/commit/ebf125297430ce33ea7b21279445bbb935092ed8#diff-c590b3c924c35c2f241746522284e4709df490d73a38aaa7d6de4ed1eac2f546
This PR just removes the references to the now-deleted example.
> Remove now-deleted Flow example from docs

- docs/tutorials/quick-start.md
- docs/tutorials/typescript.md
It's imported, but not actually being used.
---
---
- **Page**: Quick Start/TypeScript Quick Start
useState is imported, but not actually being used.
Remove useState import.
> Remove useState import

- netlify.toml
- website/package-lock.json
- website/package.json
This PR:
- Updates Docusaurus to 2.0-beta.1
- Actually turns on Webpack caching for Netlify builds
> Update Docusaurus to 2.0-beta.1

- docs/tutorials/fundamentals/part-1-overview.md
---
---
- **Section**:
- **Page**:
`concepts` is plural but is referred to using `is`
chage `is` to `are`
> docs: fix typo

- docs/redux-toolkit/overview.md
- docs/tutorials/essentials/part-5-async-logic.md
- docs/tutorials/fundamentals/part-8-modern-redux.md
This PR:
- Adds "RTK now has RTKQ for data fetching!" info boxes to the tutorial pages on async logic, as an FYI
- Cleans up the links on the RTK overview page
> Add links to RTKQ in the tutorials and clean up RTK page

- docs/recipes/WritingTests.md
- Update page with a heavy focus on integration testing
- Remove some 'low value' unit test examples completely
- Update examples to use RTK
In general - tries to finally update the writing tests page to reflect Mark's (and hopefully the React community's) ideas on best testing practices (as written about here: https://blog.isquaredsoftware.com/2021/06/the-evolution-of-redux-testing-approaches/)
I think this PR deserve some thorough poking & criticism - some of the changes might involve my own opinions, which I'd rather get tweaked to be the community's opinions on best practices for high value tests.
For example, I shifted towards a mindset of 'You generally treat reducers/selectors as implementation details that don't need testing, but can write unit tests for them if you want'. I would …
> 📝 Update writing tests page

- website/src/css/custom.css
As same as https://github.com/reduxjs/redux-toolkit/pull/1200 I changed text color front of darkness background color.
This might be better to read.
BeforePR
AfterPR
> [website] text color always white on darkness BG

- docs/tutorials/essentials/part-4-using-data.md
---
---
- **Page**: Using Redux Data
In the [Preparing Action Payloads](https://redux.js.org/tutorials/essentials/part-4-using-data#preparing-action-payloads) section, the first sentence's period after the `action.payload` should be outside of the ``.
The expected sentence should be the following:
We just saw that the action creators from `createSlice` normally expect one argument, which becomes `action.payload`.
> [Docs] Fix the period in the Redux Essentials

- docs/usage/writing-logic-thunks.mdx
---
name: :memo: Fixing broken links to redux-thunk github
about: Fixing broken links to redux-thunk github
---
- N/A
- **Section**: Using Redux
- **Page**: [Writing Logic with Thunks](https://redux.js.org/usage/writing-logic-thunks)
There are 2 broken Github links to the redux-thunk documentation in this document - they are both missing the `x` in `redux-thunk`.
It adds in the 2 x's :)
> Fixing broken links to redux-thunk github

- docs/faq/CodeStructure.md
---
---
- **Section**:
- **Page**: [FAQ Code Structure Page](https://redux.js.org/faq/code-structure#how-can-i-use-the-redux-store-in-non-component-files)
There's a typo for arrow function syntax
I fixed the syntax
> Fix typo for arrow function syntax

- docs/tutorials/fundamentals/part-5-ui-and-react.md
---
about: Fixing a grammar mistake in an existing docs page
---
- [] Is there an existing issue for this PR? no
- **Section**: tutorials/fundamentals
- **Page**: part-5-ui-react
Missing 'it' pronoun.
Add 'it' pronoun.
> [Tutorial Docs] Fixing a grammar mistake

- docs/tutorials/essentials/part-5-async-logic.md
in the tutorial code examples use "response.posts", "response.post", "response.users". The code works if all of this is replaced with "response.data", as it is shown in the final code shown in the last section "What You've Learned"
> response.data in code snippets in tutorial fixed

- docs/tutorials/essentials/part-5-async-logic.md
The mock server expects _just_ the `initialPost` object, rather than an object with a `post` field.
> Fix code snippet in tutorial (async logic)

- docs/tutorials/essentials/part-6-performance-normalization.md
The action payload first needs to be pushed to the state object before the `isNew` field is changed, otherwise messages are all always marked as 'read'.
Trivially fixes a couple of references to `useEffect` where it should be `useLayoutEffect` in the `NotificationsList` component.
> Fix code snippet and typo in tutorial

- docs/tutorials/essentials/part-5-async-logic.md
---
---
- **Section**: https://redux.js.org/tutorials/essentials/part-5-async-logic#checking-thunk-results-in-components
- **Page**: https://redux.js.org/tutorials/essentials/part-5-async-logic
There is a redundant line in the section. This now is obsolete, and `.unwrap()` method on the dispatch is being used to unwrap the Promise.
```jsx
import { unwrapResult } from '@reduxjs/toolkit'
```
Remove the corresponding line from documentation, to avoid confusion.
> docs: Remove redundant line from Redux Essentials Tutorial

- docs/tutorials/essentials/part-8-rtk-query-advanced.md
This PR:
- Fills in an omitted code snippet at the end of the "RTKQ Advanced" tutorial page
- Rewrites the tutorial content to better explain what the metadata changes are
Fixes #4203 (belatedly)
I also added two commits to the https://github.com/reduxjs/redux-essentials-example-app/tree/tutorial-steps branch that should have been there originally, which cover the code changes for the notifications implementation.
> Clarify notifications slice export changes

- docs/tutorials/essentials/part-6-performance-normalization.md
This moves the call to upsertMany the new notifications before the code
which assigns the isNew boolean. Otherwise isNew is not set correctly on
new notifications and you don't get the new styles applied. This is
consistent with the previous example code before it was converted to use
createEntityAdapter.
---
---
- **Section**: Redux Essentials Tutorial
- **Page**: part-6-performance-normalization
The code example which adds `createEntityAdapter` to the notifications reducer breaks the functionality where new notifications are shown in a different style.
It moves the statements in the correct order to fix the issue. This matches the order they were in before the `createEntityAdapter` conversion. See lines …
> Fix code example in part-6-performance-normalization.md

- docs/tutorials/essentials/part-4-using-data.md
---
---
- [ x] Have the files been linted and formatted? 
- **Section**: Redux Essentials Tutorial
- **Page**: Part 4
Going through this tutorial in the docs (Redux Essentials Part 4), reading the code example for the SinglePostPage component, I found that `match.params.postId` is a string, whereas the postId on the post object is a number (line 252).
e.g `2 === '2' `returns false in line 255.
Propose wrapping this in the `Number()` function to avoid `state.posts.find(post => post.id === postId)` returning undefined.
> Convert postId param to number before using

- docs/faq/ImmutableData.md
There are list items in a bullet point marked by dashes. They are converted into nested bullet points for increased readability.
---
---
- **Section**: _Why is immutability required by Redux?_
- **Page**: https://redux.js.org/faq/immutable-data 
There are dashes to mark list items in a bullet point, but they are unformatted, making it hard to read. 
This PR adds newlines and indentation so that the dashed text in the bullet point can become nested bullet points.
> docs(immutable data): nested bullet point formatting

- docs/faq/OrganizingState.md
Because this was written at 2016, the content seems like counter part for over engineering with verbosity [Boilerplate](https://github.com/ryota-murakami/trueblue/tree/master/app/Resources/js).  
But we are living post Redux-Toolkit,「You Might Not Need Redux」is not tell us the Author's original meant by context lost.
> Docs: Redux [FAQ: Organizing State] remove You Might Not Need Redux

- docs/tutorials/essentials/part-7-rtk-query-basics.md
---
name: :book: Add a tip pointing to code splitting
about: Updating content in an existing docs page
---
**update an _existing_ page**
- [Discord thread](https://discord.com/channels/102860784329052160/103538784460615680/920489794331611136)
- No, since I've edited directly in Github, but LGTM?
- **Page**: RTK Query Advanced Patterns
The main goal is to highlight the fact that you're expect to have only one `createApi` call in the app. (Maybe it's rather one per API, as in, if it's a different server, it's a different `createApi`?). I'm also putting a link to the advanced concept of `Injecting endpoints` that people most likely want when calling `createApi` multiple times.
I don't think so.
> Add a tip pointing to code splitting

- docs/introduction/GettingStarted.md
---
---
- **Section**: Getting Started
- **Page**: Basic Example
https://redux.js.org/introduction/getting-started#basic-example
Extra space between words of the example code.
Removes extra space from the example code.
> Got rid of the extra space

- website/docusaurus.config.js
---
---
Poor UX: there's no way to tell if we are reading a new version of the docs besides reading it entirely.
Now we'll get something like this:
> docs: display last update time

- docs/api/applyMiddleware.md
- docs/api/bindActionCreators.md
---
---
- https://github.com/reduxjs/redux/issues/4253
- **Section**:
- API Reference
- **Pages**:
- [applyMiddleware](https://redux.js.org/api/applymiddleware#example-using-thunk-middleware-for-async-actions)
- [bindActionCreators](https://redux.js.org/api/bindactioncreators#somecomponentjs)
The class-based react components should be converted to functional components.
Converting the components to functional components assumes the audience understands the basics of functional react components and hooks. In contrast, the existing examples assume the audience understands the lifecycle methods of class …
> Convert class components to functional components in the API docs examples

- package-lock.json
- package.json
I noticed some deprecated package warnings when I was installing dependencies:
```
madison ~/projects/redux 
532 ߷  rm -rf node_modules && npm ci 
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
added 1029 packages, and audited 1030 packages in 13s
88 packages are looking for funding
run `npm fund` for details
1 moderate severity vulnerability
To address all issues, run:
npm audit fix
Run `npm audit` for details.
```
After looking into these packages, it seems that they are only depended upon by one package in the project, `@babel/cli`:
```
madison ~/projects/redux 
533 ߷  npm ls urix                  
redux@5.0.0-alpha.0 /Users/madison/projects/redux
└─┬ …
```
> Removed deprecated packages by upgrading @babel/cli to version 7.16.7

- docs/usage/WritingTests.md
---
---
- _https://github.com/reduxjs/redux/issues/4263_
- **Section**: code quality
- **Page**: Writing tests
- "Redux code needs it's own dedicated tests", **it's** should be replaced by **its**.
- "Redux code needs it's own dedicated tests" -> "Redux code needs its own dedicated tests"
> Typo fix in WritingTests.md

- docs/usage/UsageWithTypescript.md
---
---
- https://github.com/reduxjs/redux/issues/4267
- **Section**: Type Checking Middleware
- **Page**: https://redux.js.org/usage/usage-with-typescript
When using TypeScript with RTK and adding types to a custom middleware following from https://redux.js.org/usage/usage-with-typescript#type-checking-middleware, for example:
```typescript
import { Middleware } from 'redux';
import { RootState } from '../store';
export const simpleMiddleware: Middleware<unknown, RootState> = api => next => action => {
const result = next(action);
if (action.type === 'cards/fetchById') {
console.group(action.type);
console.log(`dispatching`, action);
console.log('next state', api.getState());
console.groupEnd();
}
return …
```
> 📝 Update Type Checking Middleware for preventing RootState circular type references

- docs/usage/UsageWithTypescript.md
For docs consistency.
---
---
- No issue
- **Section**: Code Quality
- **Page**: Usage with TypeScript
Inconsistency. Maybe just a typo. There is written _"prefer creating a pre-typed `useSelector` hook with the correct type"_ in the block "Typing the useSelector hook". When in the next block about `useDispatch` it says this: _"prefer creating a pre-typed `useAppDispatch` hook with the correct type"_. Both are correct, I guess. First one is like "... pre-typed **version of** `useSelector` hook ...", and second one is about the hook defined already. But I think the second one is clearer, because it refers a reader to the information he have read above.
Change the name.
> Update pre-typed selector hook name

- docs/understanding/history-and-design/PriorArt.md
---
---
- **Section**: "Understanding Redux" -> "History and Design"
- **Page**: "Prior Art"
The link to the Elm creator's Twitter account is broken.
It updates that link to point to the [correct Twitter account](https://twitter.com/evancz).
> docs: Fix link to Elm creator's Twitter account

- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
[:memo: Documentation Fix](?template=documentation-edit.md)
This Pull Request is addressed to the issue #4285 for fixing the typos in Redux Fundamentals Part 3: State, Actions and Reducers page.
> Fix in the documentation page of Redux Fundamentals Part3

- docs/faq/ReactRedux.md
- docs/style-guide/style-guide.md
- docs/tutorials/essentials/part-1-overview-concepts.md
- docs/tutorials/fundamentals/part-1-overview.md
- docs/tutorials/fundamentals/part-4-store.md
- docs/usage/ConfiguringYourStore.md
---
about: Update doc links to the new devtools extension repository
---
- **Section**: 
- **Page**:
- [Redux Essentials, Part 1: Redux Overview and Concepts](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)
- [Redux Fundamentals, Part 1: Redux Overview](https://redux.js.org/tutorials/fundamentals/part-1-overview)
- [Redux Fundamentals, Part 4: Store](https://redux.js.org/tutorials/fundamentals/part-4-store)
- [Configuring Your Store](https://redux.js.org/usage/configuring-your-store)
- [Redux FAQ: React Redux](https://redux.js.org/faq/react-redux)
- [Redux Style Guide](https://redux.js.org/style-guide/style-guide)
The devtools extension repository links are pointing to deprecated repository.
Just update the links to …
> Update references to devtools extension repository

- docs/tutorials/essentials/part-7-rtk-query-basics.md
---
---
- **Page**: RTK-Query Basics
Typo in docs text that has incorrect component/file name as compared with the code repo and snippet.
Rename the component name in the text and Markdown code notation to the correct component.
> Fix incorrect component/file name

- docs/tutorials/essentials/part-8-rtk-query-advanced.md
---
---
- **Page**: RTK Query Advanced Patterns
Typo in docs text that has incorrect component/file name as compared with the code repo and snippet.
Rename the component name in the text to the correct component.
> [DOCS] Fix incorrect component/file name

- rollup.config.js
This PR introduces the following improvements to the Rollup configuration file:
1. `compress.warnings` is not a valid Terser option, as can be seen in [Terser's docs](https://github.com/terser/terser/blob/v5.10.0/README.md#compress-options) and [type declarations](https://github.com/terser/terser/blob/v5.10.0/tools/terser.d.ts#L14-L69). Therefore, it has been removed.
2. To minimize the likelihood of making similar mistakes, Intellisense has been enabled for `rollup.config.js`, as recommended in  [Rollup's docs](https://github.com/rollup/rollup/blob/v2.70.0/docs/01-command-line-reference.md#config-intellisense).
3. Currrently, the `makeExternalPredicate` function involves a great deal of indirection in preparing the `external` object. The fact that Rollup can [accept an array of `RegExp`s …
> Revamp `rollup.config.js`

- docs/introduction/Installation.md
Updating redux `devtools` package as previous one is depreciated and having dependency issues with `react ^17`
---
---
- https://github.com/reduxjs/redux/issues/4300
- **Section**:
- https://redux.js.org/introduction/installation#complementary-packages 
- **Page**:
Documentation is pointing out deprecated redux `devtool` extension that is causing 
Above issue.
Documentation will be updated with the latest package and avoid dependency issues during the installation of the package
> [Docs] Update Installation.md

- docs/tutorials/essentials/part-5-async-logic.md
This is to address the difference between the reducer used in the
"loading users" section and the rest of the reducers used in the
tutorial up to that point.
See the discussion in:
https://github.com/reduxjs/redux/issues/4317
---
---
- https://github.com/reduxjs/redux/issues/4317
- **Section**: Loading users
- **Page**:  https://github.com/reduxjs/redux/blob/master/docs/tutorials/essentials/part-5-async-logic.md
The reducer in this section returns a value instead of updating the existing state. This is the first time this technique is used in the tutorial, all previously used reducers update the existing state. While this works and is the correct solution, it is used without any comment as of why this approach …
> Add explanation for returning payload

- docs/tutorials/essentials/part-5-async-logic.md
- docs/tutorials/essentials/part-8-rtk-query-advanced.md
- show MSW usage as awaiting service worker registration
in case of race conditions with other workers
- minor text updates
---
---
N/A - No existing issue
- **Section**: Tutorials/Redux-Essentials
- **Page**: 
- Redux Essentials, Part 5: Async Logic and Data Fetching
- Redux Essentials, Part 8: RTK Query Advanced Patterns
MSW by default will defer network requests while starting the worker (see [start#waituntilready](https://mswjs.io/docs/api/setup-worker/start#waituntilready)). However, @msutkowski has pointed out if service worker registration fights with another, it won't kick in. The result is flaky behaviour - sometimes the requests will be attempted prior to the service worker registration, causing …
> 📝 Update MSW usage

- docs/tutorials/quick-start.md
Add a missing quote in "Usage Summary" section
---
---
- **Section**: Usage Summary
- **Page**: Quick Start
Missing quote.
Add missing quote.
> Fix typo in quick-start.md

- index.d.ts
- package-lock.json
- src/createStore.js
- src/index.js
This PR marks the `createStore` API as deprecated, and adds a new `legacy_createStore` API as an alias without the deprecation notice.
- Updated `createStore`'s doc description to mark it as `@deprecated`,
so that it shows up with a visual strikethrough in editors.
- Added new descriptive text to `createStore` to encourage users to
migrate to RTK, and pointing to the "RTK is Redux Today" docs page
- Rewrote TS typedefs for `createStore` to define it as a function with
overloads, rather than a varible, to get correct docs tooltips when
hovering over variable usages
- Added `legacy_createStore` API as an alias without the deprecation
Redux Toolkit (the `@reduxjs/toolkit` package) is the right way for Redux users to write Redux code today: …
> Mark `createStore` as deprecated, and add `legacy_createStore` alias

- docs/introduction/Ecosystem.md
Just the right formatting for the change I accidentally pushed to master 🙃
> update ecosystem docs formatting

- docs/faq/ReactRedux.md
---
broken links: :memo: Documentation Fix
about: Update several broken links
---
- **Section**: https://redux.js.org/faq
- **Page**: https://redux.js.org/faq/react-redux
Broken links for several external resources:
- [A Deep Dive into React Perf Debugging](https://benchling.engineering/deep-dive-react-perf-debugging/)
- [Improving React and Redux Performance with Reselect](https://blog.rangle.io/react-and-redux-performance-with-reselect/)
Update broken links with a valid links
> fix(docs): broken links for external resources

- docs/faq/ImmutableData.md
- docs/faq/Performance.md
- docs/redux-toolkit/overview.md
---
broken links: :memo: Documentation Fix
about: Update and delete broken links
---
- **Section**: [FAQ](https://redux.js.org/faq) & [Redux Toolkit](https://redux.js.org/redux-toolkit/overview)
- **Page**: [Immutable Data](https://redux.js.org/faq/immutable-data), [Performance](https://redux.js.org/faq/performance), and [Redux Toolkit Overview](https://redux.js.org/redux-toolkit/overview)
Broken links for external resources:
- [JavaScript and Immutability](https://t4d.io/javascript-and-immutability/)
- [Cloning Objects in JavaScript](https://www.zsoltnagy.eu/cloning-objects-in-javascript/)
- [`apollo-boost`](https://dev-blog.apollodata.com/zero-config-graphql-state-management-27b1f1b3c2c3)
Update apollo-boost link and delete links for article [JavaScript and …
> fix(docs): update and remove broken links

- website/docusaurus.config.js
---
name: :bug: Bug fix 
about: Fixing a problem with Website footer link navigation
---
Bug fix
Fixed a bug
It fixes the issue with routing to the Usage Guides from the Footer links on the Docs website
- Visit the [website](https://redux.js.org/usage/index)
- Scroll down to the footer section and click on the Usage Guide link
- This routes to /usage/index, which ends up in "Page not Found"
- Clicking on the Usage Guide link in the footer section, should route to https://redux.js.org/usage/
- This PR updates the Usage Guide path in the docusaurus config file to the right value
> fix: update the footer usage guide link to the right value

- docs/introduction/Ecosystem.md
---
name: :memo: Correct Redux Batch Usage
about: Correcting the Redux Batch example to have the enhancer on both ends
---
- #4369 
- **Page**: Ecosystem
Correct [redux-batch](https://github.com/manaflair/redux-batch#usage-w-extra-middlewares) usage requires making sure that reduxBatch is at the beginning and end of the enhancers array, whereas [current docs](https://redux-toolkit.js.org/api/configureStore#full-example) only use the array config version (which would put reduxBatch after the middleware enhancer, preventing the use of middleware within batches e.g. thunks).
This [codesandbox](https://codesandbox.io/s/redux-batch-rtk-typing-yl6b0t?file=/src/index.ts) can be used to replicate the issue - change line 71 to `enhancers: [reduxBatch]`. …
> Correct Redux Batch Usage

- docs/usage/WritingTests.mdx
- docs/usage/index.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
- website/tsconfig.json
- Set up ability to transpile codeblocks to show a TS & JS tab
- Convert 'WritingTests' page to use transpiled codeblocks
- Update snippets on 'WritingTests' page
---
about: Updating content in an existing docs page
---
Updates an existing page (Writing Tests).  
Also adds the ability to transpile doc codeblocks from TS to show both TS & JS tabs.
- https://github.com/reduxjs/redux/issues/4112 (does not complete the issue)
- **Section**: Usage
- **Page**: Writing Tests
- Show both TS & JS tabs for codeblocks
Yes - now targeted to accommodate both TS & JS users
> 📝 Enable codeblock TS transpilation

- docs/tutorials/typescript.md
This PR:
- Adds a CSB embed of the `counter-ts` example to the "TS Getting Started" page
and we should do the same for the other couple copies of this page on the RTK and React-Redux docs too
> Add a CodeSandbox counter app embed to the "TS Getting Started" page

- docs/tutorials/essentials/part-8-rtk-query-advanced.md
---
---
- None
- **Section**:  Redux Essentials, Part 8
- **Page**: Manipulating Response Data: Selecting Values from Results
Small grammatical error where "preferably" should be "preferable"
Changes "preferably" to "preferable"
> Fix small grammatical error

- examples/counter/src/App.test.js
Fixes lint error in counter example.
Use `npm run examples:lint` to reproduce.
See [here](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/prefer-screen-queries.md) for error details.
> Fix lint error

- docs/usage/writing-logic-thunks.mdx
- update function name `fetchTodoThunk` => `fetchTodoByIdThunk`
matched the function name to the comment name at line 49, and a little bit reasonable.
That's it! Maybe I missed something, if so. Just ignore this pr.
- [:memo: Documentation Fix](https://github.com/reduxjs/redux/compare/master...benben6515:redux:patch-1#diff-4160c89fb9a8145b89def858ba4a51bb5beaadf787556d91cbc018dba78c1c70)
> [DOC] wording: fetchTodoThunk => fetchTodoByIdThunk

- docs/tutorials/essentials/part-5-async-logic.md
Using `key` attribute here is a mistake. It makes sense only in context of an array according to official React documentation (see [here](https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys)).
> Remove unnecessary key attribute

- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
---
---
- **Section** Fundamentals
- **Page**: 3
There's [no situation](https://www.thepunctuationguide.com/terminal-points.html) in which a period should follow an exclamation point, including when inside quotes, regardless of text styling.
Change "it's okay to have other state values outside of Redux!." to "it's okay to have other state values outside of Redux!"
> Docs: delete extraneous full stop after exclamation mark

- docs/usage/UsageWithTypescript.md
---
---
- **Section**: usage
- **Page**: UsageWithTypescript.md
As a Redux Toolkit user, when i stumbled upon the circular depency problem when TypeChecking the middlwares and read this page, i was confused by the current snippet and explanation. By setting a store with the Redux Toolkit quick start example (https://redux-toolkit.js.org/tutorials/quick-start), you never use `combineReducers` and so i did not really know what to change (i had to do further research). 
I added a code snippet (how i solved the problem in my app) for Redux Toolkit hoping that it can be more clear for users them and save some searches on google. Let me know what you think please!
> Middlewares TypeChecking problem and Redux Toolkit 

- docs/tutorials/essentials/part-8-rtk-query-advanced.md
Reverts reduxjs/redux#4415
We're still using React-Router v5, not v6
> Revert "Update part-8-rtk-query-advanced.md"

- docs/usage/WritingTests.mdx
There is a type error in the `UserDisplay` component example because we don't display the name but the object instead.
> fix: type error in `UserDisplay` component example

- docs/introduction/Examples.md
- docs/tutorials/essentials/part-2-app-structure.md
- docs/tutorials/essentials/part-3-data-flow.md
- docs/tutorials/essentials/part-4-using-data.md
- docs/tutorials/essentials/part-5-async-logic.md
- docs/tutorials/essentials/part-6-performance-normalization.md
- docs/tutorials/essentials/part-7-rtk-query-basics.md
- docs/tutorials/essentials/part-8-rtk-query-advanced.md
- docs/tutorials/fundamentals/part-1-overview.md
- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
- docs/tutorials/fundamentals/part-4-store.md
- docs/tutorials/fundamentals/part-5-ui-and-react.md
- docs/tutorials/fundamentals/part-6-async-logic.md
- docs/tutorials/fundamentals/part-7-standard-patterns.md
- docs/tutorials/fundamentals/part-8-modern-redux.md
- docs/tutorials/quick-start.md
- docs/tutorials/typescript.md
Currently the embeds for codesandbox.io do not allow you to scroll on mobile devices (tested on Samsung Galaxy S22 Ultra). This is a problem because users are unable to view the whole project as they are reading through the amazing documentation and examples that have been created. Fix this by updating the src url to include the codemirror option which uses the CodeMirror editor instead of Monaco and also reduces the embed size as well
---
---
- #4431
All sections and pages that use the codesandbox.io embeds
Users are unable to scroll within files in the embeds so they are unable to view the entire file
Switch to using the CodeMirror editor instead of the default Monaco editor from codesandbox.io
> fix: codesandbox embeds mobile scrolling

- docs/faq/OrganizingState.md
---
name: :book: Updated Documentation Content
about: Remove outdated content in "Do I have to put all my state into Redux?"
---
- https://github.com/reduxjs/redux/issues/4421
- **Section**: Do I have to put all my state into Redux? Should I ever use React's `setState()`?
- **Page**: Redux FAQ: Organizing State
- There's a mix of outdated links that mention either class components and/or unmaintained libraries, which can be confusing for new developers
- I went through each link and only kept the ones that had answers which were agnostic about the version of React used (or used React hooks)
- I had a minor concern about keeping [this link](https://stackoverflow.com/questions/35328056/react-redux-should-all-component-states-be-kept-in-redux-store/35328862#35328862) because it mentions …
> Remove outdated content in "Do I have to put all my state into Redux?"

- docs/faq/OrganizingState.md
---
name: :book: Updated Documentation Content
about: Remove outdated content in "How do I organize nested or duplicate data in my state?"
---
- https://github.com/reduxjs/redux/issues/4421
- **Section**: How do I organize nested or duplicate data in my state?
- **Page**: Redux FAQ: Organizing State
- Add a link to "Redux Essentials: Normalizing Data"
- Remove content that contains multiple dead/outdated links 
- Remove content focused on performance optimization with older versions of `react-redux` and `react`
- I understand this section is about organizing state but after reading through `"High-Performance Redux"` and `"Stack Overflow: How to optimize small updates to props of nested components in React + Redux?"`, they only mention normalization briefly 
- Their main focus was more on …
> Remove outdated content in "How do I organize nested or duplicate data in my state?"

- docs/usage/structuring-reducers/PrerequisiteConcepts.md
Name: :memo: Documentation Fix
About: Link for dead website removed from **Prerequisite Reducer Concepts** section.
> Dead link for ryanFunduk removed.

- docs/style-guide/style-guide.md
---
---
- No
- **Page**: Style Guide: Best Practices
Unnecessary space after link.
Removes the space.
> Remove unnecessary space in style guide

- docs/usage/WritingTests.mdx
---
name: :memo: Documentation Fix for WritingTests.mdx
about: Remove unused configureStore imports from code examples
---
- **Section**: Using Redux -> Code Quality -> Writing Tests -> Setting Up a Reusable Test Render Function
- **Page**: https://redux.js.org/usage/writing-tests#setting-up-a-reusable-test-render-function
Unused `configureStore` import in code example as seen in the following screenshot:
This PR removes unused imports from the mdx file
> Documentation Fix for WritingTests.mdx

- src/createStore.ts
- src/index.ts
This PR ports changes from the 4.x branch up to `master`:
- The `isMinified` check removal from #4454
- The `createStore` deprecation from #4336
> Port `createStore` deprecation and `isMinified` removal from 4.x branch

- src/createStore.ts
- src/types/store.ts
Redux has always used an array of listener callbacks internally.  However, as we found out with React-Redux, using `listeners.findIndex(callback)` is bad for performance ( https://github.com/reduxjs/react-redux/pull/1523 , https://github.com/reduxjs/react-redux/issues/1869 ).
React-Redux uses a custom linked list internally.  That's way more than we need here.  But, now that we're assuming modern browsers, it's safe to assume ES2015+ support, and that `Map/Set`s are available.  
I initially tried `Set<ListenerCallback>`, but found that one test failed... because it was passing in the same `jest.fn()` instance _twice_.  A `Set` compares by reference, so the callback got removed in the first `unsubscribe()` call and was no longer around for the second.
We don't have a formal statement that …
> Replace listeners array with a Map for better performance

- docs/tutorials/fundamentals/part-4-store.md
---
---
- **Section**: tutorials/fundamentals/part-4-store
- **Page**: your-first-custom-middleware
The problem is in definition of alwaysReturnHelloMiddleware function
=> is missed
Adds => to the definition of alwaysReturnHelloMiddleware
> Added => for arrow function definition

- docs/introduction/why-rtk-is-redux-today.md
- docs/tutorials/fundamentals/part-4-store.md
- docs/usage/migrating-to-modern-redux.mdx
- website/sidebars.js
This PR:
- Adds a new "Usage > Migrating to Modern Redux" docs page.  It covers migrating to RTK and React-Redux hooks, including TS-specific topics
> Add "Migrating to Modern Redux" docs page

- .github/workflows/test.yaml
- package.json
- test/applyMiddleware.spec.ts
- test/bindActionCreators.spec.ts
- test/combineReducers.spec.ts
- test/compose.spec.ts
- test/createStore.spec.ts
- test/helpers/actionCreators.ts
- test/helpers/middleware.ts
- test/helpers/reducers.ts
- test/typescript/actionCreators.ts
- test/typescript/actions.ts
- test/typescript/compose.ts
- test/typescript/dispatch.ts
- test/typescript/enhancers.ts
- test/typescript/injectedDispatch.ts
- test/typescript/middleware.ts
- test/typescript/reducers.ts
- test/typescript/store.ts
Our `test` command has always done a full lint+build step every time, which is annoying.
I've reworked it so that `test` runs against `src`.
Also, apparently we don't actually do typetests against the usual range of TS versions like we do in all of our other repos.  Added that.
> Run tests from source instead of building first

- src/applyMiddleware.ts
- src/createStore.ts
- src/index.ts
- src/types/store.ts
- test/typescript/enhancers.ts
- test/typescript/store.ts
---
name: "Fix type of next parameter in StoreEnhancer type"
about: Fix type of next parameter in StoreEnhancer type
---
Fix a bug. Resolves https://github.com/reduxjs/redux/issues/3768.
Without this PR the type for `next` in `StoreEnhancer` is incorrect. It assumes that `next` will create a store with the current enhancers `Ext` and `StateExt` already applied to store. Instead, `next` returns a store with `NextExt` and `NextStateExt` generic parameters since the enhancer should work when composed with any other enhancer. It then expects the `StoreEnhancer` to return a new store creator that will create a store with `Ext` and `NextExt`, and `StateExt` and `NextStateExt`.
Note that I had to remove the `ExtendState` type in order to make this work. This type was introduced in …
> Fix type of next parameter in StoreEnhancer type

- src/types/store.ts
- test/typescript/enhancers.ts
- test/typescript/reducers.ts
- test/typescript/tsconfig.json
The PR says it all.
Update tests that were failing due to the lack of strict mode.
> Enable strict mode for TypeScript tests

- docs/faq/CodeStructure.md
---
name: :memo: Docs FAQ Section Fix
about: Fixing inconsistent use of semi-colons
---
When reading the docs I noticed inconsistent use of semi-colons in the code examples.
I found out the docs do not use them and decided to remove them.
> Fix inconsistent semi-colons in faq section

- package.json
From [Yarn docs about lifecycle scripts](https://yarnpkg.com/advanced/lifecycle-scripts):
> Note about yarn pack: Although rarely called directly, yarn pack is a crucial part of Yarn. Each time Yarn has to fetch a dependency from a "raw" source (such as a Git repository), it will automatically run yarn install and yarn pack on it to know which are the files to use.
> prepack is the lifecycle script called before each call to yarn pack. This is typically the place where you'll want to put scripts that build a package - such as transpiling its source.
> prepublish is called before yarn npm publish and similar commands (even before the package has been packed). This is the place where you'll want to check that the project is in an ok state. Because it's only called on prepublish, the …
> Build package in prepack instead of prepublish

- docs/usage/migrating-to-modern-redux.mdx
---
---
- **Sections**
- [Overview](https://redux.js.org/usage/migrating-to-modern-redux#overview)
- [Store Setup with configureStore](https://redux.js.org/usage/migrating-to-modern-redux#store-setup-with-configurestore)
- [Reducers and Actions with createSlice](https://redux.js.org/usage/migrating-to-modern-redux#reducers-and-actions-with-createslice)
- [Data Fetching with RTK Query](https://redux.js.org/usage/migrating-to-modern-redux#data-fetching-with-rtk-query)
- [Reactive Logic with createListenerMiddleware](https://redux.js.org/usage/migrating-to-modern-redux#reactive-logic-with-createlistenermiddleware)
- [Migrating TypeScript for Redux Logic](https://redux.js.org/usage/migrating-to-modern-redux#migrati …
> Minor fixes in migrating to modern redux documentation

- docs/components/_FundamentalsWarning.mdx
- docs/introduction/why-rtk-is-redux-today.md
- docs/redux-toolkit/overview.md
- docs/tutorials/essentials/part-1-overview-concepts.md
- docs/tutorials/essentials/part-2-app-structure.md
- docs/tutorials/essentials/part-3-data-flow.md
- docs/tutorials/essentials/part-5-async-logic.md
- docs/tutorials/essentials/part-7-rtk-query-basics.md
- docs/tutorials/fundamentals/part-1-overview.md
- docs/tutorials/fundamentals/part-2-concepts-data-flow.md
- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
- docs/tutorials/fundamentals/part-4-store.md
- docs/tutorials/fundamentals/part-5-ui-and-react.md
- docs/tutorials/fundamentals/part-6-async-logic.md
- docs/tutorials/fundamentals/part-7-standard-patterns.md
- docs/tutorials/quick-start.md
- docs/tutorials/tutorials-index.md
- docs/tutorials/typescript.md
- docs/usage/migrating-to-modern-redux.mdx
- docs/usage/side-effects-approaches.mdx
This PR:
- Adds a "warning" callout to most "Fundamentals" pages clarifying that the page intentionally shows outdated hand-written patterns for the purpose of explanation, and that you should look at the "Essentials" tutorial to learn how to use RTK
- Exceptions: Part 1 (already has a similar blurb), Part 5 (React-Redux usage is the same), Part 8 (already shows RTK migration)
- Updates both "Quick Start" pages to more clearly state "go to 'Essentials' next"
- Adds a recommendation reasons section with "why RTK Query / listeners, not sagas"
Fixes #4495 .
Example:
- https://deploy-preview-4496--redux-docs.netlify.app/tutorials/fundamentals/part-2-concepts-data-flow
(can't upload a picture due to lousy airplane wifi)
I'm totally open to suggestions for improving the callout text, or …
> Add "use modern Redux" warnings to Fundamentals pages

- docs/introduction/why-rtk-is-redux-today.md
---
---
- **Page**: Why RTK is Redux today
Simple typo/grammar issue
Removes a word
> fix: typo in introduction docs

- docs/tutorials/essentials/part-8-rtk-query-advanced.md
---
---
- **Page**: RTK Query Advanced Patterns
Simple misspelled word.
Removes a letter.
> docs: fixes typo in essentials rtk query guide

- docs/usage/migrating-to-modern-redux.mdx
---
---
- **Section**: Using Redux > Setup and Organization
- **Page**: https://redux.js.org/usage/migrating-to-modern-redux
```
Argument of type '{ url: string; }' is not assignable to parameter of type 'FetchBaseQueryArgs'. Object literal may only specify known properties, and 'url' does not exist in type 'FetchBaseQueryArgs'.
```
Replace `url` with `baseUrl`
> docs: fix migrating-to-modern-redux.mdx

- .codesandbox/ci.json
- .github/workflows/test.yaml
- package.json
- scripts/mangleErrors.cjs
- src/types/store.ts
- src/utils/formatProdErrorMessage.ts
- test/utils/formatProdErrorMessage.spec.ts
- tsconfig.json
- tsup.config.ts
- yarn.lock
This PR:
- Switches the build setup from Babel+Rollup to https://github.com/egoist/tsup (an ESBuild wrapper)
- Updates the package formatting to hopefully fix CJS/ESM compat issues
- Moves the build/publish output to all be in `./dist/`, and changes the file locations/names
- Drops the UMD bundles from the output
- Copies over the "test published artifact in these example projects" config from RTK and `redux-thunk`
- Updates the GH Actions test workflow to ignore `FalseCJS` problems from `arethetypeswrong`
> Rewrite build/setup and hopefully fix ESM compat

- .github/workflows/test.yaml
- package.json
In https://github.com/reduxjs/redux/pull/4487 we switched from ts-jest (which runs type-checking on test files) to Vitest (which does not).
This PR runs type-checking on the tests to make sure they pass.
> Type-check tests

- src/applyMiddleware.ts
- src/combineReducers.ts
- src/createStore.ts
- src/index.ts
- src/types/reducers.ts
- src/types/store.ts
- test/combineReducers.spec.ts
- test/createStore.spec.ts
- test/typescript/enhancers.ts
- test/typescript/reducers.ts
- test/typescript/store.ts
The main change to pay attention to here is the update to the `Reducer` type. Before this PR `Reducer` has a type of:
```
type Reducer<S, A extends Action> = (
state: S | undefined,
action: A
) => S
```
After this PR `Reducer` has this type:
```
type Reducer<S, A extends Action, PreloadedState = S> = (
state: S | PreloadedState | undefined,
action: A
) => S
```
Why the need for this change? When the store is first created by `createStore`, the initial state is set to whatever is passed as the `preloadedState` argument (or `undefined` if nothing is passed). That means that the first time that the reducer is called, it is called with the `preloadedState`. After the first call, the reducer is always passed the current state (which is `S`).
For most normal reducers, `S | undefined` accurately …
> Add PreloadedState generic

- src/types/middleware.ts
- test/applyMiddleware.spec.ts
- test/helpers/middleware.ts
- test/typescript/middleware.ts
---
name: :bug: Bug fix or new feature
---
It makes types safer for middleware.
Currently, the `next` parameter is typed as the `D` type parameter passed, and `action` is typed as the`Action` extracted from the dispatch type. Neither of these are a safe assumption:
- `next` would be typed to have **all** of the dispatch extensions, including the ones earlier in the chain that would no longer apply.
- Technically it would be *mostly* safe to type `next` as the default Dispatch implemented by the base redux store, however this would cause `next(action)` to error (as we cannot promise `action` is actually an `Action`) - and it wouldn't account for any following middlewares that return anything other than the action they're given when they see a specific …
> Type action and next as unknown

- docs/faq/CodeStructure.md
- docs/usage/WritingCustomMiddleware.md
- website/sidebars.js
Fixes #4472
---
---
Add a page
- #4472 
- **Section**: Usage Guide/Using Redux/Redux Logic and Patterns
- **Page**: Writing Custom Middleware
How-to
Developers thinking about writing their own middleware with low to medium experience with Redux.
How to use Redux and middleware in general, but not how to write middleware.
- Understanding what middleware can do
- Understanding when to write custom middleware vs. using existing packages
- Understanding how to write middleware that is compatible with other Redux middleware like RTK Query middleware
- That they most likely shouldn't write custom middleware
> Add documentation page "Writing Custom Middleware"

- docs/tutorials/essentials/part-1-overview-concepts.md
changed to a working URL (https://internetingishard.netlify.app/html-and-css/index.html)
---
---
- #4527 
- **Section**: Redux Essentials, Part 1: Redux Overview and Concepts
- **Page**: [this](https://redux.js.org/tutorials/essentials/part-1-overview-concepts#how-to-read-this-tutorial)
Url was broken
Changed to new working URL
> update tutorial link HTML & CSS url

- docs/tutorials/essentials/part-3-data-flow.md
---
---
- **Section**: Redux Essentials, Part 3: Basic Redux Data Flow
- **Page**: [this](https://redux.js.org/tutorials/essentials/part-3-data-flow#showing-the-posts-list)
the link refers to old React docs
updates the link to the latest React dev docs
> Update React Fragment link to latest React docs

- docs/usage/migrating-to-modern-redux.mdx
There is a typo in the docs for the listener middleware where it tries to prepend a middleware without calling `getDefaultMIddleware` first
`getDefaultMiddleware.prepend` is invalid
`getDefaultMiddleware().prepend` is ok
---
---
> Fix missing call to `getDefaultMiddleware`

- docs/tutorials/essentials/part-2-app-structure.md
---
---
- #4529
- **Section**: Redux Essentials, Part 2: Redux Toolkit App Structure [link](https://redux.js.org/tutorials/essentials/part-2-app-structure#writing-async-logic-with-thunks)
- **Page**: [this page](https://redux.js.org/tutorials/essentials/part-2-app-structure#writing-async-logic-with-thunks)
we should redirect to thunk docs instead of github repo
> fix: redux-thunk docs link

- docs/introduction/GettingStarted.md
- docs/introduction/Installation.md
- docs/tutorials/essentials/part-3-data-flow.md
This PR:
- Rewrites the installation instructions on the "Getting Started", "Installation", and "Essentials Part 3" pages to point to modern templates:
- The Vite+TS template we're about to add over in https://github.com/reduxjs/redux-templates
- The Next `with-redux` template
- Rahsheen's RN templates
> Update installation steps to point to modern templates

- docs/tutorials/typescript.md
---
---
- [ x ] Is there an existing issue for this PR?
- #4541 
- [ x ] Have the files been linted and formatted?
- **Section**: tutorials
- **Page**: typescript-quick-start
Add `export` to typescript quick start so the store object does not give same error.
> add export to typescript tutorial

- docs/introduction/why-rtk-is-redux-today.md
---
---
- **Page**: https://redux.js.org/introduction/why-rtk-is-redux-today
According to the usage [action.payload.id](https://github.com/reduxjs/redux/blob/4a6d2fb227ba119d3498a43fab8f53fe008be64c/docs/introduction/why-rtk-is-redux-today.md?plain=1#L94) payload should contain object.
> Fix example in why-rtk-is-redux-today.md

- website/src/css/custom.css
---
---
- #4538 
- The inline code blocks used inside DetailedExplanation.tsx
It's difficult to see the text in inline code blocks inside the DetailedExplanation component in dark mode. The css doesn't match the styles used for inline code blocks on the rest of the documentation.
I added a css 'color' property to the code declaration inside website\src\css\custom.css. The value is consistent with what's used outside the DetailedExplanation component.
> Add color property to 'code' css declaration

- docs/tutorials/essentials/part-6-performance-normalization.md
add highlight-next-line
---
---
- **Section**:
- **Page**:
This is the first time we are using useLayoutEffect in this file, so its import should also be highlighted.
add missing highlight
> add missing highlight

- docs/package.json
- docs/usage/WritingTests.mdx
- docs/yarn.lock
- website/package.json
- website/yarn.lock
- In msw docs they seem to be using http and HttpResponse for requests https://mswjs.io/docs/api/setup-server/
- Delay is performed with await so the function is now async https://mswjs.io/docs/api/delay/
[:memo: Documentation Fix](?template=documentation-edit.md)
> Update docs to MSW 2.0 | rest import discontinued and replaced by http instead

- docs/tutorials/videos.md
Changed TypeSCript to TypeScript at the bottom for the testing section.
---
---
- **Section**: Confidently Testing Redux Applications with Jest & TypeScript
- **Page**: https://redux.js.org/tutorials/videos
There's a typo. TypeSCript should be TypeScript
Fixes the typo
> Changed TypeSCript to TypeScript at the bottom for the testing section.

- src/index.ts
- src/utils/isAction.ts
- src/utils/isPlainObject.ts
- test/utils/isAction.spec.ts
This is already exported from RTK, but seems useful to move to core as the middleware typing changes now (correctly) treat `action` as `unknown` - exporting this provides an "official" way to check that a value is an action object (with the same restrictions as the final reducers - plain object with type string)
> Add isAction type predicate

- .github/workflows/test.yaml
- errors.json
- netlify.toml
- package.json
- test/typescript/store.ts
- yarn.lock
This PR:
- Bumps TS, Vitest, tsup, and ESbuild
- Updates our GH Actions and Netlify docs build to use Node 18
- Updates the TS test matrix to include 5.1-5.3
- Manually alters some typetest formatting to deal with error locations migrating with the switch from TS 4.x to TS 5.x
- Adds a missing error message
- Switches to the real `attw` CLI
- Handles the RTK CRA4 example failing with Node 18
> Update build tooling for 5.0

- .github/workflows/test.yaml
- package.json
- yarn.lock
This PR:
- Updates the `ts-eslint` packages to v6 to fix a mismatch with TS 5
- Adds a lint step to the CI workflow
> Updates ts-eslint packages to match TS 5

- docs/faq/Actions.md
---
---
-No
- **Section**: FAQ
- **Page**: Actions
There's a link to DecemberSoft "[Decembersoft: Redux-Thunk vs Redux-Saga](https://decembersoft.com/posts/redux-thunk-vs-redux-saga/)", but the link now have some content about "Top New Betting Sites in Australia".
Remove the link to that specific article.
> Remove link to DecemberSoft post no longer valid (now have content about bets in australia)

- src/createStore.ts
- src/types/store.ts
- test/typescript/store.ts
---
name: :bug: Fix the return type of function `Store['getState']`
about: Unexpectedly narrowed type
---
This PR fixes a bug in the type definitions.
The return type of function `Store['getState']` is unexpectedly narrowed to non-nullable.
```ts
import { type Reducer, createStore } from 'redux'
type NonNullableState = { count: number }
const nullableReducer: Reducer<NonNullableState | null> = () => null
const storeWithNullableState = createStore(nullableReducer)
const nullableState = storeWithNullableState.getState()
//    ^? const nullableState: NonNullableState
```
TS Playground: <https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjAnmApnASugJgVwGN0oAaOQqdAQxnQGUZpMBfOAMyghDgHIqCAD14AoEagxwAchAB2U-ABtF1AEaKGMWpgC8iChHyyYALjiz8IVSTgsRhOQGd4F5Wo04CxKGc9ESADwy8koq6pracAA+5qEAfHB6ABQ …
> fix(types/store): Unexpectedly narrowed return type of function `Store['getState']`

- docs/understanding/history-and-design/history-of-redux.md
Hi @markerikson,
I came across your insightful comment on this Reddit post [^1] and wanted to thank you for sharing your knowledge! It was a valuable resource for me.
I believe adding a reference to Dan Abramov's conference talk in the documentation could further enrich the learning experience for users like myself who are interested in delving deeper.
[^1]: https://www.reddit.com/r/reactjs/comments/18tzuyt/redux_what_problems_does_it_solve/
- **Section**: Understanding Redux > History and Design
- **Page**: The History of Redux
Add a link to Dan Abramov's demonstration for the Flux pattern at react-europe 2015.
No.
> docs: update History of Redux with conference talk link

- docs/usage/UsageWithTypescript.md
- docs/usage/WritingCustomMiddleware.md
---
---
- no
- yes  
- **Page**: Usage with TypeScript (**Section**: Typing `createAsyncThunk`) 
- **Page**: Writing Custom Middleware (**Section**: Create side effects for actions)
Misspelled word `whicher`
Misplaced space `th eaction`
Changes `whicher` to `whichever`
Changes `th eaction` to `the action`
> fix: typo in usage doc

- docs/introduction/LearningResources.md
---
name: Update link for Redux Middleware Tutorial
about: Fixing a broken link
- #4647
- **Section**: Learning Resources
- **Page**: https://redux.js.org/introduction/learning-resources#middleware
The resource for Redux Middleware Tutorial is pointing to a broken link.
The original link has been replaced with a GitHub repository containing notes authored by the original writer of the article. This new link provides access to the same content that was initially available on the author's blog.
> Update link for Redux Middleware Tutorial - Fix #4647

- examples/counter-vanilla/index.html
As the UMD builds has been dropped from Redux 5.0, import `redux.browser.mjs` instead.
> Fix counter vanilla example

- docs/usage/migrating-to-modern-redux.mdx
---
Documentation Fix
Fixing a problem in an existing docs page
---
- **Migrations: Migrating to Modern Redux (https://redux.js.org/usage/migrating-to-modern-redux)**:
- **Store Setup with configureStore (https://redux.js.org/usage/migrating-to-modern-redux#store-setup-with-configurestore)**:
At the end of the section "Store Setup with configureStore" the "Detailed Example: Custom Store Setup with Persistence and Middleware" example is given which uses Redux-Persist library. In the example configureStore's reducer is provided with rootReducer which is ambiguous due to the fact that persistor will be typically created after based on the created store. However, for example, when the persistor will be given to the PersistGate component, the app won't work as expected.
The code in the PR …
> [DOCS] replace root reducer with persisted reducer

- docs/usage/nextjs.mdx
When creating an application via `npx create-next-app --example with-redux my-app` (the method described in the documentation), the application does not create the `src` directory. 
[Related Issue](https://github.com/reduxjs/redux/issues/4656#issue-2068940198)
> fixed typo in nextjs docs

- docs/package.json
- docs/tutorials/typescript.md
- docs/usage/UsageWithTypescript.md
- docs/usage/WritingTests.mdx
- docs/usage/migrating-to-modern-redux.mdx
- docs/usage/nextjs.mdx
- docs/yarn.lock
- examples/counter-ts/src/app/hooks.ts
- package.json
- website/package.json
- website/yarn.lock
> Add `withTypes` to examples in docs

- README.md
The old logo used some GitHub token system that expired and the logo disappeared.
> Fix Redux logo

- docs/api/combineReducers.md
The Docs for Redux, in many places, cite moving to configureStore. Though `createStore` is still available, it is also marked as deprecated. This doc may need to update to reflect modern recommendations.
---
---
update an _existing_ page
- #4672 
- **Section**:
- **Page**:
https://redux.js.org/api/combinereducers
at anchor https://redux.js.org/api/combinereducers#appjs
code example
lower adopter/developer confusion on the approach to Redux. 
This update makes a huge assumption in blending of the lines of ownership/documents of use and responsibilities between Redux and @reduxjs/toolkit
> Closes #4672 Update combineReducers.md

- docs/tutorials/typescript.md
---
---
- **Page**: TypeScript Quick Start
The `app/store.ts` code snippet in the TypeScript Quick Start Tutorial should be updated to include the export keyword for the store constant, as demonstrated in the full example hosted in CodeSandbox within the same page and the snippet for the same file shown in the [`Code Quality > Usage with TypeScript > Define Root State and Dispatch Types`](https://github.com/reduxjs/redux/blob/master/docs/usage/UsageWithTypescript.md#define-root-state-and-dispatch-types) page.
This PR adds the export keyword to the store constant declaration in the `app/store.ts` file snippet, aligning with the implementation in the CodeSandbox example and other docs.
> TypeScript Quick Start Tutorial snippet change

- docs/usage/UsageWithTypescript.md
Update an existing page
- Not an issue, but a discussion: https://github.com/reduxjs/redux-toolkit/discussions/4312
- **Section**: Using Redux
- **Page**: Usage with Typescript
This adds a warning to the docs because a very commonly used ESLint rule (`@typescript-eslint/ban-types`) will recommend switching the `{}` dispatch argument for `Middleware` to something else `(like `Record<string, never>`), which will then break the store's types. As per the discussion linked above, the rule should be ignored for this line and you *need* to use `{}` here.
This might add an information not useful to some readers, but this page is for Typescript users, and typing middlewares is not very common, so the audience for this part should already be targeted, and there is a high probability of them using …
> Add a note to ignore `@typescript-eslint/ban-types` rule when typing middlewares

- docs/understanding/history-and-design/PriorArt.md
---
---
Update an existing page: [Understanding Redux > History and Design > Prior Art](https://redux.js.org/understanding/history-and-design/prior-art)
- No
- Yes
- **Section**: Understanding Redux
- **Page**: Prior Art
The [original Flux repository](https://github.com/facebookarchive/flux) was archived in March 2023 and has been moved to the [Meta Archive](http://github.com/facebookarchive) organization. This breaks the links to the Flux documentation. This PR  updates them to the corrected links.
No
> Updated broken links to the Flux documentation

- docs/usage/nextjs.mdx
---
about: Fix small typo
---
No
Yes
- **Section**: Using redux -> setup an organization -> NextJs
- **Page**: https://redux.js.org/usage/nextjs
3 small typos
fix typos
> Fix small typo in docs

- docs/tutorials/fundamentals/part-1-overview.md
- docs/tutorials/fundamentals/part-2-concepts-data-flow.md
- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
- docs/tutorials/fundamentals/part-4-store.md
- docs/tutorials/fundamentals/part-5-ui-and-react.md
- docs/tutorials/fundamentals/part-6-async-logic.md
- docs/tutorials/fundamentals/part-7-standard-patterns.md
- docs/tutorials/fundamentals/part-8-modern-redux.md
---
---
- **Section**: Redux Fundamentals
- **Page**: All 8 pages
We are using docusaurus for the docs and it will automatically add a header tag from the `title` attribute. So there is no need to add a redundant `h1` tag containing the same title. Currently in the [docs here ](https://redux.js.org/tutorials/fundamentals/part-1-overview) it will display 2 titles with same text which is not a good user experience.
I have removed the extra `h1` tag and now we leave it to docusaurus to render the page's title. This is how it has been done 
on the sections i.e. [Redux Essentials](https://redux.js.org/tutorials/essentials/part-1-overview-concepts)
> chore: updated docs to remove extra heading tag

- docs/usage/ServerRendering.md
- **Section**
Using Redux -> Setup and Organization 
- **Page**:
Server Rendering
The link was incorrect and leads to a blank page
I have inserted an up-to-date link to the react documentation
> fix: react renderToString docs link

- docs/usage/CodeSplitting.md
- docs/usage/WritingTests.mdx
---
---
Updating existing page 
- https://github.com/reduxjs/redux/issues/4662
- **Section**: Usage
- **Page**: Code Splitting
Now that RTK has its own code-splitting utilities (combineSlices and createDynamicMiddleware), it would be very useful to have an in-depth of how these are intended to be used, separate from the API reference.
This would avoid the standard "recipe" approach in the current docs in favour of depending on an actual library.
> Add combineSlices section to Code Splitting page

- .github/workflows/test.yaml
> Run CI jobs if `yarn.lock` changes

- src/types/middleware.ts
- test/typescript/middleware.test-d.ts
Fixes a type bug
The `getState` function provided by `MiddlewareAPI` is not bound to any object, and as such it can be used freely as in the examples.
The `MiddlewareAPI` type does not make this explicit, and typescript linters can report this as problematic usage.
- there's a file that needs formatting, but is outside the scope of my change: `docs/usage/deriving-data-selectors.md`
- No updates needed IMO
- No new tests added - the linting rules required to 
- Enable the [@typescript-eslint/unbound-method](https://typescript-eslint.io/rules/unbound-method/) linting rule
- Load up one of the examples
```ts
const middleware: Middleware<unknown, unknown> =
({ getState }) =>
(next) =>
(action) => {
// ...
};
```
- The linter will report that the rule is being violated …
> fix(types): getState is not bound to MiddlewareAPI

- docs/tutorials/essentials/part-4-using-data.md
Fixed a typo and changed highlighting
> Docs: Update part-4-using-data.md

- docs/tutorials/essentials/part-6-performance-normalization.md
Fixed typo in router
---
---
- **Section**:  #adding-user-pages
- **Page**: https://redux.js.org/tutorials/essentials/part-6-performance-normalization
React router dom, strictly use **element** attribute since v6  instead of **component**
> Docs: Update part-6-performance-normalization.md

- docs/tutorials/essentials/part-2-app-structure.md
- website/docusaurus.config.js
- Adds the "wide" image from #4748 as a site-wide top banner (sticky, so it hides as you scroll down)
- Throws in a text clarification I had sitting around about use of ESM syntax
> Add top Redux.dev banner

- docs/tutorials/essentials/part-4-using-data.md
---
---
- **Section**:
- **Page**: Part 4: Using Redux Data
`initialState` is an array of `Post`(defined in the same code block) not `Posts`
Reference the correct type name
> Fix typo in documentation: redux essentials

- docs/tutorials/essentials/part-2-app-structure.md
---
about: Add a missing period
---
- **Section**:
- **Page**:
> Add missing `.` to `part-2-app-structure.md`

- website/src/css/custom.css
for better UX, menu and TOC items style should indicate only one thing, which is the current read item
When you click on an item and then scroll to another .... notice: the prev item still having the same style as the current one.
> exclude menu and TOC items from the visited link styles for better UX

- docs/tutorials/essentials/part-5-async-logic.md
Fixes https://github.com/reduxjs/redux/issues/4766. See issue for details.
> Fix statement on Checking Async Thunk Conditions

- src/types/reducers.ts
- test/typescript/reducers.test-d.ts
- tsconfig.base.json
Fixes https://github.com/reduxjs/redux/issues/4764. See issue for details.
Note I had to enable `exactOptionalPropertyTypes` to reproduce the bug in the test.
> Fix issue with `combineReducer` returning incorrect type when given a custom action

- docs/tutorials/essentials/part-4-using-data.md
---
about: it's just a simple typo :)
---
> typo in part-4-using-data.md

- docs/tutorials/essentials/part-4-using-data.md
- docs/tutorials/essentials/part-5-async-logic.md
- docs/tutorials/essentials/part-7-rtk-query-basics.md
- docs/tutorials/essentials/part-8-rtk-query-advanced.md
- docs/tutorials/fundamentals/part-3-state-actions-reducers.md
- docs/usage/ServerRendering.md
- docs/usage/UsageWithTypescript.md
- docs/usage/migrating-to-modern-redux.mdx
I highlighted code lines in the tutorial that were changed but not highlighted. Also improved comment formatting.
> Improve docs and formatting

- docs/tutorials/essentials/part-4-using-data.md
---
---
fix #4770 
- [issue link](https://github.com/reduxjs/redux/issues/4770)
- **Section**: Redux Essentials, Part 4: Using Redux Data
The link is broken.
References an updated link.
> Fix the link referencing React Router docs

- .github/workflows/test.yaml
- package.json
- yarn.lock
> chore: update TypeScript version to 5.8

- website/package.json
- website/yarn.lock
> chore(docs): update `remark-typescript-tools` to fix broken code blocks

- docs/tutorials/essentials/part-2-app-structure.md
in essentials/part-2-app-structure
---
---
I couldn't find one
No code changes, only minor change in a `.md`.
- **Section**: `The React Counter Component`, `Component State and Forms`, `Providing the Store`
- **Page**: tutorials/essentials/part-2-app-structure
The documentation specifies wrong(`.js`) extension for multiple files.
Update extensions to .ts/.tsx to match the described example application.
> docs(tutorials): update file extensions to .ts/.tsx

- docs/usage/deriving-data-selectors.md
---
about: A small fix in an example code
---
- **Section**:  Using Redux
- **Page**: Deriving Data with Selectors
Example code snippet uses the `map` method in a place where `filter` method should be used instead.
```js
function TodoList() {
// highlight-start
// ❌ WARNING: this _always_ returns a new reference, so it will _always_ re-render!
const completedTodos = useSelector(state =>
state.todos.map(todo => todo.completed)
)
// highlight-end
}
```
`map` has been replaced with `filter`
> Replacing map with filter in an example

- docs/usage/deriving-data-selectors.md
---
about: Removing unnecessary memoization from a code example as it might confuse people
---
- **Section**: Writing Memoized Selectors with Reselect
- **Page**: Deriving Data with Selectors
Using (`createSelector`) for the `selectA1` selector directly contradicts the **Balance Selector Usage** section, which says in bold text the following: **A selector function that does a direct lookup and return of a value should be a plain function, not memoized.** Therefore this code example might confuse people about when to use memoization.
```js
const state = {
a: {
first: 5
},
b: 10
}
const selectA = state => state.a
const selectB = state => state.b
const selectA1 = createSelector([selectA], a => a.first)
const selectResult = createSelector([selectA1, selectB], …
```
> Remove unnecessary memoization from a code example

- docs/tutorials/essentials/part-6-performance-normalization.md
…e part-6-performance-normalization.md
In line 1218, the error is that this component is using the plain (untyped) useSelector hook:
const orderedPostIds = useSelector(selectPostIds)
which is inconsistent with the recommended best practice of using the typed useAppSelector hook for Redux Toolkit with TypeScript.
While it is supposed to be importing/using the already typed UseAppSelector from @/app/hooks:
import { useAppSelector, useAppDispatch } from '@/app/hooks':
// Corrected Version:
const orderedPostIds = useAppSelector(selectPostIds)
MORE DETAILS:
Description
This pull request fixes a bug in the documentation for the "Redux Essentials" tutorial. The PostsList component example was using the untyped useSelector hook, which is inconsistent with the recommended best practice of using …
> Docs: Fix incorrect useSelector usage in 'PostsList' Component; Update part-6-performance-normalization
